# Классические модели. Работа с широкими данными

автор: Алексей Космачев

В общем случае данные для машинного обучения могут быть большими в двух смыслах

* Очень много наблюдений. Визуализируя данные для обучения как таблицу наблюдения-признаки, можно это представлять как очень "высокую" таблицу с огромных количеством записей. По этой причине такую ситуацию еще называют "высокими данными".

* Очень много признаков. Проводя такую же аналогию с таблицей, она бы выглядела как очень "широкая таблица" с гигантским количеством столбцов. Такую ситуацию аналогично называют "широкими данными".

Обе ситуации требуют различных подходов для решения. В этом семинаре будет говорить про "широкие данные".

### А где встречаются широкие данные?

Ярким примером являются рекомндательные системы. Там любой user_id/item_id это признак, а их может быть бесконечно много. По этому поводу есть интересная работа - [SLIM](https://www-users.cse.umn.edu/~ningx005/slides/ICDM2011_slides.pdf) - интерпретируемая линейная регрессия для рекомендательных систем. Об этом можно почитать, например, здесь: [телеграм](https://t.me/WazowskiRecommends/14) или [медиум](https://roizner.medium.com/slim-a-fast-and-interpretable-baseline-for-recommender-algorithms-559cd73dcc55) (тот же пост на английском)

### Подготовим данные и инструменты для дальшей работы

In [1]:
! mkdir -p sem06
%cd sem06

/home/ubuntu/sem06

Для демонстрационных целей будем использовать датасет с отзывами пользователей на различные медицинские препараты

Больше информации на UCI - https://archive.ics.uci.edu/ml/datasets/Drug+Review+Dataset+%28Drugs.com%29

In [2]:
! wget https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
! unzip drugsCom_raw.zip

--2026-02-24 14:20:48--  https://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip’

drugsCom_raw.zip        [           <=>      ]  41.00M   440KB/s    in 2m 40s

2026-02-24 14:23:29 (262 KB/s) - ‘drugsCom_raw.zip’ saved [42989872]

/bin/bash: unzip: command not found

In [4]:
! unzip drugsCom_raw.zip

Archive:  drugsCom_raw.zip
  inflating: drugsComTest_raw.tsv
  inflating: drugsComTrain_raw.tsv

In [5]:
! head drugsComTest_raw.tsv

Основной инструмент, который будем сегодня изучать - это Vowpal Wabbit.

Больше информации можно найти на официальном сайте - https://vowpalwabbit.org/

Ниже скачаем уже собранную версию VW , готовую к использованию

In [6]:
! whoami

ubuntu

In [7]:
! sudo wget http://finance.yendor.com/ML/VW/Binaries/vw-8.20190624 -O /usr/bin/vw
! sudo chmod +x /usr/bin/vw
! sudo chown ubuntu /usr/bin/vw

--2026-02-24 14:25:24--  http://finance.yendor.com/ML/VW/Binaries/vw-8.20190624
Resolving finance.yendor.com (finance.yendor.com)... 75.119.201.70
Connecting to finance.yendor.com (finance.yendor.com)|75.119.201.70|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://finance.yendor.com/ML/VW/Binaries/vw-8.20190624 [following]
--2026-02-24 14:25:24--  https://finance.yendor.com/ML/VW/Binaries/vw-8.20190624
Connecting to finance.yendor.com (finance.yendor.com)|75.119.201.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9467376 (9.0M)
Saving to: ‘/usr/bin/vw’

/usr/bin/vw         100%[===================>]   9.03M  4.85MB/s    in 1.9s

2026-02-24 14:25:27 (4.85 MB/s) - ‘/usr/bin/vw’ saved [9467376/9467376]

И заодно поставим всякие стандартные питоновские библиотеки для анализа данных

In [9]:
! sudo apt-get update -y && sudo apt-get install graphviz -y

Hit:1 http://mirror.yandex.ru/ubuntu focal InRelease
Hit:2 http://mirror.yandex.ru/ubuntu focal-updates InRelease
Hit:3 http://mirror.yandex.ru/ubuntu focal-backports InRelease
Hit:4 http://dataproc.storage.yandexcloud.net/ci/trunk/225-54615002560eee21 focal InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:6 https://repos.influxdata.com/ubuntu focal InRelease [12.9 kB]
Err:7 http://mirror.yandex.ru/mirrors/postgresql focal-pgdg InRelease
  421  Misdirected Request [IP: 213.180.204.183 80]
Err:6 https://repos.influxdata.com/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA61C26A0585BD3B
Hit:8 https://packages.fluentbit.io/ubuntu/focal focal InRelease
Hit:9 https://packages.broadcom.com/artifactory/saltproject-deb stable InRelease
Reading package lists... Done
E: Failed to fetch http://mirror.yandex.ru/mirrors/postgresql/dists/focal-pgdg/InRelease  421  Misdirected Request [IP: 213.180.204.183 80]
E: The repository 'http://mirror.yandex.ru/mirrors/postgresql focal-pgdg InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repos.influxdata.com/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY DA61C26A0585BD3B

In [10]:
! pip install numpy pandas scikit-learn dateparser pandarallel ipywidgets catboost graphviz

Collecting numpy
  Downloading numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
     |████████████████████████████████| 17.3 MB 1.6 MB/s eta 0:00:01
Collecting pandas
  Downloading pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 49.2 MB/s eta 0:00:01
Collecting scikit-learn
  Downloading scikit_learn-1.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.1 MB)
     |████████████████████████████████| 11.1 MB 53.4 MB/s eta 0:00:01
Collecting dateparser
  Downloading dateparser-1.2.2-py3-none-any.whl (315 kB)
     |████████████████████████████████| 315 kB 80.9 MB/s eta 0:00:01
Collecting pandarallel
  Downloading pandarallel-1.6.5.tar.gz (14 kB)
Collecting ipywidgets
  Downloading ipywidgets-8.1.8-py3-none-any.whl (139 kB)
     |████████████████████████████████| 139 kB 74.0 MB/s eta 0:00:01
Collecting catboost
  Downloading catboost-1.2.10-cp38-cp38-manylinux2014_x86_64.whl (97.1 MB)
     |████████████████████████████████| 97.1 MB 115 kB/s  eta 0:00:01
Collecting graphviz
  Downloading graphviz-0.20.3-py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 7.9 MB/s  eta 0:00:01
Collecting tzdata>=2022.1
  Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
     |████████████████████████████████| 348 kB 61.1 MB/s eta 0:00:01
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     |████████████████████████████████| 229 kB 59.8 MB/s eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 70.9 MB/s eta 0:00:01
Collecting joblib>=1.1.1
  Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
     |████████████████████████████████| 301 kB 60.5 MB/s eta 0:00:01
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Collecting scipy>=1.5.0
  Downloading scipy-1.10.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     |████████████████████████████████| 34.5 MB 57.1 MB/s eta 0:00:01
Collecting regex>=2024.9.11
  Downloading regex-2024.11.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (785 kB)
     |████████████████████████████████| 785 kB 73.9 MB/s eta 0:00:01
Collecting tzlocal>=0.2
  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Collecting dill>=0.3.1
  Downloading dill-0.4.0-py3-none-any.whl (119 kB)
     |████████████████████████████████| 119 kB 76.9 MB/s eta 0:00:01
Collecting psutil
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
     |████████████████████████████████| 155 kB 63.6 MB/s eta 0:00:01
Collecting ipython>=6.1.0
  Downloading ipython-8.12.3-py3-none-any.whl (798 kB)
     |████████████████████████████████| 798 kB 70.2 MB/s eta 0:00:01
Collecting widgetsnbextension~=4.0.14
  Downloading widgetsnbextension-4.0.15-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 64.7 MB/s eta 0:00:01
Collecting jupyterlab_widgets~=3.0.15
  Downloading jupyterlab_widgets-3.0.16-py3-none-any.whl (914 kB)
     |████████████████████████████████| 914 kB 77.0 MB/s eta 0:00:01
Collecting traitlets>=4.3.1
  Downloading traitlets-5.14.3-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 6.1 MB/s  eta 0:00:01
Collecting comm>=0.1.3
  Downloading comm-0.2.3-py3-none-any.whl (7.3 kB)
Collecting plotly
  Downloading plotly-6.5.2-py3-none-any.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 71.0 MB/s eta 0:00:01
Collecting matplotlib
  Downloading matplotlib-3.7.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB 57.5 MB/s eta 0:00:01
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from catboost) (1.14.0)
Collecting backports.zoneinfo; python_version < "3.9"
  Downloading backports.zoneinfo-0.2.1-cp38-cp38-manylinux1_x86_64.whl (74 kB)
     |████████████████████████████████| 74 kB 5.0 MB/s  eta 0:00:01
Collecting pygments>=2.4.0
  Downloading pygments-2.19.2-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 58.6 MB/s eta 0:00:01
Collecting decorator
  Downloading decorator-5.2.1-py3-none-any.whl (9.2 kB)
Collecting matplotlib-inline
  Downloading matplotlib_inline-0.1.7-py3-none-any.whl (9.9 kB)
Collecting backcall
  Downloading backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pickleshare
  Downloading pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting typing-extensions; python_version < "3.10"
  Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.8 MB/s  eta 0:00:01
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30
  Downloading prompt_toolkit-3.0.52-py3-none-any.whl (391 kB)
     |████████████████████████████████| 391 kB 67.6 MB/s eta 0:00:01
Requirement already satisfied: pexpect>4.3; sys_platform != "win32" in /usr/lib/python3/dist-packages (from ipython>=6.1.0->ipywidgets) (4.6.0)
Collecting stack-data
  Downloading stack_data-0.6.3-py3-none-any.whl (24 kB)
Collecting jedi>=0.16
  Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 72.2 MB/s eta 0:00:01
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from plotly->catboost) (20.3)
Collecting narwhals>=1.15.1
  Downloading narwhals-1.42.1-py3-none-any.whl (359 kB)
     |████████████████████████████████| 359 kB 61.1 MB/s eta 0:00:01
Collecting contourpy>=1.0.1
  Downloading contourpy-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (301 kB)
     |████████████████████████████████| 301 kB 52.0 MB/s eta 0:00:01
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3/dist-packages (from matplotlib->catboost) (2.4.6)
Collecting importlib-resources>=3.2.0; python_version < "3.10"
  Downloading importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Collecting cycler>=0.10
  Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0
  Downloading fonttools-4.57.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.7 MB)
     |████████████████████████████████| 4.7 MB 52.8 MB/s eta 0:00:01
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.7-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 60.4 MB/s eta 0:00:01
Collecting pillow>=6.2.0
  Downloading pillow-10.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 66.5 MB/s eta 0:00:01
Collecting wcwidth
  Downloading wcwidth-0.6.0-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 5.6 MB/s  eta 0:00:01
Collecting pure-eval
  Downloading pure_eval-0.2.3-py3-none-any.whl (11 kB)
Collecting executing>=1.2.0
  Downloading executing-2.2.1-py2.py3-none-any.whl (28 kB)
Collecting asttokens>=2.1.0
  Downloading asttokens-3.0.1-py3-none-any.whl (27 kB)
Collecting parso<0.9.0,>=0.8.4
  Downloading parso-0.8.6-py2.py3-none-any.whl (106 kB)
     |████████████████████████████████| 106 kB 70.8 MB/s eta 0:00:01
Collecting zipp>=3.1.0; python_version < "3.10"
  Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.5-py3-none-any.whl size=16678 sha256=1001cb6888f3692ed52aca91a1701fae47e901ee0080784584fe507c4e3dc3d1
  Stored in directory: /home/ubuntu/.cache/pip/wheels/c7/e9/78/48eb140b79de41c4d9440938ef5f9e3186c979183fe57829b3
Successfully built pandarallel
Installing collected packages: numpy, tzdata, python-dateutil, pytz, pandas, joblib, threadpoolctl, scipy, scikit-learn, regex, backports.zoneinfo, tzlocal, dateparser, dill, psutil, pandarallel, pygments, decorator, traitlets, matplotlib-inline, backcall, pickleshare, typing-extensions, wcwidth, prompt-toolkit, pure-eval, executing, asttokens, stack-data, parso, jedi, ipython, widgetsnbextension, jupyterlab-widgets, comm, ipywidgets, narwhals, plotly, contourpy, zipp, importlib-resources, cycler, fonttools, kiwisolver, pillow, matplotlib, graphviz, catboost

  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dateparser-download is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts ipython and ipython3 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script plotly_get_chrome is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools, pyftmerge, pyftsubset and ttx are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed asttokens-3.0.1 backcall-0.2.0 backports.zoneinfo-0.2.1 catboost-1.2.10 comm-0.2.3 contourpy-1.1.1 cycler-0.12.1 dateparser-1.2.2 decorator-5.2.1 dill-0.4.0 executing-2.2.1 fonttools-4.57.0 graphviz-0.20.3 importlib-resources-6.4.5 ipython-8.12.3 ipywidgets-8.1.8 jedi-0.19.2 joblib-1.4.2 jupyterlab-widgets-3.0.16 kiwisolver-1.4.7 matplotlib-3.7.5 matplotlib-inline-0.1.7 narwhals-1.42.1 numpy-1.24.4 pandarallel-1.6.5 pandas-2.0.3 parso-0.8.6 pickleshare-0.7.5 pillow-10.4.0 plotly-6.5.2 prompt-toolkit-3.0.52 psutil-7.2.2 pure-eval-0.2.3 pygments-2.19.2 python-dateutil-2.9.0.post0 pytz-2025.2 regex-2024.11.6 scikit-learn-1.3.2 scipy-1.10.1 stack-data-0.6.3 threadpoolctl-3.5.0 traitlets-5.14.3 typing-extensions-4.13.2 tzdata-2025.3 tzlocal-5.2 wcwidth-0.6.0 widgetsnbextension-4.0.15 zipp-3.20.2

In [11]:
!pip install --upgrade --force-reinstall pandarallel

Processing /home/ubuntu/.cache/pip/wheels/c7/e9/78/48eb140b79de41c4d9440938ef5f9e3186c979183fe57829b3/pandarallel-1.6.5-py3-none-any.whl
Collecting psutil
  Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Collecting pandas>=1
  Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting dill>=0.3.1
  Using cached dill-0.4.0-py3-none-any.whl (119 kB)
Collecting numpy>=1.20.3; python_version < "3.10"
  Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
Collecting tzdata>=2022.1
  Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Collecting python-dateutil>=2.8.2
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting pytz>=2020.1
  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Collecting six>=1.5
  Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
Installing collected packages: psutil, numpy, tzdata, six, python-dateutil, pytz, pandas, dill, pandarallel
  Attempting uninstall: psutil
    Found existing installation: psutil 7.2.2
    Uninstalling psutil-7.2.2:
      Successfully uninstalled psutil-7.2.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.4
    Uninstalling numpy-1.24.4:
      Successfully uninstalled numpy-1.24.4
  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: tzdata
    Found existing installation: tzdata 2025.3
    Uninstalling tzdata-2025.3:
      Successfully uninstalled tzdata-2025.3
  Attempting uninstall: python-dateutil
    Found existing installation: python-dateutil 2.9.0.post0
    Uninstalling python-dateutil-2.9.0.post0:
      Successfully uninstalled python-dateutil-2.9.0.post0
  Attempting uninstall: pytz
    Found existing installation: pytz 2025.2
    Uninstalling pytz-2025.2:
      Successfully uninstalled pytz-2025.2
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
  Attempting uninstall: dill
    Found existing installation: dill 0.4.0
    Uninstalling dill-0.4.0:
      Successfully uninstalled dill-0.4.0
  Attempting uninstall: pandarallel
    Found existing installation: pandarallel 1.6.5
    Uninstalling pandarallel-1.6.5:
      Successfully uninstalled pandarallel-1.6.5
Successfully installed dill-0.4.0 numpy-1.24.4 pandarallel-1.6.5 pandas-2.0.3 psutil-7.2.2 python-dateutil-2.9.0.post0 pytz-2025.2 six-1.17.0 tzdata-2025.3

In [12]:
! pip install psutil

Requirement already satisfied: psutil in /home/ubuntu/.local/lib/python3.8/site-packages (7.2.2)

In [13]:
! /opt/conda/bin/jupyter nbextension enable --py widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

In [15]:
# Проверяем, что vw работает
! vw --help | head

Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
driver:
  --onethread           Disable parse thread
VW options:
  --ring_size arg (=256, ) size of example ring
  --strict_parse           throw on malformed examples
Update options:
  -l [ --learning_rate ] arg Set learning rate
  --power_t arg              t power value
  --decay_learning_rate arg  Set Decay factor for learning_rate between passes
  --initial_t arg            initial t value

## Хеширование признаков. Линейные модели.

Vowpal Wabbit - инструмент от компании Microsoft, который позволяет очень эффективно обучать линейные модели. Ключевая особенность данного инструмента - использования хешинг-трика. То есть все признаки изначально хешируются, что позволяет модели эффективно обрабатывать практически произвольное количество признаков.

In [12]:
изначальные признаки:
x1 = 1
x2 = 0
.
.
.
xn = 5

n >> 1M

что хотим получить по набору признаков:
y1
y2
.
.
.
yk

k << n


h - hash function, h : x_{i} -> [0, k)
h(x_{i}) \forall i

h(x1)
h(x2)
...
h(xn)
                                 
                                 
h(xi) = h(xj) 
value(xi), value(xj) -> mean(value(xi), value(xj)), max(value(xi), value(xj)), min(value(xi), value(xj))


[1, 0, 0, 0, ....., 1, 0, ..., 1]
[0, 0, 0, 0, ....., 0, ...1, ...0, ..., 1]
x1, ..., xm, m << n (n - maximum)
hash(xm+t) = h(xm)

SyntaxError: invalid syntax (<ipython-input-12-05c193904dc7>, line 1)

### Формат данных
VW для обучения требует свой особенный формат хранения данных. Он выглядит следующим образом:

```
[Label] [Importance] [Tag]|Namespace Features |Namespace Features ... |Namespace Features
```

* Label - значение целевой переменной. Если не указывать, объект не будет использоваться в обучении
* Importance - вес объекта. Если не указывать, равен 1
* Tag - пометка объекта. Никак не влияет на процесс обучения, но добавляет семантики и "читаемости" данных для человека
* Namespace - название области признаков. Используется, чтобы разные по сути признаки с одинаковым названием не пересекались
* Features - признаки. Это или пара <название признака>:<значение признака> или просто <название признака>. В последнем случае будет считаться, что значение равно 1

Например, попробуем закодировать несколько элементов из Iris в этом формате

| Длина чашелистика | Ширина чашелистика | Длина лепестка | Ширина лепестка |  Вид ириса |
|:-----------------:|:------------------:|:--------------:|:---------------:|:----------:|
| 5.1               | 3.5                | 1.4            | 0.2             | setosa     |
| 4.9               | 3.0                | 1.4            | 0.2             | setosa     |
| 7.0               | 3.2                | 4.7            | 1.4             | versicolor |

Будем считать setosa классом 1, а versicolor классом -1.

In [16]:
%%writefile iris_1.example.vw
1 | sepal_length:5.1 sepal_width:3.5 petal_length:1.4 petal_width:0.2
1 | sepal_length:4.9 sepal_width:3.0 petal_length:1.4 petal_width:0.2
-1 | sepal_length:7.0 sepal_width:3.2 petal_length:4.7 petal_width:1.4

Writing iris_1.example.vw

В данном наборе мы дополнительно можем сгруппировать признаки - признаки для чашелистика и признаки для лепестка. Это позволит логически их разделить, сэкономит место, а также позволит в дальнейшем оперировать этими группами.

Запишем точно эти же данные, но с использованием именованных секций.

In [17]:
%%writefile iris_2.example.vw
1 |sepal length:5.1 width:3.5 |petal length:1.4 width:0.2
1 |sepal length:4.9 width:3.0 |petal length:1.4 width:0.2
-1 |sepal length:7.0 width:3.2 |petal length:4.7 width:1.4

Writing iris_2.example.vw

Подобный формат записи данных позволяет очень удобно записывать категориальные признаки в формате One-Hot Encoding. При таком кодировании мы бы для признака, соответствующего конкретной категории, выставили бы значение 1, а всем остальным - 0.

Например для признака с полом человека превратится в два признака

| gender_man | gender_woman |
|:----------:|:------------:|
| 1          | 0            |

Если же в VW не указывать явно значение признака, то оно будет в автоматическом режиме выставлено равным 1, чего мы и ожидаем при One-Hot кодировании.

Попробуем для примера записать вот такие данные в этом формате

| Класс |  Цвет фона | Включена ли темная тема | Размер шрифта | Межстрочный интервал |
|:-----:|:----------:|:-----------------------:|:-------------:|:--------------------:|
| 1     | White      | да                      | 12            | 1.5                  |
| -1    | Black      | нет                     | 14            | 1.5                  |
| 1     | White, Red | нет                     | 12            | 2                    |
| -1    | Black, Red | да                      | 15            | 1.5                  |

In [19]:
%%writefile design.example.vw
1 |color white |theme dark |font size:12.0 interval:1.5
-1 |color black |theme normal |font size:14.0 interval:1.5
1 |color white red |theme normal:1 |font size: 12.0 interval:2.0
-1 |color black red |theme dark |font size: 15.0 interval:1.5

Overwriting design.example.vw

Можно заметить, что такой подход к кодированию также позволяет очень просто кодировать текстовые признаки в формате bag-of-words. При использовании bag-of-words мы для каждого слова добавляет отдельный бинарный признак, который равен 1, если слово есть в тексте.

Таким образом, чтобы закодировать в формате vw какой-то текст через bag-of-words достаточно... Просто написать этот текст! Единственное, что необходимо сделать дополнительно - это очистить сам текст от лишних символов, таких как знаки препинания, удаления, кавычки и так далее. Очищенный текст - это и есть кодирование признаков в vw.

Попробуем, например, закодировать вот такой набор данных.

| Оценка |                             Заголовок                              |                                                                      Комментарий                                                                     |
|:------:|:------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------:|
| 2      | To lazy to watch film                                              | My family and I normally do not watch local movies for the simple reason that they are poorly made                                                   |
| 5      | Well-directed and fairly notorious piece of Italian nunsploitation | This file is a genuinely moving and intelligent movie with plenty of nudity and gore.You can't go wrong with it.5 out of 5.                         |
| 3      | this was at one time the worst movie I had ever seen               | But since than time, I have seen many more movies that are worse (how is it possible??) Therefore, to be fair, I had to give this movie a 3 out of 5 |

In [20]:
%%writefile reviews.vw
2.0 |title to lazy to watch film |review my family and i normally do not watch local movies for the simple reason that they are poorly made
5.0 |title well directed and fairly notorious piece of italian nunsploitation |review this file is a genuinely moving and intelligent movie with plenty of nudity and gore you can t go wrong with it 8 out of 10 
3.0 |title this was at one time the worst movie i had ever seen |review but since than time  i have seen many more movies that are worse how is it possible  therefore to be fair  i had to give this movie a 3 out of 5

Writing reviews.vw

In [21]:
! cat reviews.vw

2.0 |title to lazy to watch film |review my family and i normally do not watch local movies for the simple reason that they are poorly made
5.0 |title well directed and fairly notorious piece of italian nunsploitation |review this file is a genuinely moving and intelligent movie with plenty of nudity and gore you can t go wrong with it 8 out of 10
3.0 |title this was at one time the worst movie i had ever seen |review but since than time  i have seen many more movies that are worse how is it possible  therefore to be fair  i had to give this movie a 3 out of 5

В этом примере именованные секции играют важную роль, так как одно и тоже слово может оказаться и в заголовке и в тексте комментария. Без секций мы бы считали это одним признаком. Секции позволяют нам разделять слова, которые использовались в заголовке от слов, которые использовались в описании.

Итак, мы научились формировать данные для VW, самое время запустить его. Попробуем использовать наши примеры.

In [22]:
! cat reviews.vw

2.0 |title to lazy to watch film |review my family and i normally do not watch local movies for the simple reason that they are poorly made
5.0 |title well directed and fairly notorious piece of italian nunsploitation |review this file is a genuinely moving and intelligent movie with plenty of nudity and gore you can t go wrong with it 8 out of 10
3.0 |title this was at one time the worst movie i had ever seen |review but since than time  i have seen many more movies that are worse how is it possible  therefore to be fair  i had to give this movie a 3 out of 5

In [23]:
## запуск vw
! vw reviews.vw --final_regressor reviews.model.bin

final_regressor = reviews.model.bin
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = reviews.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
4.000000 4.000000            1            1.0   2.0000   0.0000       25
13.653724 23.307447            2            2.0   5.0000   0.1722       36

finished run
number of examples = 3
weighted example sum = 3.000000
weighted label sum = 10.000000
average loss = 10.574909
best constant = 3.333333
total feature number = 106

In [24]:
! cat reviews.model.bin

   8.7.0     m      �@                      �dA�    ;9�=�"  ��=�.  ;9�=�6  �#k=Q=  �#k=QN  ��=>d   a0=�m  DC�=Fx  ��=��   a0=ݕ   a0=�  �#k=H�  ;9�=:�   a0=G�  �p�=��   a0=��  ��=�  ��=9�   a0=� �#k=�2 ��=4 ��=@ H
�  a0=� ��=� ��=� �p�=k� ;9�=\� 4
>p� �#k=L�  a0=Z�  a0=� �#k=��  a0==�  a0=�� �#k=�! �#k=*7 ��=�8 �ly=�:  a0=�; ��=�Q �#k=�U �#k=KY ��=�] �#k=_ �>ri ��=?�  a0=N� �#k=�� ��=К  a0=�  a0=�� ��=F� �#k=�  a0=B�  a0=�� ��=��  a0=� �#k=k  a0=� ��=� SQ�=y.  a0=MB  a0=+Q  a0=\T ��=�Y ��=�o ;9�=o ;9�=$� �#k=�  a0=v� �#k=�� �p�=]� �a�=�� �#k=�� ��=+�  a0=�� ��=��  a0=

На экране можно видеть отчет обучения, а в файл `reviews_result.vw.bin` записались веса модели. По-умолчанию используется линейная регрессия с MSE.

Для того, чтобы получить предсказания нет отдельной команды. Это связано с особым форматом работы инструмента. Можно считать, что vw всегда запускается в режиме обучения, однако есть несколько флагов, которые умеют контролировать этот процесс.

Схематично это можно изобразить на картинке

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vw-explanation.png" width="600">

Таким образом при каждом запуске VW получает входные данные, с которыми он сейчас будет работать. Далее он начинает обучение на этих данных. Если указан `--initial_regressor` то он возьмет указанные веса в качестве начальных - то есть попытается "дообучить" модель, которую мы указали. Параллельно с этим для каждого пройденного элемента он производит предсказание. Если указать параметр `--predictions`, то эти данные он отдельно запишет в файл. По окончанию обучения новые полученные веса он попробует сохранить в файл, указанный через `--final_regressor`. И также есть очень важный флаг `--testonly`, говорящий о том, что обновлять веса (то есть обучаться) в процессе не требуется.

Подобная схема позволяет более гибко задавать режимы работы. Вот возможные сценарии работы, которые можно выставить этими ключами.

* `--final_regressor` - просто обучаем модель на данных
* `--testonly`, `--initial_regressor`, `--predictions` - просто делаем предсказания модели на данных
* `--final_regressor`, `--initial_regressor` - дообучаем модель на новых данных

И так далее. Попробуем сделать предсказание на нашем же примере.

In [25]:
! vw --testonly \
    --initial_regressor reviews.model.bin \
    --predictions reviews_prediction.txt \
    reviews.vw

only testing
predictions = reviews_prediction.txt
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = reviews.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.042279 0.042279            1            1.0   2.0000   1.7944       25
2.310258 4.578236            2            2.0   5.0000   2.8603       36

finished run
number of examples = 3
weighted example sum = 3.000000
weighted label sum = 10.000000
average loss = 1.583771
best constant = 3.333333
total feature number = 106

In [26]:
! cat reviews_prediction.txt

1.794381
2.860319
2.638340

In [27]:
! cat reviews.vw

2.0 |title to lazy to watch film |review my family and i normally do not watch local movies for the simple reason that they are poorly made
5.0 |title well directed and fairly notorious piece of italian nunsploitation |review this file is a genuinely moving and intelligent movie with plenty of nudity and gore you can t go wrong with it 8 out of 10
3.0 |title this was at one time the worst movie i had ever seen |review but since than time  i have seen many more movies that are worse how is it possible  therefore to be fair  i had to give this movie a 3 out of 5

### Решаем реальную задачу

Подключим все необходимые библиотеки и прочитаем данные

In [28]:
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip

--2026-02-24 14:28:40--  http://archive.ics.uci.edu/ml/machine-learning-databases/00462/drugsCom_raw.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified
Saving to: ‘drugsCom_raw.zip.1’

drugsCom_raw.zip.1      [                <=> ]  41.00M  10.4MB/s    in 4.1s

2026-02-24 14:28:44 (9.91 MB/s) - ‘drugsCom_raw.zip.1’ saved [42989872]

In [29]:
!unzip drugsCom_raw.zip

Archive:  drugsCom_raw.zip
replace drugsComTest_raw.tsv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ^C

In [30]:
import pandas as pd
import numpy as np
import re
import dateparser
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
!sudo pip install --upgrade psutil

Collecting psutil
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
     |████████████████████████████████| 155 kB 761 kB/s eta 0:00:01
Installing collected packages: psutil
Successfully installed psutil-7.2.2

In [32]:
from pandarallel import pandarallel
pandarallel.initialize(use_memory_fs=False, progress_bar=True)

INFO: Pandarallel will run on 2 workers.
INFO: Pandarallel will use standard multiprocessing data transfer (pipe) to transfer data between the main process and workers.

In [33]:
df_train = pd.read_csv("drugsComTrain_raw.tsv", delimiter='\t')
df_test = pd.read_csv("drugsComTrain_raw.tsv", delimiter='\t')
df = pd.concat([df_train, df_test])

In [34]:
df.dropna(inplace=True)

In [35]:
df

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
...,...,...,...,...,...,...,...
161292,191035,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10.0,"May 31, 2015",125
161293,127085,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1.0,"November 1, 2011",34
161294,187382,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2.0,"March 15, 2014",35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10.0,"September 19, 2015",79
161296,215220,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9.0,"December 13, 2014",116

Задачу для обучения мы можем поставить себе произвольную. Чтобы было наглядно и в обучающей выборке было много разных признаков сформулируем задачу такую - **По написанному отзыву одного пользователя, определить какому количеству других пользователей эта информация окажется полезной**

Таким образом у нас изначально есть всего 4 признака следующей природы
* `drugName` - категория
* `condigion` - категория
* `review` - произвольный текст
* `rating` - вещественное число

А целевая переменная это `usefulCount` - тоже вещественное число

Подсчитаем количество признаков, которое нам потребуется для кодирования всех этих признаков, чтобы их можно было подать в линейную модель.

Категории будем колировать One-Hot, текст через Bag-of-Words, из временной метки сделаем категориальную переменную с днями недели, а вещественные будет подавать как есть.

In [36]:
len(df['drugName'].unique())  # Количество уникальных препаратов

3431

In [37]:
len(df['condition'].unique())  # Количество уникальных заболеваний

884

In [38]:
len(CountVectorizer().fit(df['review']).get_feature_names_out()) # Количество уникальных слов в корпусе

49855

Итого уже 3431 + 884 + 49855 + 1 = **54 178** признаков для кодирования.

In [39]:
def convert_to_vw(data):
    target = data['usefulCount']
    
    drug_name = data['drugName'].lower().replace(' ', '_')
    condition = data['condition'].lower().replace(' ', '_')
    
    raw_text = data['review'].lower()
    word_pattern = re.compile(r"[a-zA-Z0-9_]+")
    words = [match.group(0) for match in re.finditer(word_pattern, raw_text)]
    review = ' '.join(words)
    
    rating = data['rating']

    
    template = "{target} |d {drug_name} |c {condition} |r {review} |s rating:{rating}"
    return template.format(
        target=target,
        drug_name=drug_name,
        condition=condition,
        review=review,
        rating=rating
    )

In [40]:
_, example = next(df.iterrows())
example

Unnamed: 0                                                206461
drugName                                               Valsartan
condition                           Left Ventricular Dysfunction
review         "It has no side effect, I take it in combinati...
rating                                                       9.0
date                                                May 20, 2012
usefulCount                                                   27
Name: 0, dtype: object

In [41]:
convert_to_vw(example)

'27 |d valsartan |c left_ventricular_dysfunction |r it has no side effect i take it in combination of bystolic 5 mg and fish oil |s rating:9.0'

In [42]:
def write_vw(dataframe, filename):
    with open(filename, 'w') as f:
        for vw_record in dataframe.parallel_apply(convert_to_vw, axis=1):
            f.write(vw_record + '\n')

In [43]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=420)

In [44]:
%%time

write_vw(df_train, 'drugs.train.vw')
write_vw(df_test, 'drugs.test.vw')

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=128318), Label(value='0 / 128318')…

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=32080), Label(value='0 / 32080')))…

CPU times: user 841 ms, sys: 872 ms, total: 1.71 s
Wall time: 10.2 s

In [45]:
! head -n 2 drugs.train.vw

17 |d anaprox-ds |c pain |r i recommend if for girls if they have menstrual pain it helps alot 10 15 mins after i take the pill i feel no more pain |s rating:10.0
1 |d levetiracetam |c epilepsy |r as a 42 year old female i have had seizures my entire life i have taken 14 anti convulsants at one point or another in an attempt to control my complex partial seizures but keppra is the worst medication i have ever taken the side effects are horrible although it 039 s the only medication that has been able to stop my seizures the side effects are so terrible that it 039 s not worth taking it i couldn 039 t string together a coherent thought had short term memory loss had awful mood swings and suddenly hated life everything was difficult i couldn 039 t think straight and felt emotionally raw all the time i could barely keep it together while on this medication every day of life was awful while on this medication i will never take it again |s rating:1.0

Итого мы разбили выборку на обучающую и тестовую и закодировали эти данные в нужном формате. Можно начинать обучать машины!

#### Запускаем чистый VW

Поставим обучаться VW без дополнительных параметров на нашем датасете

In [46]:
! cat drugs.train.vw | wc -l

256636

In [47]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw

final_regressor = drugs.model.bin
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       30
145.348644 1.697287            2            2.0   1.0000   2.3028      145
240.409956 335.471268            4            4.0   7.0000   7.9989      157
1483.276169 2726.142381            8            8.0  24.0000   4.0544       73
827.101424 170.926679           16           16.0  11.0000  14.8396      137
2549.058402 4271.015380           32           32.0 135.0000   6.7423       55
2170.529700 1792.000997           64           64.0   9.0000  32.8455      150
1650.839727 1131.149754          128          128.0   4.0000  32.2044      149
1504.761907 1358.684087          256          256.0   3.0000  14.4195       88
1625.316700 1745.871493          512          512.0   5.0000   7.0946       26
1475.857534 1326.398367         1024         1024.0  72.0000  32.2698      111
1347.566841 1219.276149         2048         2048.0  29.0000  15.0549       48
1265.555108 1183.543375         4096         4096.0 156.0000  21.0076       49
1386.092046 1506.628984         8192         8192.0  32.0000  65.1222      257
1280.718251 1175.344457        16384        16384.0   4.0000  42.1068      148
1208.551133 1136.384015        32768        32768.0  16.0000  12.5752       85
1216.762133 1224.973133        65536        65536.0  26.0000  36.5765       57
1137.727417 1058.692700       131072       131072.0  97.0000  63.4455      123

finished run
number of examples = 256636
weighted example sum = 256636.000000
weighted label sum = 7199651.000000
average loss = 1093.414733
best constant = 28.053940
total feature number = 23746542
CPU times: user 41.3 ms, sys: 16.5 ms, total: 57.7 ms
Wall time: 1.63 s

In [48]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

only testing
predictions = drugs.preductions.txt
Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000       74
1793.657227 3551.314453            2            2.0  76.0000  16.4071       10
1092.279785 390.902344            4            4.0   4.0000   0.0000       68
884.345149 676.410512            8            8.0  23.0000  20.4742       44
507.483603 130.622057           16           16.0   7.0000  23.0774      126
508.988668 510.493733           32           32.0  13.0000  17.7603       47
596.315355 683.642042           64           64.0   3.0000  10.9192      108
1069.053975 1541.792594          128          128.0   9.0000  27.1967      115
999.484723 929.915471          256          256.0  29.0000  17.7026       60
1405.514523 1811.544323          512          512.0   5.0000  11.3577       33
2595.465846 3785.417170         1024         1024.0   9.0000  20.3570       96
1831.956867 1068.447887         2048         2048.0   7.0000   0.0871      104
1480.169832 1128.382798         4096         4096.0   5.0000   1.2220      133
1219.172720 958.175608         8192         8192.0  12.0000  15.0112       59
1283.453369 1347.734017        16384        16384.0   2.0000  11.4544      102
1193.752325 1104.051280        32768        32768.0  65.0000  63.0970      129

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 1167.618861
best constant = 28.272305
total feature number = 5932516

In [49]:
! head drugs.preductions.txt

0
16.407093
49.673176
0
25.992844
31.923294
32.541691
20.474159
13.278885
41.239552

Для проверки качества регрессии будем считать обычный `R^2`. Для того, чтобы делать это просто, напишем функцию, которая будет считывать правильные ответы из vw файла, считывать предсказания и для них подсчитывать R2.

In [50]:
def calc_r2(predictions_filename, answers_filename):
    def read_target_from_vw(vw_record):
        return float(vw_record.split(' ')[0])
    
    with open(predictions_filename, 'r') as f:
        y_pred = np.array([float(value) for value in f.readlines()])
        
    with open(answers_filename, 'r') as f:
        y_expected = np.array([read_target_from_vw(value) for value in f.readlines()])
        
    return r2_score(y_expected, y_pred)

In [51]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.18962522751793354

Качество пока не поражает воображение

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_1.png" width="300">

Основная причина - по умолчанию vw запускает всего одну эпоху с дефолтными параметрами. Этого явно недостаточно, чтобы выбить хорошее качество. Попробуем улучить качество, используя различные опции этого инструмента

In [52]:
! ls -lh drugs.train.vw

-rw-r--r-- 1 ubuntu ubuntu 123M Feb 24 14:30 drugs.train.vw

In [53]:
!

#### Эпохи, размер хеша, лернинг рейт

Начнем тюнить нашу модель. Добавим больше эпох, увеличим размер хеша и подтянем лернинг рейт.

In [54]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 15.0 \
    --bit_precision 22 \
    --passes 100 \
    --cache -k

final_regressor = drugs.model.bin
Num weight bits = 22
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       30
256.536003 224.072006            2            2.0   1.0000  15.9690      145
328.243542 399.951080            4            4.0   7.0000  28.0000      157
1008.053105 1687.862669            8            8.0  24.0000  23.4970       73
3901.271561 6794.490017           16           16.0 224.0000   8.1367       38
2635.549805 1369.828049           32           32.0  25.0000  81.1440      147
2575.012004 2514.474203           64           64.0  13.0000  29.9650       77
1855.448868 1135.885732          128          128.0   6.0000   1.7608       80
1575.086902 1294.724937          256          256.0   8.0000  25.1003       64
1628.369504 1681.652105          512          512.0   2.0000   6.5046       27
1355.402863 1082.436222         1024         1024.0  36.0000   3.3847       27
1184.185076 1012.967290         2048         2048.0   5.0000  23.5813        8
1127.176478 1070.167880         4096         4096.0  16.0000  23.8669      149
1176.364854 1225.553229         8192         8192.0   8.0000   0.0000      146
1083.200157 990.035461        16384        16384.0   3.0000  13.1330       25
1008.678620 934.157082        32768        32768.0   4.0000  31.9330       12
976.008733 943.338846        65536        65536.0  11.0000  16.3297      138
908.013027 840.017321       131072       131072.0  23.0000  21.9266       88
844.629321 844.629321       262144       262144.0  17.0000  16.1106       13 h
807.831009 771.032696       524288       524288.0  37.0000  77.3631      148 h
770.267461 732.704559      1048576      1048576.0   7.0000  15.0727       14 h
737.081745 703.896029      2097152      2097152.0   0.0000   6.6464       25 h
705.920126 674.758641      4194304      4194304.0  72.0000  31.5927       58 h
677.795255 649.670444      8388608      8388608.0  51.0000  50.2163       45 h
652.966610 628.137991     16777216     16777216.0  14.0000  13.6160       55 h

finished run
number of examples per pass = 230973
passes used = 100
weighted example sum = 23097300.000000
weighted label sum = 647466600.000000
average loss = 611.576416 h
best constant = 28.032135
total feature number = 2136909500
CPU times: user 1.02 s, sys: 223 ms, total: 1.25 s
Wall time: 50.4 s

In [55]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

only testing
predictions = drugs.preductions.txt
Num weight bits = 22
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000       74
544.334290 1052.668579            2            2.0  76.0000  43.5551       10
372.843262 201.352234            4            4.0   4.0000   0.0000       68
544.368635 715.894009            8            8.0  23.0000  48.4719       44
493.378039 442.387444           16           16.0   7.0000  21.1832      126
373.361964 253.345888           32           32.0  13.0000  21.3520       47
464.793796 556.225629           64           64.0   3.0000  10.0905      108
479.414651 494.035505          128          128.0   9.0000  41.7097      115
407.755910 336.097168          256          256.0  29.0000  16.1786       60
609.451772 811.147634          512          512.0   5.0000   0.1304       33
1267.123649 1924.795526         1024         1024.0   9.0000   2.0223       96
925.106382 583.089114         2048         2048.0   7.0000  13.9168      104
823.019976 720.933570         4096         4096.0   5.0000   0.0000      133
693.240626 563.461276         8192         8192.0  12.0000   0.0000       59
781.106395 868.972164        16384        16384.0   2.0000   0.0000      102
714.572880 648.039364        32768        32768.0  65.0000  72.5684      129

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 705.123170
best constant = 28.272305
total feature number = 5932516

In [56]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.510615966968609

Так уже гораздо интереснее!

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_2.png" width="300">

#### Регуляризация

Можно попробовать добавить регуляризацию, однако нужно быть очень аккуратным с ней - она расчитывается для **каждого** объекта и поэтому ее нужно выставлять очень маленькой, чтобы модель не скатилась в 0.

In [57]:
%%time
# Попробуем использовать 0.00001 для L2, но скорее всего это будет очень много

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 15.0 \
    --bit_precision 22 \
    --passes 20 \
    --l2 0.00001 \
    --cache -k

using l2 regularization = 1e-05
final_regressor = drugs.model.bin
Num weight bits = 22
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       30
256.536034 224.072067            2            2.0   1.0000  15.9690      145
328.245617 399.955200            4            4.0   7.0000  28.0000      157
1008.064921 1687.884224            8            8.0  24.0000  23.4958       73
3901.193176 6794.321432           16           16.0 224.0000   8.1362       38
2635.421075 1369.648973           32           32.0  25.0000  81.1145      147
2574.827465 2514.233856           64           64.0  13.0000  29.9484       77
1854.434202 1134.040939          128          128.0   6.0000   1.8763       80
1574.579564 1294.724925          256          256.0   8.0000  25.0383       64
1628.570408 1682.561253          512          512.0   2.0000   6.4972       27
1354.914281 1081.258153         1024         1024.0  36.0000   3.5571       27
1182.028310 1009.142340         2048         2048.0   5.0000  21.3117        8
1120.741384 1059.454457         4096         4096.0  16.0000  23.2163      149
1170.857630 1220.973877         8192         8192.0   8.0000   0.0000      146
1097.302662 1023.747693        16384        16384.0   3.0000  13.9877       25
1069.951524 1042.600385        32768        32768.0   4.0000  17.9258       12
1103.290979 1136.630434        65536        65536.0  11.0000  34.2014      138
1115.105353 1126.919727       131072       131072.0  23.0000  19.4242       88
1140.953556 1140.953556       262144       262144.0  17.0000   5.3568       13 h
1182.661881 1224.370205       524288       524288.0  37.0000  33.8497      148 h

finished run
number of examples per pass = 230973
passes used = 4
weighted example sum = 923892.000000
weighted label sum = 25898664.000000
average loss = 1149.091797 h
best constant = 28.032133
total feature number = 85476380
CPU times: user 65.4 ms, sys: 34.2 ms, total: 99.7 ms
Wall time: 3.42 s

In [58]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

only testing
predictions = drugs.preductions.txt
Num weight bits = 22
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
5.711040 5.711040            1            1.0   6.0000   3.6102       74
2302.700979 4599.690918            2            2.0  76.0000   8.1790       10
1197.536105 92.371231            4            4.0   4.0000   3.3018       68
946.584093 695.632082            8            8.0  23.0000  14.1478       44
508.381847 70.179600           16           16.0   7.0000  21.2303      126
559.358821 610.335794           32           32.0  13.0000  13.8739       47
645.041917 730.725014           64           64.0   3.0000  10.0210      108
1205.428500 1765.815082          128          128.0   9.0000  22.5388      115
1161.321458 1117.214417          256          256.0  29.0000  13.5862       60
1635.143056 2108.964654          512          512.0   5.0000   7.9889       33
2808.249166 3981.355276         1024         1024.0   9.0000  19.4100       96
2015.631242 1223.013318         2048         2048.0   7.0000   8.4586      104
1654.816349 1294.001456         4096         4096.0   5.0000   4.2887      133
1372.543725 1090.271101         8192         8192.0  12.0000  14.3118       59
1431.269908 1489.996091        16384        16384.0   2.0000  13.2178      102
1341.083557 1250.897206        32768        32768.0  65.0000  46.5719      129

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 1309.473645
best constant = 28.272305
total feature number = 5932516

In [59]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.0911722662960851

In [117]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 15.0 \
    --bit_precision 22 \
    --passes 100 \
    --cache -k

final_regressor = drugs.model.bin
Num weight bits = 22
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       30
256.536003 224.072006            2            2.0   1.0000  15.9690      145
328.243542 399.951080            4            4.0   7.0000  28.0000      157
1008.053105 1687.862669            8            8.0  24.0000  23.4970       73
3901.271561 6794.490017           16           16.0 224.0000   8.1367       38
2635.549805 1369.828049           32           32.0  25.0000  81.1440      147
2575.012004 2514.474203           64           64.0  13.0000  29.9650       77
1855.448868 1135.885732          128          128.0   6.0000   1.7608       80
1575.086902 1294.724937          256          256.0   8.0000  25.1003       64
1628.369504 1681.652105          512          512.0   2.0000   6.5046       27
1355.402863 1082.436222         1024         1024.0  36.0000   3.3847       27
1184.185076 1012.967290         2048         2048.0   5.0000  23.5813        8
1127.176478 1070.167880         4096         4096.0  16.0000  23.8669      149
1176.364854 1225.553229         8192         8192.0   8.0000   0.0000      146
1083.200157 990.035461        16384        16384.0   3.0000  13.1330       25
1008.678620 934.157082        32768        32768.0   4.0000  31.9330       12
976.008733 943.338846        65536        65536.0  11.0000  16.3297      138
908.013027 840.017321       131072       131072.0  23.0000  21.9266       88
844.629321 844.629321       262144       262144.0  17.0000  16.1106       13 h
807.831009 771.032696       524288       524288.0  37.0000  77.3631      148 h
770.267461 732.704559      1048576      1048576.0   7.0000  15.0727       14 h
737.081745 703.896029      2097152      2097152.0   0.0000   6.6464       25 h
705.920126 674.758641      4194304      4194304.0  72.0000  31.5927       58 h

finished run
number of examples per pass = 230973
passes used = 20
weighted example sum = 4619460.000000
weighted label sum = 129493320.000000
average loss = 660.593567 h
best constant = 28.032133
total feature number = 427381900
CPU times: user 210 ms, sys: 45.4 ms, total: 256 ms
Wall time: 10.1 s

In [118]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

only testing
predictions = drugs.preductions.txt
Num weight bits = 22
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000       74
663.856689 1291.713379            2            2.0  76.0000  40.0596       10
419.834221 175.811752            4            4.0   4.0000   0.0000       68
627.090374 834.346527            8            8.0  23.0000  48.1149       44
507.308460 387.526547           16           16.0   7.0000  25.1145      126
409.221345 311.134229           32           32.0  13.0000  19.5480       47
501.073717 592.926089           64           64.0   3.0000   7.7352      108
567.331315 633.588913          128          128.0   9.0000  33.9953      115
472.671125 378.010935          256          256.0  29.0000  20.7042       60
733.460116 994.249107          512          512.0   5.0000   1.8280       33
1610.544786 2487.629457         1024         1024.0   9.0000  13.5174       96
1116.956317 623.367848         2048         2048.0   7.0000  12.4998      104
942.624485 768.292653         4096         4096.0   5.0000   0.0000      133
771.782137 600.939788         8192         8192.0  12.0000   1.7880       59
847.632038 923.481939        16384        16384.0   2.0000   0.0000      102
770.589153 693.546267        32768        32768.0  65.0000  70.0541      129

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 758.093769
best constant = 28.272305
total feature number = 5932516

In [119]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')  # Все еще хуже

0.4738522304061916

Все еще хуже чем без регуляризации 

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_2.5.png" width="300">

Таким образом выставлять L* регуляризацию - это отдельное исскуство в VW. Можно попробовать выставлять сильно меньшее значение. Однако на моей практике очень редко получается руками подобрать хороший коэффициент - это возможно только если искать автоподбором. 

Так что совет - настраивайте L* регуляризации уже после настройки всех остальных параметров. Или вообще не используйте, VW имеет тенденцию неплохо обучаться и без нее.

#### Комбинируем признаки

Мы можем попробовать комбинировать (перемножать) признаки между собой, чтобы получать лучшее качество. Итоговое количество признаков сильно возрастет (если у нас есть признак с N значениями и с M значениями, то их перемножение даст еще N\*M признаков. Но нас это не смущает, так как у нас есть хешинг-трик! Можем себе позволить спокойно увеличивать количество признаков, не сильно переживая.

В нашем случае логично перемножить препараты и заболевания - признак препарат-заболевание звучит достаточно логично.

In [ ]:
template = "{target} |d {drug_name} |c {condition} |r {review} |s rating:{rating}"

In [ ]:
d r a g

In [63]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 15.0 \
    --bit_precision 22 \
    --passes 20 \
    --interactions dc \
    --cache -k

creating features for following interactions: dcr
final_regressor = drugs.model.bin
Num weight bits = 22
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       56
173.775717 58.551434            2            2.0   1.0000   8.6519      286
236.528136 299.280556            4            4.0   7.0000  21.0339      310
1136.053465 2035.578795            8            8.0  24.0000  16.3336      142
3776.561829 6417.070192           16           16.0 224.0000   8.1378       72
2527.440120 1278.318411           32           32.0  25.0000  68.1992      290
2505.646199 2483.852278           64           64.0  13.0000  36.5816      150
1726.187350 946.728500          128          128.0   6.0000  15.2583      156
1570.330419 1414.473487          256          256.0   8.0000  28.2349      124
1689.941745 1809.553072          512          512.0   2.0000   6.4234       50
1425.949008 1161.956271         1024         1024.0  36.0000   2.9053       50
1262.254934 1098.560859         2048         2048.0   5.0000  17.3022       12
1172.219328 1082.183722         4096         4096.0  16.0000   4.2650      294
1233.861944 1295.504559         8192         8192.0   8.0000   0.0000      288
1141.750931 1049.639918        16384        16384.0   3.0000  12.2528       46
1057.689497 973.628063        32768        32768.0   4.0000  35.2417       20
1002.287773 946.886049        65536        65536.0  11.0000   0.0000      272
887.204181 772.120589       131072       131072.0  23.0000  20.8798      172
729.833461 729.833461       262144       262144.0  17.0000  16.1484       22 h
598.370826 466.908190       524288       524288.0  37.0000  34.7173      292 h
488.057213 377.745495      1048576      1048576.0   7.0000  14.6533       24 h
409.288742 330.520270      2097152      2097152.0   0.0000   0.0000       46 h
360.916634 312.544734      4194304      4194304.0  72.0000  71.6191      112 h

finished run
number of examples per pass = 230973
passes used = 20
weighted example sum = 4619460.000000
weighted label sum = 129493320.000000
average loss = 309.984558 h
best constant = 28.032133
total feature number = 836285960
CPU times: user 1.15 s, sys: 204 ms, total: 1.35 s
Wall time: 59.6 s

In [64]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

creating features for following interactions: dcr
only testing
predictions = drugs.preductions.txt
Num weight bits = 22
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000      144
85.240517 134.481033            2            2.0  76.0000  64.4034       16
615.387020 1145.533524            4            4.0   4.0000   3.1986      132
1816.075496 3016.763971            8            8.0  23.0000  23.8609       84
950.735275 85.395054           16           16.0   7.0000   6.4168      248
561.618642 172.502009           32           32.0  13.0000  13.1827       90
515.536312 469.453983           64           64.0   3.0000  13.6076      212
456.415955 397.295597          128          128.0   9.0000   9.6287      226
298.751872 141.087788          256          256.0  29.0000  28.8574      116
372.962000 447.172128          512          512.0   5.0000   4.7718       62
369.966735 366.971471         1024         1024.0   9.0000   8.8572      188
309.212642 248.458549         2048         2048.0   7.0000   7.0147      204
357.402697 405.592751         4096         4096.0   5.0000   0.0000      262
318.769508 280.136320         8192         8192.0  12.0000  12.0915      114
353.717012 388.664516        16384        16384.0   2.0000   1.7843      200
332.393501 311.069990        32768        32768.0  65.0000  65.6577      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 360.368581
best constant = 28.272305
total feature number = 11608392

In [65]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.7498896088825375

Качество поднялось!

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_3.png" width="300">

Посчитаем количество признаков - 3431 + 884 + 49855 + 1 + 3431 \* 884 = **3 087 182**. Уже достаточно внушительное количество.

#### Используем N-граммы для текста

Можно попросить VW по определенному неймспейсу генерировать сразу N-граммы. Подход хорошо работает для текстов, так что мы можем попробовать использовать это для признака review.

Конечно этот еще сильнее взорвет количество признаков, но мы опять не сильно переживаем по этому поводу.

In [66]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 15.0 \
    --bit_precision 22 \
    --passes 20 \
    --ngram r2 \
    --cache -k

Generating 2-grams for r namespaces.
final_regressor = drugs.model.bin
Num weight bits = 22
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       55
173.416544 57.833088            2            2.0   1.0000   8.6048      285
234.932221 296.447899            4            4.0   7.0000  21.3651      309
1134.389025 2033.845829            8            8.0  24.0000  16.8272      141
3791.905764 6449.422503           16           16.0 224.0000   7.6771       71
2540.528538 1289.151311           32           32.0  25.0000  74.1889      289
2494.572742 2448.616947           64           64.0  13.0000  37.9520      149
1798.624631 1102.676520          128          128.0   6.0000  14.6850      155
1600.929980 1403.235330          256          256.0   8.0000  23.6014      123
1663.021671 1725.113361          512          512.0   2.0000   5.6924       49
1369.037644 1075.053618         1024         1024.0  36.0000   4.5349       49
1198.467888 1027.898132         2048         2048.0   5.0000  16.9478       11
1132.846353 1067.224817         4096         4096.0  16.0000  31.6621      293
1181.314936 1229.783519         8192         8192.0   8.0000   0.0000      287
1089.489915 997.664894        16384        16384.0   3.0000   8.5879       45
998.937282 908.384649        32768        32768.0   4.0000  29.4009       19
930.594702 862.252122        65536        65536.0  11.0000  12.2669      271
800.038658 669.482614       131072       131072.0  23.0000  22.5039      171
648.947532 648.947532       262144       262144.0  17.0000  18.5435       21 h
520.388710 391.829888       524288       524288.0  37.0000  46.5877      291 h
403.255813 286.124926      1048576      1048576.0   7.0000  20.4463       23 h
313.587890 223.919967      2097152      2097152.0   0.0000   2.6224       45 h
253.429638 193.271645      4194304      4194304.0  72.0000  69.8852      111 h

finished run
number of examples per pass = 230973
passes used = 20
weighted example sum = 4619460.000000
weighted label sum = 129493320.000000
average loss = 184.529190 h
best constant = 28.032133
total feature number = 831666580
CPU times: user 819 ms, sys: 142 ms, total: 960 ms
Wall time: 40.8 s

In [67]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

Generating 2-grams for r namespaces.
only testing
predictions = drugs.preductions.txt
Num weight bits = 22
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000      143
92.785980 149.571960            2            2.0  76.0000  63.7700       15
46.472919 0.159858            4            4.0   4.0000   3.7340      131
726.686506 1406.900093            8            8.0  23.0000  24.3720       83
467.138790 207.591073           16           16.0   7.0000   7.5358      247
583.989696 700.840603           32           32.0  13.0000  13.3271       89
293.150106 2.310516           64           64.0   3.0000   2.9172      211
240.087881 187.025655          128          128.0   9.0000  11.1393      225
197.618541 155.149201          256          256.0  29.0000  29.3629      115
201.476881 205.335222          512          512.0   5.0000   3.6453       61
213.109645 224.742409         1024         1024.0   9.0000   8.6000      187
213.260795 213.411945         2048         2048.0   7.0000   5.6910      203
200.194561 187.128327         4096         4096.0   5.0000   5.1133      261
195.788509 191.382457         8192         8192.0  12.0000  10.7383      113
218.729164 241.669819        16384        16384.0   2.0000   1.7680      199
200.421219 182.113273        32768        32768.0  65.0000  66.4408      253

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 198.961471
best constant = 28.272305
total feature number = 11544232

In [68]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.8619126818394689

Юху! Вот это уже реально похоже на какую-то модель, которую не стыдно и на продакшн катить!

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_4.png" width="300">

Количество признаков уже подобралось к отметке 3431 + 884 + 49855 + 1 + 49855 ^ 2 = **2 485 575 203**

#### Используем все вместе!

In [69]:
%%time

! vw --final_regressor drugs.model.bin drugs.train.vw \
    --learning_rate 20.0 \
    --bit_precision 23 \
    --passes 40 \
    --ngram r2 \
    --interactions dc \
    --cache -k

Generating 2-grams for r namespaces.
creating features for following interactions: dc
final_regressor = drugs.model.bin
Num weight bits = 23
learning rate = 20
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.train.vw.cache
Reading datafile = drugs.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
289.000000 289.000000            1            1.0  17.0000   0.0000       56
172.327087 55.654175            2            2.0   1.0000   8.4602      286
234.736885 297.146683            4            4.0   7.0000  21.2516      310
1134.530071 2034.323258            8            8.0  24.0000  17.2988      142
3821.997198 6509.464324           16           16.0 224.0000   7.8433       72
2605.829915 1389.662631           32           32.0  25.0000  82.3097      290
2535.426779 2465.023644           64           64.0  13.0000  39.4484      150
1853.672747 1171.918714          128          128.0   6.0000  15.5830      156
1641.572197 1429.471647          256          256.0   8.0000  24.9067      124
1691.768454 1741.964711          512          512.0   2.0000   6.2751       50
1383.541058 1075.313662         1024         1024.0  36.0000   4.7206       50
1211.676608 1039.812158         2048         2048.0   5.0000  18.2781       12
1146.054335 1080.432063         4096         4096.0  16.0000  29.8406      294
1193.189726 1240.325117         8192         8192.0   8.0000   0.0000      288
1095.244129 997.298532        16384        16384.0   3.0000   7.3953       46
998.000213 900.756296        32768        32768.0   4.0000  29.2003       20
922.575071 847.149930        65536        65536.0  11.0000   8.8569      272
780.502838 638.430604       131072       131072.0  23.0000  24.4275      172
615.977142 615.977142       262144       262144.0  17.0000  20.1388       22 h
478.110864 340.244586       524288       524288.0  37.0000  43.7173      292 h
360.911987 243.715121      1048576      1048576.0   7.0000  20.5183       24 h
278.320655 195.729324      2097152      2097152.0   0.0000   2.2544       46 h
227.661465 177.002493      4194304      4194304.0  72.0000  70.6924      112 h

finished run
number of examples per pass = 230973
passes used = 27
weighted example sum = 6236271.000000
weighted label sum = 174815982.000000
average loss = 172.602631 h
best constant = 28.032133
total feature number = 1128986154
CPU times: user 1.11 s, sys: 258 ms, total: 1.37 s
Wall time: 58.8 s

In [70]:
! vw --testonly --initial_regressor drugs.model.bin --predictions drugs.preductions.txt drugs.test.vw

Generating 2-grams for r namespaces.
creating features for following interactions: dc
only testing
predictions = drugs.preductions.txt
Num weight bits = 23
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
36.000000 36.000000            1            1.0   6.0000   0.0000      144
44.216021 52.432041            2            2.0  76.0000  68.7590       16
22.670023 1.124026            4            4.0   4.0000   3.6876      132
740.151412 1457.632801            8            8.0  23.0000  23.6109       84
453.024517 165.897623           16           16.0   7.0000   7.6341      248
663.569742 874.114967           32           32.0  13.0000  13.1812       90
332.543136 1.516530           64           64.0   3.0000   3.3430      212
275.126275 217.709414          128          128.0   9.0000  10.4234      226
206.997369 138.868464          256          256.0  29.0000  28.8114      116
203.198146 199.398923          512          512.0   5.0000   4.3028       62
195.547768 187.897389         1024         1024.0   9.0000   8.8795      188
202.295741 209.043714         2048         2048.0   7.0000   6.1844      204
189.892287 177.488833         4096         4096.0   5.0000   4.9263      262
187.510396 185.128506         8192         8192.0  12.0000  11.4418      114
194.120019 200.729642        16384        16384.0   2.0000   1.5956      200
182.357134 170.594250        32768        32768.0  65.0000  66.2649      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = 1813951.000000
average loss = 178.366314
best constant = 28.272305
total feature number = 11608392

In [71]:
calc_r2('drugs.preductions.txt', 'drugs.test.vw')

0.8762065549926664

Лучший результат!

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_5.png" width="300">

Количество признаков перевалило за  3431 + 884 + 49855 + 1 + 7 + 49855 ^ 2 + 3431 \* 884=  **2 488 608 207**.

### Классификация

Помимо обычный линейрой регрессии с MSE , Vowpal Wabbit умеер решать и задачи классификации. Для этого нужно поменять обучаемую loss function. Список всех поддерживаемых loss можно найти здесь - https://github.com/VowpalWabbit/vowpal_wabbit/wiki/Loss-functions .

Для начала переформатируем наш датасет для классификации - сделаем два класса - полезный и не полезный отзыв. Определять это будем по количеству usefullCount - если больше медианы, то полезный, если меньше - нет.

In [72]:
df['usefulCount'].median()

16.0

Важно отметить, что для бинарной классификации, классы должны быть 1 и -1.

In [73]:
def convert_to_vw_class(data):
    target = 1 if data['usefulCount'] > 16.0 else -1
    
    drug_name = data['drugName'].lower().replace(' ', '_')
    condition = data['condition'].lower().replace(' ', '_')
    
    raw_text = data['review'].lower()
    word_pattern = re.compile(r"[a-zA-Z0-9_]+")
    words = [match.group(0) for match in re.finditer(word_pattern, raw_text)]
    review = ' '.join(words)
    
    rating = data['rating']

    
    template = "{target} |d {drug_name} |c {condition} |r {review} |s rating:{rating}"
    return template.format(
        target=target,
        drug_name=drug_name,
        condition=condition,
        review=review,
        rating=rating
    )

In [74]:
_, example = next(df.iterrows())
example

Unnamed: 0                                                206461
drugName                                               Valsartan
condition                           Left Ventricular Dysfunction
review         "It has no side effect, I take it in combinati...
rating                                                       9.0
date                                                May 20, 2012
usefulCount                                                   27
Name: 0, dtype: object

In [75]:
convert_to_vw_class(example)

'1 |d valsartan |c left_ventricular_dysfunction |r it has no side effect i take it in combination of bystolic 5 mg and fish oil |s rating:9.0'

In [76]:
def write_vw_class(dataframe, filename):
    with open(filename, 'w') as f:
        for vw_record in dataframe.parallel_apply(convert_to_vw_class, axis=1):
            f.write(vw_record + '\n')

In [77]:
df_train, df_test = train_test_split(df, test_size=0.2, random_state=420)

In [78]:
%%time

write_vw_class(df_train, 'drugs.class.train.vw')
write_vw_class(df_test, 'drugs.class.test.vw')

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=128318), Label(value='0 / 128318')…

VBox(children=(HBox(children=(IntProgress(value=0, description='0.00%', max=32080), Label(value='0 / 32080')))…

CPU times: user 853 ms, sys: 993 ms, total: 1.85 s
Wall time: 10.1 s

In [79]:
! head -n 3 drugs.class.train.vw

1 |d anaprox-ds |c pain |r i recommend if for girls if they have menstrual pain it helps alot 10 15 mins after i take the pill i feel no more pain |s rating:10.0
-1 |d levetiracetam |c epilepsy |r as a 42 year old female i have had seizures my entire life i have taken 14 anti convulsants at one point or another in an attempt to control my complex partial seizures but keppra is the worst medication i have ever taken the side effects are horrible although it 039 s the only medication that has been able to stop my seizures the side effects are so terrible that it 039 s not worth taking it i couldn 039 t string together a coherent thought had short term memory loss had awful mood swings and suddenly hated life everything was difficult i couldn 039 t think straight and felt emotionally raw all the time i could barely keep it together while on this medication every day of life was awful while on this medication i will never take it again |s rating:1.0
1 |d contrave |c obesity |r i have been taking contrave for almost two months i am a 50 year old 5 039 2 quot woman that started out at 155 lbs since starting i have lost 11 lbs i had i think all the side effects a week of severe nauseousness no throwing up just wouldn 039 t eat anything without a stomach ache before i started contrave i drank up to six cans of pop a day and now do not even crave it i had headaches for about a week and constipation now almost two months in and i feel better i really feel this is a great diet pill i only have 9lbs to go to my goal weight |s rating:10.0

In [80]:
%%time

! vw --final_regressor drugs.model.bin drugs.class.train.vw \
    --loss_function logistic \
    --learning_rate 20.0 \
    --bit_precision 23 \
    --passes 40 \
    --ngram r2 \
    --interactions dc \
    --cache -k

Generating 2-grams for r namespaces.
creating features for following interactions: dc
final_regressor = drugs.model.bin
Num weight bits = 23
learning rate = 20
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.class.train.vw.cache
Reading datafile = drugs.class.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.693147 0.693147            1            1.0   1.0000   0.0000       56
1.784606 2.876064            2            2.0  -1.0000   2.8181      286
1.551441 1.318277            4            4.0  -1.0000   1.9425      310
1.280395 1.009348            8            8.0   1.0000  -0.1680      142
1.133821 0.987248           16           16.0   1.0000  -0.6707       72
0.933702 0.733582           32           32.0   1.0000   3.8839      290
0.904595 0.875489           64           64.0  -1.0000   1.0534      150
0.844466 0.784337          128          128.0  -1.0000  -1.4201      156
0.783167 0.721868          256          256.0  -1.0000  -2.9304      124
0.714368 0.645570          512          512.0  -1.0000   0.0605       50
0.735383 0.756397         1024         1024.0   1.0000  -1.1244       50
0.734593 0.733804         2048         2048.0  -1.0000   0.3237       12
0.712489 0.690385         4096         4096.0  -1.0000  -0.1398      294
0.712163 0.711838         8192         8192.0  -1.0000  -0.8617      288
0.692920 0.673677        16384        16384.0  -1.0000  -2.5164       46
0.661107 0.629294        32768        32768.0  -1.0000  -2.1521       20
0.599389 0.537671        65536        65536.0  -1.0000  -1.6124      272
0.497981 0.396572       131072       131072.0   1.0000   1.8294      172
0.344417 0.344417       262144       262144.0   1.0000   1.3034       22 h
0.238315 0.132214       524288       524288.0   1.0000   6.3202      292 h
0.184806 0.131297      1048576      1048576.0  -1.0000  -2.5690       24 h

finished run
number of examples per pass = 230973
passes used = 6
weighted example sum = 1385838.000000
weighted label sum = -13770.000000
average loss = 0.129419 h
best constant = -0.019873
best constant's loss = 0.693098
total feature number = 250885812
CPU times: user 223 ms, sys: 78.3 ms, total: 301 ms
Wall time: 11.6 s

In [81]:
%%time

! vw drugs.class.test.vw \
    --testonly \
    --initial_regressor drugs.model.bin \
    --predictions predictions.txt

Generating 2-grams for r namespaces.
creating features for following interactions: dc
only testing
predictions = predictions.txt
Num weight bits = 23
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.class.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
45.949364 45.949364            1            1.0  -1.0000  -7.7786      144
28.838305 11.727246            2            2.0   1.0000   4.4245       16
36.769369 44.700434            4            4.0  -1.0000  -9.0952      132
28.369600 19.969830            8            8.0   1.0000   4.4692       84
25.758292 23.146984           16           16.0  -1.0000  -7.3193      248
26.630841 27.503391           32           32.0  -1.0000  -4.5997       90
41.285366 55.939890           64           64.0  -1.0000  -6.0912      212
38.983493 36.681621          128          128.0  -1.0000  -5.7473      226
39.622673 40.261853          256          256.0   1.0000   7.4183      116
45.118072 50.613471          512          512.0  -1.0000  -4.9033       62
42.285941 39.453809         1024         1024.0  -1.0000  -6.1001      188
41.430310 40.574679         2048         2048.0  -1.0000 -12.0986      204
41.623416 41.816521         4096         4096.0  -1.0000 -11.0945      262
40.992919 40.362423         8192         8192.0  -1.0000  -4.8113      114
41.195842 41.398766        16384        16384.0  -1.0000  -9.4104      200
41.764152 42.332462        32768        32768.0   1.0000  11.0593      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = -640.000000
average loss = 41.883024
best constant = -0.009975
best constant's loss = 0.999901
total feature number = 11608392
CPU times: user 4.39 ms, sys: 28.4 ms, total: 32.8 ms
Wall time: 456 ms

По умолчанию vw считает только регрессию - то есть значение логита для логистической регресии

In [82]:
! head predictions.txt

-7.778596
4.424507
5.885537
-9.095208
6.093756
1.256716
-7.066693
4.469213
-4.044488
6.824972

Чтобы предсказывать сразу классы для бинарной классификации можно указать флаг `--binary`

In [83]:
%%time

! vw drugs.class.test.vw \
    --binary \
    --testonly \
    --initial_regressor drugs.model.bin \
    --predictions predictions.txt

Generating 2-grams for r namespaces.
creating features for following interactions: dc
only testing
predictions = predictions.txt
Num weight bits = 23
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.class.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.000000 0.000000            1            1.0  -1.0000  -1.0000      144
0.000000 0.000000            2            2.0   1.0000   1.0000       16
0.000000 0.000000            4            4.0  -1.0000  -1.0000      132
0.125000 0.250000            8            8.0   1.0000   1.0000       84
0.125000 0.125000           16           16.0  -1.0000  -1.0000      248
0.093750 0.062500           32           32.0  -1.0000  -1.0000       90
0.046875 0.000000           64           64.0  -1.0000  -1.0000      212
0.039062 0.031250          128          128.0  -1.0000  -1.0000      226
0.031250 0.023438          256          256.0   1.0000   1.0000      116
0.035156 0.039062          512          512.0  -1.0000  -1.0000       62
0.035156 0.035156         1024         1024.0  -1.0000  -1.0000      188
0.044434 0.053711         2048         2048.0  -1.0000  -1.0000      204
0.042236 0.040039         4096         4096.0  -1.0000  -1.0000      262
0.040894 0.039551         8192         8192.0  -1.0000  -1.0000      114
0.040222 0.039551        16384        16384.0  -1.0000  -1.0000      200
0.040588 0.040955        32768        32768.0   1.0000   1.0000      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = -640.000000
average loss = 0.039885
best constant = -0.009975
best constant's loss = 0.999901
total feature number = 11608392
CPU times: user 13.4 ms, sys: 15.3 ms, total: 28.8 ms
Wall time: 462 ms

In [84]:
! head predictions.txt

-1
1
1
-1
1
1
-1
1
-1
1

Чтобы предсказывать вероятности, то нужно указать vw что требуется пост-преобразование через `--link=logistic`

In [85]:
%%time

! vw drugs.class.test.vw \
    --link=logistic \
    --testonly \
    --initial_regressor drugs.model.bin \
    --predictions predictions.txt

Generating 2-grams for r namespaces.
creating features for following interactions: dc
only testing
predictions = predictions.txt
Num weight bits = 23
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.class.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
45.949364 45.949364            1            1.0  -1.0000   0.0004      144
28.838305 11.727246            2            2.0   1.0000   0.9882       16
36.769369 44.700434            4            4.0  -1.0000   0.0001      132
28.369600 19.969830            8            8.0   1.0000   0.9887       84
25.758292 23.146984           16           16.0  -1.0000   0.0007      248
26.630841 27.503391           32           32.0  -1.0000   0.0100       90
41.285366 55.939890           64           64.0  -1.0000   0.0023      212
38.983493 36.681621          128          128.0  -1.0000   0.0032      226
39.622673 40.261853          256          256.0   1.0000   0.9994      116
45.118072 50.613471          512          512.0  -1.0000   0.0074       62
42.285941 39.453809         1024         1024.0  -1.0000   0.0022      188
41.430310 40.574679         2048         2048.0  -1.0000   0.0000      204
41.623416 41.816521         4096         4096.0  -1.0000   0.0000      262
40.992919 40.362423         8192         8192.0  -1.0000   0.0081      114
41.195842 41.398766        16384        16384.0  -1.0000   0.0001      200
41.764152 42.332462        32768        32768.0   1.0000   1.0000      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = -640.000000
average loss = 41.883024
best constant = -0.009975
best constant's loss = 0.999901
total feature number = 11608392
CPU times: user 12 ms, sys: 13.2 ms, total: 25.1 ms
Wall time: 450 ms

In [86]:
! head predictions.txt

0.000418
0.988162
0.997228
0.000112
0.997748
0.778460
0.000852
0.988673
0.017217
0.998915

In [87]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score


def calc_class_metrics(predictions_filename, answers_filename):
    def read_target_from_vw(vw_record):
        return int((float(vw_record.split(' ')[0]) + 1) / 2)
    
    with open(predictions_filename, 'r') as f:
        y_pred = np.array([int(float(value) > 0.5) for value in f.readlines()])
        
    with open(answers_filename, 'r') as f:
        y_expected = np.array([read_target_from_vw(value) for value in f.readlines()])
        
    return accuracy_score(y_expected, y_pred), precision_score(y_expected, y_pred), recall_score(y_expected, y_pred)

In [88]:
calc_class_metrics('predictions.txt', 'drugs.class.test.vw')

(0.9601153366583541, 0.9561658387227794, 0.9636020151133501)

In [89]:
%%time

! vw --final_regressor drugs.model.bin drugs.class.train.vw \
    --loss_function logistic \
    --nn 3 \
    --inpass \
    --learning_rate 15.0 \
    --bit_precision 23 \
    --passes 50 \
    --ngram r2 \
    --interactions dc \
    --cache -k

Generating 2-grams for r namespaces.
creating features for following interactions: dc
final_regressor = drugs.model.bin
using input passthrough for neural network training
Num weight bits = 23
learning rate = 15
initial_t = 0
power_t = 0.5
decay_learning_rate = 1
creating cache_file = drugs.class.train.vw.cache
Reading datafile = drugs.class.train.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
0.693147 0.693147            1            1.0   1.0000   0.0000       56
1.941622 3.190097            2            2.0  -1.0000   3.1481      286
1.622740 1.303857            4            4.0  -1.0000   1.9788      310
1.305374 0.988007            8            8.0   1.0000  -0.0849      142
1.136837 0.968300           16           16.0   1.0000  -0.6021       72
0.934221 0.731605           32           32.0   1.0000   3.6791      290
0.903716 0.873211           64           64.0  -1.0000   0.9956      150
0.842906 0.782096          128          128.0  -1.0000  -1.3598      156
0.778342 0.713779          256          256.0  -1.0000  -2.7776      124
0.706528 0.634714          512          512.0  -1.0000   0.0943       50
0.723758 0.740988         1024         1024.0   1.0000  -1.0745       50
0.720434 0.717110         2048         2048.0  -1.0000   0.3221       12
0.698014 0.675594         4096         4096.0  -1.0000   0.0030      294
0.695959 0.693903         8192         8192.0  -1.0000  -0.9562      288
0.676331 0.656704        16384        16384.0  -1.0000  -2.4915       46
0.645395 0.614458        32768        32768.0  -1.0000  -1.7317       20
0.585693 0.525990        65536        65536.0  -1.0000  -0.7817      272
0.488113 0.390534       131072       131072.0   1.0000   1.0655      172
0.343543 0.343543       262144       262144.0   1.0000   1.3486       22 h
0.242145 0.140747       524288       524288.0   1.0000   5.8654      292 h
0.189317 0.136489      1048576      1048576.0  -1.0000  -2.4940       24 h

finished run
number of examples per pass = 230973
passes used = 6
weighted example sum = 1385838.000000
weighted label sum = -13770.000000
average loss = 0.135922 h
best constant = -0.019873
best constant's loss = 0.693098
total feature number = 250885812
CPU times: user 688 ms, sys: 120 ms, total: 807 ms
Wall time: 34.5 s

In [90]:
! vw --help

Num weight bits = 18
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile =
num sources = 1
driver:
  --onethread           Disable parse thread
VW options:
  --ring_size arg (=256, ) size of example ring
  --strict_parse           throw on malformed examples
Update options:
  -l [ --learning_rate ] arg Set learning rate
  --power_t arg              t power value
  --decay_learning_rate arg  Set Decay factor for learning_rate between passes
  --initial_t arg            initial t value
  --feature_mask arg         Use existing regressor to determine which
                             parameters may be updated.  If no
                             initial_regressor given, also used for initial
                             weights.
Weight options:
  -i [ --initial_regressor ] arg  Initial regressor(s)
  --initial_weight arg            Set all weights to an initial value of arg.
  --random_weights                make initial weights random
  --normal_weights                make initial weights normal
  --truncated_normal_weights      make initial weights truncated normal
  --sparse_weights                Use a sparse datastructure for weights
  --input_feature_regularizer arg Per feature regularization input file
Parallelization options:
  --span_server arg                 Location of server for setting up spanning
                                    tree
  --unique_id arg (=0, )            unique id used for cluster parallel jobs
  --total arg (=1, )                total number of nodes used in cluster
                                    parallel job
  --node arg (=0, )                 node number in cluster parallel job
  --span_server_port arg (=26543, ) Port of the server for setting up spanning
                                    tree
Diagnostic options:
  --version             Version information
  -a [ --audit ]        print weights of features
  -P [ --progress ] arg Progress update frequency. int: additive, float:
                        multiplicative
  --quiet               Don't output disgnostics and progress updates
  -h [ --help ]         Look here: http://hunch.net/~vw/ and click on Tutorial.
Randomization options:
  --random_seed arg     seed random number generator
Feature options:
  --hash arg                      how to hash the features. Available options:
                                  strings, all
  --hash_seed arg (=0, )          seed for hash function
  --ignore arg                    ignore namespaces beginning with character
                                  <arg>
  --ignore_linear arg             ignore namespaces beginning with character
                                  <arg> for linear terms only
  --keep arg                      keep namespaces beginning with character
                                  <arg>
  --redefine arg                  redefine namespaces beginning with characters
                                  of string S as namespace N. <arg> shall be in
                                  form 'N:=S' where := is operator. Empty N or
                                  S are treated as default namespace. Use ':'
                                  as a wildcard in S.
  -b [ --bit_precision ] arg      number of bits in the feature table
  --noconstant                    Don't add a constant feature
  -C [ --constant ] arg           Set initial value of constant
  --ngram arg                     Generate N grams. To generate N grams for a
                                  single namespace 'foo', arg should be fN.
  --skips arg                     Generate skips in N grams. This in
                                  conjunction with the ngram tag can be used to
                                  generate generalized n-skip-k-gram. To
                                  generate n-skips for a single namespace
                                  'foo', arg should be fN.
  --feature_limit arg             limit to N features. To apply to a single
                                  namespace 'foo', arg should be fN
  --affix arg                     generate prefixes/suffixes of features;
                                  argument '+2a,-3b,+1' means generate 2-char
                                  prefixes for namespace a, 3-char suffixes for
                                  b and 1 char prefixes for default namespace
  --spelling arg                  compute spelling features for a give
                                  namespace (use '_' for default namespace)
  --dictionary arg                read a dictionary for additional features
                                  (arg either 'x:file' or just 'file')
  --dictionary_path arg           look in this directory for dictionaries;
                                  defaults to current directory or env{PATH}
  --interactions arg              Create feature interactions of any level
                                  between namespaces.
  --permutations                  Use permutations instead of combinations for
                                  feature interactions of same namespace.
  --leave_duplicate_interactions  Don't remove interactions with duplicate
                                  combinations of namespaces. For ex. this is a
                                  duplicate: '-q ab -q ba' and a lot more in
                                  '-q ::'.
  -q [ --quadratic ] arg          Create and use quadratic features
  --q: arg                        : corresponds to a wildcard for all printable
                                  characters
  --cubic arg                     Create and use cubic features
Example options:
  -t [ --testonly ]                Ignore label information and just test
  --holdout_off                    no holdout data in multiple passes
  --holdout_period arg (=10, )     holdout period for test only
  --holdout_after arg              holdout after n training examples, default
                                   off (disables holdout_period)
  --early_terminate arg (=3, )     Specify the number of passes tolerated when
                                   holdout loss doesn't decrease before early
                                   termination
  --passes arg                     Number of Training Passes
  --initial_pass_length arg        initial number of examples per pass
  --examples arg                   number of examples to parse
  --min_prediction arg             Smallest prediction to output
  --max_prediction arg             Largest prediction to output
  --sort_features                  turn this on to disregard order in which
                                   features have been defined. This will lead
                                   to smaller cache sizes
  --loss_function arg (=squared, ) Specify the loss function to be used, uses
                                   squared by default. Currently available ones
                                   are squared, classic, hinge, logistic,
                                   quantile and poisson.
  --quantile_tau arg (=0.5, )      Parameter \tau associated with Quantile
                                   loss. Defaults to 0.5
  --l1 arg                         l_1 lambda
  --l2 arg                         l_2 lambda
  --no_bias_regularization         no bias in regularization
  --named_labels arg               use names for labels (multiclass, etc.)
                                   rather than integers, argument specified all
                                   possible labels, comma-sep, eg
                                   "--named_labels Noun,Verb,Adj,Punc"
Output model:
  -f [ --final_regressor ] arg          Final regressor
  --readable_model arg                  Output human-readable final regressor
                                        with numeric features
  --invert_hash arg                     Output human-readable final regressor
                                        with feature names.  Computationally
                                        expensive.
  --save_resume                         save extra state so learning can be
                                        resumed later with new data
  --preserve_performance_counters       reset performance counters when
                                        warmstarting
  --save_per_pass                       Save the model after every pass over
                                        data
  --output_feature_regularizer_binary arg
                                        Per feature regularization output file
  --output_feature_regularizer_text arg Per feature regularization output file,
                                        in text
  --id arg                              User supplied ID embedded into the
                                        final regressor
Output options:
  -p [ --predictions ] arg     File to output predictions to
  -r [ --raw_predictions ] arg File to output unnormalized predictions to
Audit Regressor:
  --audit_regressor arg stores feature names and their regressor values. Same
                        dataset must be used for both regressor training and
                        this mode.
Search options:
  --search arg                          Use learning to search,
                                        argument=maximum action id or 0 for LDF
  --search_task arg                     the search task (use "--search_task
                                        list" to get a list of available tasks)
  --search_metatask arg                 the search metatask (use
                                        "--search_metatask list" to get a list
                                        of available metatasks)
  --search_interpolation arg            at what level should interpolation
                                        happen? [*data|policy]
  --search_rollout arg                  how should rollouts be executed?
                                            [policy|oracle|*mix_per_state|mix_p
                                        er_roll|none]
  --search_rollin arg                   how should past trajectories be
                                        generated? [policy|oracle|*mix_per_stat
                                        e|mix_per_roll]
  --search_passes_per_policy arg (=1, ) number of passes per policy (only valid
                                        for search_interpolation=policy)
  --search_beta arg (=0.5, )            interpolation rate for policies (only
                                        valid for search_interpolation=policy)
  --search_alpha arg (=1e-10, )         annealed beta = 1-(1-alpha)^t (only
                                        valid for search_interpolation=data)
  --search_total_nb_policies arg        if we are going to train the policies
                                        through multiple separate calls to vw,
                                        we need to specify this parameter and
                                        tell vw how many policies are
                                        eventually going to be trained
  --search_trained_nb_policies arg      the number of trained policies in a
                                        file
  --search_allowed_transitions arg      read file of allowed transitions [def:
                                        all transitions are allowed]
  --search_subsample_time arg           instead of training at all timesteps,
                                        use a subset. if value in (0,1), train
                                        on a random v%. if v>=1, train on
                                        precisely v steps per example, if
                                        v<=-1, use active learning
  --search_neighbor_features arg        copy features from neighboring lines.
                                        argument looks like: '-1:a,+2' meaning
                                        copy previous line namespace a and next
                                        next line from namespace _unnamed_,
                                        where ',' separates them
  --search_rollout_num_steps arg        how many calls of "loss" before we stop
                                        really predicting on rollouts and
                                        switch to oracle (default means
                                        "infinite")
  --search_history_length arg (=1, )    some tasks allow you to specify how
                                        much history their depend on; specify
                                        that here
  --search_no_caching                   turn off the built-in caching ability
                                        (makes things slower, but technically
                                        more safe)
  --search_xv                           train two separate policies,
                                        alternating prediction/learning
  --search_perturb_oracle arg (=0, )    perturb the oracle on rollin with this
                                        probability
  --search_linear_ordering              insist on generating examples in linear
                                        order (def: hoopla permutation)
  --search_active_verify arg            verify that active learning is doing
                                        the right thing (arg = multiplier,
                                        should be = cost_range * range_c)
  --search_save_every_k_runs arg        save model every k runs
Experience Replay:
  --replay_c arg              use experience replay at a specified level
                              [b=classification/regression, m=multiclass,
                              c=cost sensitive] with specified buffer size
  --replay_c_count arg (=1, ) how many times (in expectation) should each
                              example be played (default: 1 = permuting)
Explore evaluation:
  --explore_eval        Evaluate explore_eval adf policies
  --multiplier arg      Multiplier used to make all rejection sample
                        probabilities <= 1
Make csoaa_ldf into Contextual Bandit:
  --cbify_ldf           Convert csoaa_ldf into a contextual bandit problem
  --loss0 arg (=0, )    loss for correct label
  --loss1 arg (=1, )    loss for incorrect label
Make Multiclass into Contextual Bandit:
  --cbify arg           Convert multiclass on <k> classes into a contextual
                        bandit problem
  --cbify_cs            consume cost-sensitive classification examples instead
                        of multiclass
  --loss0 arg (=0, )    loss for correct label
  --loss1 arg (=1, )    loss for incorrect label
Make Multiclass into Warm-starting Contextual Bandit:
  --warm_cb arg                        Convert multiclass on <k> classes into a
                                       contextual bandit problem
  --warm_cb_cs                         consume cost-sensitive classification
                                       examples instead of multiclass
  --loss0 arg (=0, )                   loss for correct label
  --loss1 arg (=1, )                   loss for incorrect label
  --warm_start arg (=0, )              number of training examples for warm
                                       start phase
  --epsilon arg                        epsilon-greedy exploration
  --interaction arg (=4294967295, )    number of examples for the interactive
                                       contextual bandit learning phase
  --warm_start_update                  indicator of warm start updates
  --interaction_update                 indicator of interaction updates
  --corrupt_type_warm_start arg (=1, ) type of label corruption in the warm
                                       start phase (1: uniformly at random, 2:
                                       circular, 3: replacing with overwriting
                                       label)
  --corrupt_prob_warm_start arg (=0, ) probability of label corruption in the
                                       warm start phase
  --choices_lambda arg (=1, )          the number of candidate lambdas to
                                       aggregate (lambda is the importance
                                       weight parameter between the two
                                       sources)
  --lambda_scheme arg (=1, )           The scheme for generating candidate
                                       lambda set (1: center lambda=0.5, 2:
                                       center lambda=0.5, min lambda=0, max
                                       lambda=1, 3: center lambda=epsilon/(1+ep
                                       silon), 4: center lambda=epsilon/(1+epsi
                                       lon), min lambda=0, max lambda=1); the
                                       rest of candidate lambda values are
                                       generated using a doubling scheme
  --overwrite_label arg (=1, )         the label used by type 3 corruptions
                                       (overwriting)
  --sim_bandit                         simulate contextual bandit updates on
                                       warm start examples
Contextual Bandit Exploration with Action Dependent Features:
  --cb_explore_adf          Online explore-exploit for a contextual bandit
                            problem with multiline action dependent features
  --first arg               tau-first exploration
  --epsilon arg             epsilon-greedy exploration
  --bag arg                 bagging-based exploration
  --cover arg               Online cover based exploration
  --psi arg (=1, )          disagreement parameter for cover
  --nounif                  do not explore uniformly on zero-probability
                            actions in cover
  --softmax                 softmax exploration
  --regcb                   RegCB-elim exploration
  --regcbopt                RegCB optimistic exploration
  --mellowness arg (=0.1, ) RegCB mellowness parameter c_0. Default 0.1
  --greedify                always update first policy once in bagging
  --cb_min_cost arg (=0, )  lower bound on cost
  --cb_max_cost arg (=1, )  upper bound on cost
  --first_only              Only explore the first action in a tie-breaking
                            event
  --lambda arg (=1, )       parameter for softmax
  --cb_type arg             contextual bandit method to use in {ips,dr,mtr}.
                            Default: mtr
Contextual Bandit Exploration:
  --cb_explore arg        Online explore-exploit for a <k> action contextual
                          bandit problem
  --first arg             tau-first exploration
  --epsilon arg (=0.05, ) epsilon-greedy exploration
  --bag arg               bagging-based exploration
  --cover arg             Online cover based exploration
  --psi arg (=1, )        disagreement parameter for cover
Multiworld Testing Options:
  --multiworld_test arg Evaluate features as a policies
  --learn arg           Do Contextual Bandit learning on <n> classes.
  --exclude_eval        Discard mwt policy features before learning
Contextual Bandit with Action Dependent Features:
  --cb_adf              Do Contextual Bandit learning with multiline action
                        dependent features.
  --rank_all            Return actions sorted by score order
  --no_predict          Do not do a prediction when training
  --cb_type arg         contextual bandit method to use in {ips, dm, dr, mtr,
                        sm}. Default: mtr
Contextual Bandit Options:
  --cb arg              Use contextual bandit learning with <k> costs
  --cb_type arg         contextual bandit method to use in {ips,dm,dr}
  --eval                Evaluate a policy rather than optimizing.
Cost Sensitive One Against All with Label Dependent Features:
  --csoaa_ldf arg       Use one-against-all multiclass learning with label
                        dependent features.
  --ldf_override arg    Override singleline or multiline from csoaa_ldf or

In [91]:
%%time

! vw drugs.class.test.vw \
    --link=logistic \
    --testonly \
    --initial_regressor drugs.model.bin \
    --predictions predictions.txt

Generating 2-grams for r namespaces.
creating features for following interactions: dc
only testing
predictions = predictions.txt
using input passthrough for neural network testing
Num weight bits = 23
learning rate = 0.5
initial_t = 0
power_t = 0.5
using no cache
Reading datafile = drugs.class.test.vw
num sources = 1
average  since         example        example  current  current  current
loss     last          counter         weight    label  predict features
50.758190 50.758190            1            1.0  -1.0000   0.0003      144
30.176360 9.594529            2            2.0   1.0000   0.9837       16
35.817200 41.458041            4            4.0  -1.0000   0.0002      132
26.169814 16.522428            8            8.0   1.0000   0.9843       84
23.266625 20.363437           16           16.0  -1.0000   0.0008      248
24.219722 25.172818           32           32.0  -1.0000   0.0252       90
36.875913 49.532104           64           64.0  -1.0000   0.0060      212
33.922824 30.969735          128          128.0  -1.0000   0.0051      226
33.808911 33.694998          256          256.0   1.0000   0.9996      116
38.518313 43.227716          512          512.0  -1.0000   0.0176       62
35.843264 33.168214         1024         1024.0  -1.0000   0.0034      188
35.095601 34.347938         2048         2048.0  -1.0000   0.0001      204
35.254402 35.413203         4096         4096.0  -1.0000   0.0004      262
34.910644 34.566885         8192         8192.0  -1.0000   0.0109      114
35.081335 35.252027        16384        16384.0  -1.0000   0.0002      200
35.649935 36.218534        32768        32768.0   1.0000   1.0000      254

finished run
number of examples = 64160
weighted example sum = 64160.000000
weighted label sum = -640.000000
average loss = 35.851201
best constant = -0.009975
best constant's loss = 0.999901
total feature number = 11608392
CPU times: user 15.9 ms, sys: 20.7 ms, total: 36.6 ms
Wall time: 719 ms

In [92]:
calc_class_metrics('predictions.txt', 'drugs.class.test.vw')

(0.9593827930174563, 0.953857649915935, 0.9646095717884131)

### Нативная работа с категориальными признаками. Деревья решений.

Как можно было видеть выше, огромное количество признаков может возникать из-за кодирования больших категориальных признаков или текста. Есть алтернативный способ работы с такими признаками - использование деревьев решений. Эти модели могут использовать изначальные признаки "как есть", а значит и нет вообще пробелмы с количеством признаков.

Один из хороших примерно инструментов, которые активно используют возможности деревьев для работы с категориями - CatBoost. Сама приставка Cat = Categorical, показывая что эта версия бустинга деревьев очень хорошо справляется с таким типом данных.

In [121]:
pip list | grep "catboost"

catboost                  1.2.10
Note: you may need to restart the kernel to use updated packages.

In [93]:
from catboost import Pool, CatBoostClassifier, CatBoostRegressor

In [94]:
df

,Unnamed: 0,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,"May 20, 2012",27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,"April 27, 2010",192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,"December 14, 2009",17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,"November 3, 2015",10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,"November 27, 2016",37
...,...,...,...,...,...,...,...
161292,191035,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10.0,"May 31, 2015",125
161293,127085,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1.0,"November 1, 2011",34
161294,187382,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2.0,"March 15, 2014",35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10.0,"September 19, 2015",79
161296,215220,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9.0,"December 13, 2014",116

**Историческая заметка:**
Долгое время не было возможности использовать текстовые признаки в задаче регрессии. И каждый предыдущий год я просил студентов набегать на вот этот тикет и ставить лайки задаче - https://github.com/catboost/catboost/issues/1221 .

И вот, свершилось!

In [95]:
X = df[['drugName', 'condition', 'review', 'rating']]
Y = df['usefulCount']

In [96]:
Y

0          27
1         192
2          17
3          10
4          37
         ...
161292    125
161293     34
161294     35
161295     79
161296    116
Name: usefulCount, Length: 320796, dtype: int64

In [97]:
X

,drugName,condition,review,rating
0,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0
1,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0
2,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0
3,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0
4,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0
...,...,...,...,...
161292,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10.0
161293,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1.0
161294,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2.0
161295,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10.0
161296,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9.0

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=420)

In [99]:
train_pool = Pool(
    X_train, 
    y_train, 
    cat_features=[0, 1], 
    text_features=[2], 
    feature_names=list(X_train.columns)
)
test_pool = Pool(
    X_test, 
    cat_features=[0, 1], 
    text_features=[2], 
    feature_names=list(X_test.columns)
)

In [100]:
model = CatBoostRegressor()

In [101]:
%%time

model.fit(train_pool, verbose=True, plot=False)

Learning rate set to 0.098368
0:	learn: 35.2890663	total: 491ms	remaining: 8m 10s
1:	learn: 34.6127370	total: 976ms	remaining: 8m 6s
2:	learn: 34.0495009	total: 1.41s	remaining: 7m 47s
3:	learn: 33.5874955	total: 1.87s	remaining: 7m 45s
4:	learn: 33.2003497	total: 2.31s	remaining: 7m 38s
5:	learn: 32.8785335	total: 2.77s	remaining: 7m 38s
6:	learn: 32.4720987	total: 3.19s	remaining: 7m 31s
7:	learn: 32.1373289	total: 3.57s	remaining: 7m 23s
8:	learn: 31.8574671	total: 3.99s	remaining: 7m 19s
9:	learn: 31.6188589	total: 4.36s	remaining: 7m 11s
10:	learn: 31.4134171	total: 4.73s	remaining: 7m 5s
11:	learn: 31.2420471	total: 5.12s	remaining: 7m 1s
12:	learn: 31.0951054	total: 5.55s	remaining: 7m 1s
13:	learn: 30.9746579	total: 5.92s	remaining: 6m 56s
14:	learn: 30.8686787	total: 6.28s	remaining: 6m 52s
15:	learn: 30.7795885	total: 6.62s	remaining: 6m 47s
16:	learn: 30.7046092	total: 7.01s	remaining: 6m 45s
17:	learn: 30.6369182	total: 7.38s	remaining: 6m 42s
18:	learn: 30.5632258	total: 7.74s	remaining: 6m 39s
19:	learn: 30.5118657	total: 8.11s	remaining: 6m 37s
20:	learn: 30.4674203	total: 8.5s	remaining: 6m 36s
21:	learn: 30.4251822	total: 8.85s	remaining: 6m 33s
22:	learn: 30.3800390	total: 9.2s	remaining: 6m 30s
23:	learn: 30.3210276	total: 9.55s	remaining: 6m 28s
24:	learn: 30.2714505	total: 9.91s	remaining: 6m 26s
25:	learn: 30.2260370	total: 10.3s	remaining: 6m 25s
26:	learn: 30.1878152	total: 10.6s	remaining: 6m 23s
27:	learn: 30.1544968	total: 11s	remaining: 6m 20s
28:	learn: 30.1281521	total: 11.3s	remaining: 6m 17s
29:	learn: 30.1060087	total: 11.5s	remaining: 6m 12s
30:	learn: 30.0734453	total: 11.8s	remaining: 6m 8s
31:	learn: 30.0446395	total: 12.2s	remaining: 6m 7s
32:	learn: 30.0184781	total: 12.5s	remaining: 6m 5s
33:	learn: 29.9975255	total: 12.8s	remaining: 6m 2s
34:	learn: 29.9788271	total: 13s	remaining: 5m 58s
35:	learn: 29.9590930	total: 13.3s	remaining: 5m 56s
36:	learn: 29.9313695	total: 13.6s	remaining: 5m 53s
37:	learn: 29.9098020	total: 13.8s	remaining: 5m 50s
38:	learn: 29.8883209	total: 14.1s	remaining: 5m 48s
39:	learn: 29.8704465	total: 14.5s	remaining: 5m 48s
40:	learn: 29.8558355	total: 14.7s	remaining: 5m 44s
41:	learn: 29.8413866	total: 15s	remaining: 5m 42s
42:	learn: 29.8296759	total: 15.3s	remaining: 5m 40s
43:	learn: 29.8088539	total: 15.6s	remaining: 5m 38s
44:	learn: 29.7934979	total: 15.8s	remaining: 5m 36s
45:	learn: 29.7798868	total: 16.1s	remaining: 5m 33s
46:	learn: 29.7619738	total: 16.3s	remaining: 5m 31s
47:	learn: 29.7449441	total: 16.6s	remaining: 5m 29s
48:	learn: 29.7275430	total: 16.8s	remaining: 5m 26s
49:	learn: 29.7090115	total: 17.1s	remaining: 5m 24s
50:	learn: 29.6937731	total: 17.4s	remaining: 5m 22s
51:	learn: 29.6801515	total: 17.6s	remaining: 5m 21s
52:	learn: 29.6608701	total: 17.9s	remaining: 5m 20s
53:	learn: 29.6519112	total: 18.2s	remaining: 5m 18s
54:	learn: 29.6415299	total: 18.5s	remaining: 5m 17s
55:	learn: 29.6280360	total: 18.7s	remaining: 5m 15s
56:	learn: 29.6171638	total: 19s	remaining: 5m 14s
57:	learn: 29.6011050	total: 19.3s	remaining: 5m 12s
58:	learn: 29.5831460	total: 19.5s	remaining: 5m 11s
59:	learn: 29.5731212	total: 19.8s	remaining: 5m 9s
60:	learn: 29.5578879	total: 20.1s	remaining: 5m 8s
61:	learn: 29.5464721	total: 20.3s	remaining: 5m 7s
62:	learn: 29.5313764	total: 20.7s	remaining: 5m 7s
63:	learn: 29.5218681	total: 20.9s	remaining: 5m 6s
64:	learn: 29.5024202	total: 21.2s	remaining: 5m 5s
65:	learn: 29.4872013	total: 21.5s	remaining: 5m 3s
66:	learn: 29.4722759	total: 21.7s	remaining: 5m 2s
67:	learn: 29.4537995	total: 22s	remaining: 5m 1s
68:	learn: 29.4457326	total: 22.2s	remaining: 4m 59s
69:	learn: 29.4332898	total: 22.5s	remaining: 4m 58s
70:	learn: 29.4222778	total: 22.8s	remaining: 4m 57s
71:	learn: 29.4083571	total: 23s	remaining: 4m 56s
72:	learn: 29.3881643	total: 23.3s	remaining: 4m 56s
73:	learn: 29.3720647	total: 23.6s	remaining: 4m 55s
74:	learn: 29.3618126	total: 23.9s	remaining: 4m 54s
75:	learn: 29.3523325	total: 24.1s	remaining: 4m 53s
76:	learn: 29.3397203	total: 24.4s	remaining: 4m 52s
77:	learn: 29.3293062	total: 24.6s	remaining: 4m 50s
78:	learn: 29.3158226	total: 24.9s	remaining: 4m 50s
79:	learn: 29.3040683	total: 25.1s	remaining: 4m 49s
80:	learn: 29.2898830	total: 25.4s	remaining: 4m 48s
81:	learn: 29.2803131	total: 25.6s	remaining: 4m 46s
82:	learn: 29.2690684	total: 25.9s	remaining: 4m 46s
83:	learn: 29.2602527	total: 26.1s	remaining: 4m 45s
84:	learn: 29.2512181	total: 26.5s	remaining: 4m 44s
85:	learn: 29.2387943	total: 26.7s	remaining: 4m 43s
86:	learn: 29.2193886	total: 27.1s	remaining: 4m 44s
87:	learn: 29.2080163	total: 27.3s	remaining: 4m 43s
88:	learn: 29.1958083	total: 27.7s	remaining: 4m 43s
89:	learn: 29.1725075	total: 28.1s	remaining: 4m 44s
90:	learn: 29.1626984	total: 28.3s	remaining: 4m 43s
91:	learn: 29.1552123	total: 28.6s	remaining: 4m 42s
92:	learn: 29.1427279	total: 28.8s	remaining: 4m 41s
93:	learn: 29.1341895	total: 29.1s	remaining: 4m 40s
94:	learn: 29.1214940	total: 29.3s	remaining: 4m 39s
95:	learn: 29.1126772	total: 29.6s	remaining: 4m 38s
96:	learn: 29.1021013	total: 29.8s	remaining: 4m 37s
97:	learn: 29.0927760	total: 30.1s	remaining: 4m 36s
98:	learn: 29.0785415	total: 30.3s	remaining: 4m 35s
99:	learn: 29.0698882	total: 30.6s	remaining: 4m 34s
100:	learn: 29.0581971	total: 30.8s	remaining: 4m 34s
101:	learn: 29.0491652	total: 31s	remaining: 4m 33s
102:	learn: 29.0399495	total: 31.3s	remaining: 4m 32s
103:	learn: 29.0245284	total: 31.5s	remaining: 4m 31s
104:	learn: 29.0164606	total: 31.8s	remaining: 4m 30s
105:	learn: 29.0028681	total: 32s	remaining: 4m 30s
106:	learn: 28.9953688	total: 32.3s	remaining: 4m 29s
107:	learn: 28.9880302	total: 32.5s	remaining: 4m 28s
108:	learn: 28.9814146	total: 32.8s	remaining: 4m 27s
109:	learn: 28.9720023	total: 33s	remaining: 4m 26s
110:	learn: 28.9598341	total: 33.2s	remaining: 4m 26s
111:	learn: 28.9530864	total: 33.5s	remaining: 4m 25s
112:	learn: 28.9412359	total: 33.7s	remaining: 4m 24s
113:	learn: 28.9327173	total: 34s	remaining: 4m 24s
114:	learn: 28.9230995	total: 34.2s	remaining: 4m 23s
115:	learn: 28.9175222	total: 34.5s	remaining: 4m 22s
116:	learn: 28.9080064	total: 34.7s	remaining: 4m 21s
117:	learn: 28.9017257	total: 34.9s	remaining: 4m 21s
118:	learn: 28.8926497	total: 35.2s	remaining: 4m 20s
119:	learn: 28.8830408	total: 35.4s	remaining: 4m 19s
120:	learn: 28.8719287	total: 35.8s	remaining: 4m 19s
121:	learn: 28.8593725	total: 36.1s	remaining: 4m 19s
122:	learn: 28.8501609	total: 36.4s	remaining: 4m 19s
123:	learn: 28.8389504	total: 36.7s	remaining: 4m 19s
124:	learn: 28.8231983	total: 37s	remaining: 4m 19s
125:	learn: 28.8153319	total: 37.3s	remaining: 4m 18s
126:	learn: 28.8045359	total: 37.6s	remaining: 4m 18s
127:	learn: 28.7908124	total: 37.9s	remaining: 4m 18s
128:	learn: 28.7794536	total: 38.1s	remaining: 4m 17s
129:	learn: 28.7720941	total: 38.4s	remaining: 4m 16s
130:	learn: 28.7589836	total: 38.7s	remaining: 4m 16s
131:	learn: 28.7510647	total: 39.1s	remaining: 4m 16s
132:	learn: 28.7379231	total: 39.5s	remaining: 4m 17s
133:	learn: 28.7270546	total: 39.7s	remaining: 4m 16s
134:	learn: 28.7207732	total: 40s	remaining: 4m 16s
135:	learn: 28.7106290	total: 40.2s	remaining: 4m 15s
136:	learn: 28.7007574	total: 40.5s	remaining: 4m 15s
137:	learn: 28.6897051	total: 40.8s	remaining: 4m 14s
138:	learn: 28.6693691	total: 41.1s	remaining: 4m 14s
139:	learn: 28.6608289	total: 41.3s	remaining: 4m 13s
140:	learn: 28.6509263	total: 41.6s	remaining: 4m 13s
141:	learn: 28.6420587	total: 41.8s	remaining: 4m 12s
142:	learn: 28.6339923	total: 42.1s	remaining: 4m 12s
143:	learn: 28.6250934	total: 42.4s	remaining: 4m 12s
144:	learn: 28.6142852	total: 42.7s	remaining: 4m 11s
145:	learn: 28.6063345	total: 43s	remaining: 4m 11s
146:	learn: 28.5984964	total: 43.2s	remaining: 4m 10s
147:	learn: 28.5910612	total: 43.4s	remaining: 4m 10s
148:	learn: 28.5824514	total: 43.7s	remaining: 4m 9s
149:	learn: 28.5732307	total: 44s	remaining: 4m 9s
150:	learn: 28.5606392	total: 44.3s	remaining: 4m 9s
151:	learn: 28.5490840	total: 44.6s	remaining: 4m 8s
152:	learn: 28.5373134	total: 44.9s	remaining: 4m 8s
153:	learn: 28.5312503	total: 45.1s	remaining: 4m 7s
154:	learn: 28.5228621	total: 45.4s	remaining: 4m 7s

155:	learn: 28.5123044	total: 45.6s	remaining: 4m 6s
156:	learn: 28.5052673	total: 45.9s	remaining: 4m 6s
157:	learn: 28.4965354	total: 46.1s	remaining: 4m 5s
158:	learn: 28.4880542	total: 46.4s	remaining: 4m 5s
159:	learn: 28.4802618	total: 46.7s	remaining: 4m 4s
160:	learn: 28.4698060	total: 46.9s	remaining: 4m 4s
161:	learn: 28.4612163	total: 47.2s	remaining: 4m 4s
162:	learn: 28.4553066	total: 47.5s	remaining: 4m 3s
163:	learn: 28.4453321	total: 47.7s	remaining: 4m 3s
164:	learn: 28.4362955	total: 48s	remaining: 4m 2s
165:	learn: 28.4293722	total: 48.3s	remaining: 4m 2s
166:	learn: 28.4188359	total: 48.7s	remaining: 4m 2s
167:	learn: 28.4071181	total: 49s	remaining: 4m 2s
168:	learn: 28.3968046	total: 49.3s	remaining: 4m 2s
169:	learn: 28.3845246	total: 49.5s	remaining: 4m 1s
170:	learn: 28.3734754	total: 49.8s	remaining: 4m 1s
171:	learn: 28.3670468	total: 50s	remaining: 4m
172:	learn: 28.3608382	total: 50.3s	remaining: 4m
173:	learn: 28.3527426	total: 50.5s	remaining: 3m 59s
174:	learn: 28.3439062	total: 50.8s	remaining: 3m 59s
175:	learn: 28.3349036	total: 51s	remaining: 3m 58s
176:	learn: 28.3264298	total: 51.2s	remaining: 3m 58s
177:	learn: 28.3185414	total: 51.5s	remaining: 3m 57s
178:	learn: 28.3106878	total: 51.7s	remaining: 3m 57s
179:	learn: 28.2998442	total: 52s	remaining: 3m 56s
180:	learn: 28.2891177	total: 52.2s	remaining: 3m 56s
181:	learn: 28.2794058	total: 52.5s	remaining: 3m 55s
182:	learn: 28.2727876	total: 52.7s	remaining: 3m 55s
183:	learn: 28.2660737	total: 53s	remaining: 3m 54s
184:	learn: 28.2571097	total: 53.4s	remaining: 3m 55s
185:	learn: 28.2499632	total: 53.6s	remaining: 3m 54s
186:	learn: 28.2408946	total: 53.9s	remaining: 3m 54s
187:	learn: 28.2331948	total: 54.1s	remaining: 3m 53s
188:	learn: 28.2190075	total: 54.4s	remaining: 3m 53s
189:	learn: 28.2119121	total: 54.6s	remaining: 3m 52s
190:	learn: 28.2040947	total: 54.9s	remaining: 3m 52s
191:	learn: 28.1968359	total: 55.1s	remaining: 3m 52s
192:	learn: 28.1868917	total: 55.5s	remaining: 3m 51s
193:	learn: 28.1809024	total: 55.7s	remaining: 3m 51s
194:	learn: 28.1735266	total: 56s	remaining: 3m 51s
195:	learn: 28.1666781	total: 56.3s	remaining: 3m 50s
196:	learn: 28.1602048	total: 56.5s	remaining: 3m 50s
197:	learn: 28.1500527	total: 56.8s	remaining: 3m 49s
198:	learn: 28.1429270	total: 57.1s	remaining: 3m 49s
199:	learn: 28.1363845	total: 57.3s	remaining: 3m 49s
200:	learn: 28.1276514	total: 57.6s	remaining: 3m 48s
201:	learn: 28.1193198	total: 57.8s	remaining: 3m 48s
202:	learn: 28.1149465	total: 58s	remaining: 3m 47s
203:	learn: 28.1081648	total: 58.3s	remaining: 3m 47s
204:	learn: 28.0992848	total: 58.5s	remaining: 3m 46s
205:	learn: 28.0924004	total: 58.8s	remaining: 3m 46s
206:	learn: 28.0813202	total: 59.2s	remaining: 3m 46s
207:	learn: 28.0747298	total: 59.5s	remaining: 3m 46s
208:	learn: 28.0657315	total: 59.8s	remaining: 3m 46s
209:	learn: 28.0600951	total: 1m	remaining: 3m 45s
210:	learn: 28.0490629	total: 1m	remaining: 3m 45s
211:	learn: 28.0422043	total: 1m	remaining: 3m 44s
212:	learn: 28.0323098	total: 1m	remaining: 3m 44s
213:	learn: 28.0240705	total: 1m 1s	remaining: 3m 44s
214:	learn: 28.0160770	total: 1m 1s	remaining: 3m 43s
215:	learn: 28.0104434	total: 1m 1s	remaining: 3m 43s
216:	learn: 28.0034104	total: 1m 1s	remaining: 3m 42s
217:	learn: 27.9961545	total: 1m 2s	remaining: 3m 42s
218:	learn: 27.9887227	total: 1m 2s	remaining: 3m 42s
219:	learn: 27.9814225	total: 1m 2s	remaining: 3m 42s
220:	learn: 27.9739018	total: 1m 2s	remaining: 3m 41s
221:	learn: 27.9665489	total: 1m 3s	remaining: 3m 41s
222:	learn: 27.9581984	total: 1m 3s	remaining: 3m 41s
223:	learn: 27.9482821	total: 1m 3s	remaining: 3m 40s
224:	learn: 27.9416235	total: 1m 3s	remaining: 3m 40s
225:	learn: 27.9329939	total: 1m 4s	remaining: 3m 39s
226:	learn: 27.9243675	total: 1m 4s	remaining: 3m 39s
227:	learn: 27.9196863	total: 1m 4s	remaining: 3m 39s
228:	learn: 27.9134916	total: 1m 5s	remaining: 3m 38s
229:	learn: 27.9057968	total: 1m 5s	remaining: 3m 38s
230:	learn: 27.8994600	total: 1m 5s	remaining: 3m 38s
231:	learn: 27.8935629	total: 1m 5s	remaining: 3m 37s
232:	learn: 27.8859754	total: 1m 6s	remaining: 3m 37s
233:	learn: 27.8793313	total: 1m 6s	remaining: 3m 37s
234:	learn: 27.8725932	total: 1m 6s	remaining: 3m 36s
235:	learn: 27.8649920	total: 1m 6s	remaining: 3m 36s
236:	learn: 27.8577346	total: 1m 7s	remaining: 3m 36s
237:	learn: 27.8526457	total: 1m 7s	remaining: 3m 36s
238:	learn: 27.8457495	total: 1m 7s	remaining: 3m 35s
239:	learn: 27.8360149	total: 1m 8s	remaining: 3m 35s
240:	learn: 27.8271371	total: 1m 8s	remaining: 3m 34s
241:	learn: 27.8181288	total: 1m 8s	remaining: 3m 34s
242:	learn: 27.8110845	total: 1m 8s	remaining: 3m 34s
243:	learn: 27.8042155	total: 1m 8s	remaining: 3m 33s
244:	learn: 27.7965854	total: 1m 9s	remaining: 3m 33s
245:	learn: 27.7914232	total: 1m 9s	remaining: 3m 32s
246:	learn: 27.7869850	total: 1m 9s	remaining: 3m 32s
247:	learn: 27.7811170	total: 1m 10s	remaining: 3m 32s
248:	learn: 27.7736269	total: 1m 10s	remaining: 3m 31s
249:	learn: 27.7653387	total: 1m 10s	remaining: 3m 31s
250:	learn: 27.7515017	total: 1m 10s	remaining: 3m 31s
251:	learn: 27.7449142	total: 1m 11s	remaining: 3m 31s
252:	learn: 27.7388072	total: 1m 11s	remaining: 3m 30s
253:	learn: 27.7315965	total: 1m 11s	remaining: 3m 30s
254:	learn: 27.7263158	total: 1m 11s	remaining: 3m 29s
255:	learn: 27.7208241	total: 1m 12s	remaining: 3m 29s
256:	learn: 27.7128537	total: 1m 12s	remaining: 3m 29s
257:	learn: 27.7075663	total: 1m 12s	remaining: 3m 29s
258:	learn: 27.7032088	total: 1m 13s	remaining: 3m 28s
259:	learn: 27.6997817	total: 1m 13s	remaining: 3m 28s
260:	learn: 27.6933486	total: 1m 13s	remaining: 3m 28s
261:	learn: 27.6856337	total: 1m 13s	remaining: 3m 28s
262:	learn: 27.6806274	total: 1m 14s	remaining: 3m 27s
263:	learn: 27.6744218	total: 1m 14s	remaining: 3m 27s
264:	learn: 27.6690802	total: 1m 14s	remaining: 3m 26s
265:	learn: 27.6638594	total: 1m 14s	remaining: 3m 26s
266:	learn: 27.6560453	total: 1m 15s	remaining: 3m 26s
267:	learn: 27.6505994	total: 1m 15s	remaining: 3m 25s
268:	learn: 27.6463776	total: 1m 15s	remaining: 3m 25s
269:	learn: 27.6423306	total: 1m 15s	remaining: 3m 25s
270:	learn: 27.6346964	total: 1m 16s	remaining: 3m 24s
271:	learn: 27.6275555	total: 1m 16s	remaining: 3m 24s
272:	learn: 27.6194308	total: 1m 16s	remaining: 3m 23s
273:	learn: 27.6126008	total: 1m 16s	remaining: 3m 23s
274:	learn: 27.6069917	total: 1m 17s	remaining: 3m 23s
275:	learn: 27.5937098	total: 1m 17s	remaining: 3m 22s
276:	learn: 27.5848719	total: 1m 17s	remaining: 3m 22s
277:	learn: 27.5778881	total: 1m 17s	remaining: 3m 22s
278:	learn: 27.5689073	total: 1m 18s	remaining: 3m 22s
279:	learn: 27.5626107	total: 1m 18s	remaining: 3m 21s
280:	learn: 27.5562747	total: 1m 18s	remaining: 3m 21s
281:	learn: 27.5528395	total: 1m 18s	remaining: 3m 21s
282:	learn: 27.5459360	total: 1m 19s	remaining: 3m 20s
283:	learn: 27.5421137	total: 1m 19s	remaining: 3m 20s
284:	learn: 27.5382261	total: 1m 19s	remaining: 3m 20s
285:	learn: 27.5325894	total: 1m 20s	remaining: 3m 19s
286:	learn: 27.5269053	total: 1m 20s	remaining: 3m 19s
287:	learn: 27.5213840	total: 1m 20s	remaining: 3m 19s
288:	learn: 27.5166191	total: 1m 20s	remaining: 3m 18s
289:	learn: 27.5114027	total: 1m 21s	remaining: 3m 18s
290:	learn: 27.5052928	total: 1m 21s	remaining: 3m 18s
291:	learn: 27.4973749	total: 1m 21s	remaining: 3m 17s
292:	learn: 27.4916161	total: 1m 21s	remaining: 3m 17s
293:	learn: 27.4848874	total: 1m 22s	remaining: 3m 17s
294:	learn: 27.4771347	total: 1m 22s	remaining: 3m 16s
295:	learn: 27.4704267	total: 1m 22s	remaining: 3m 16s
296:	learn: 27.4647739	total: 1m 22s	remaining: 3m 16s
297:	learn: 27.4582719	total: 1m 23s	remaining: 3m 16s
298:	learn: 27.4526376	total: 1m 23s	remaining: 3m 15s
299:	learn: 27.4455684	total: 1m 23s	remaining: 3m 15s
300:	learn: 27.4403010	total: 1m 23s	remaining: 3m 14s
301:	learn: 27.4348103	total: 1m 24s	remaining: 3m 14s
302:	learn: 27.4289474	total: 1m 24s	remaining: 3m 14s
303:	learn: 27.4230524	total: 1m 24s	remaining: 3m 13s
304:	learn: 27.4172450	total: 1m 24s	remaining: 3m 13s
305:	learn: 27.4115257	total: 1m 25s	remaining: 3m 13s
306:	learn: 27.4056756	total: 1m 25s	remaining: 3m 12s

307:	learn: 27.3991939	total: 1m 25s	remaining: 3m 12s
308:	learn: 27.3952327	total: 1m 25s	remaining: 3m 12s
309:	learn: 27.3901810	total: 1m 26s	remaining: 3m 11s
310:	learn: 27.3850911	total: 1m 26s	remaining: 3m 11s
311:	learn: 27.3802108	total: 1m 26s	remaining: 3m 11s
312:	learn: 27.3718849	total: 1m 27s	remaining: 3m 11s
313:	learn: 27.3652155	total: 1m 27s	remaining: 3m 10s
314:	learn: 27.3596295	total: 1m 27s	remaining: 3m 10s
315:	learn: 27.3522613	total: 1m 27s	remaining: 3m 10s
316:	learn: 27.3467594	total: 1m 28s	remaining: 3m 9s
317:	learn: 27.3401480	total: 1m 28s	remaining: 3m 9s
318:	learn: 27.3343013	total: 1m 28s	remaining: 3m 9s
319:	learn: 27.3300322	total: 1m 28s	remaining: 3m 8s
320:	learn: 27.3235162	total: 1m 29s	remaining: 3m 8s
321:	learn: 27.3162951	total: 1m 29s	remaining: 3m 8s
322:	learn: 27.3123793	total: 1m 29s	remaining: 3m 7s
323:	learn: 27.3040742	total: 1m 29s	remaining: 3m 7s
324:	learn: 27.2968658	total: 1m 30s	remaining: 3m 7s
325:	learn: 27.2924104	total: 1m 30s	remaining: 3m 6s
326:	learn: 27.2853427	total: 1m 30s	remaining: 3m 6s
327:	learn: 27.2783238	total: 1m 30s	remaining: 3m 6s
328:	learn: 27.2719416	total: 1m 31s	remaining: 3m 5s
329:	learn: 27.2661434	total: 1m 31s	remaining: 3m 5s
330:	learn: 27.2616223	total: 1m 31s	remaining: 3m 5s
331:	learn: 27.2540982	total: 1m 31s	remaining: 3m 5s
332:	learn: 27.2505672	total: 1m 32s	remaining: 3m 4s
333:	learn: 27.2442563	total: 1m 32s	remaining: 3m 4s
334:	learn: 27.2399191	total: 1m 32s	remaining: 3m 4s
335:	learn: 27.2355785	total: 1m 32s	remaining: 3m 3s
336:	learn: 27.2321359	total: 1m 33s	remaining: 3m 3s
337:	learn: 27.2275515	total: 1m 33s	remaining: 3m 3s
338:	learn: 27.2216795	total: 1m 33s	remaining: 3m 2s
339:	learn: 27.2157183	total: 1m 33s	remaining: 3m 2s
340:	learn: 27.2102009	total: 1m 34s	remaining: 3m 2s
341:	learn: 27.2068643	total: 1m 34s	remaining: 3m 1s
342:	learn: 27.2020909	total: 1m 34s	remaining: 3m 1s
343:	learn: 27.1968623	total: 1m 34s	remaining: 3m 1s
344:	learn: 27.1904299	total: 1m 35s	remaining: 3m
345:	learn: 27.1843010	total: 1m 35s	remaining: 3m
346:	learn: 27.1754069	total: 1m 35s	remaining: 3m
347:	learn: 27.1703994	total: 1m 35s	remaining: 2m 59s
348:	learn: 27.1606340	total: 1m 36s	remaining: 2m 59s
349:	learn: 27.1550281	total: 1m 36s	remaining: 2m 59s
350:	learn: 27.1482381	total: 1m 36s	remaining: 2m 59s
351:	learn: 27.1416206	total: 1m 37s	remaining: 2m 58s
352:	learn: 27.1377338	total: 1m 37s	remaining: 2m 58s
353:	learn: 27.1344983	total: 1m 37s	remaining: 2m 58s
354:	learn: 27.1244709	total: 1m 37s	remaining: 2m 57s
355:	learn: 27.1178201	total: 1m 38s	remaining: 2m 57s
356:	learn: 27.1126937	total: 1m 38s	remaining: 2m 56s
357:	learn: 27.1040305	total: 1m 38s	remaining: 2m 56s
358:	learn: 27.0976347	total: 1m 38s	remaining: 2m 56s
359:	learn: 27.0895279	total: 1m 39s	remaining: 2m 56s
360:	learn: 27.0800563	total: 1m 39s	remaining: 2m 55s
361:	learn: 27.0746802	total: 1m 39s	remaining: 2m 55s
362:	learn: 27.0696207	total: 1m 39s	remaining: 2m 55s
363:	learn: 27.0638106	total: 1m 40s	remaining: 2m 54s
364:	learn: 27.0587373	total: 1m 40s	remaining: 2m 54s
365:	learn: 27.0511393	total: 1m 40s	remaining: 2m 54s
366:	learn: 27.0465576	total: 1m 40s	remaining: 2m 54s
367:	learn: 27.0412090	total: 1m 41s	remaining: 2m 53s
368:	learn: 27.0336611	total: 1m 41s	remaining: 2m 53s
369:	learn: 27.0292846	total: 1m 41s	remaining: 2m 53s
370:	learn: 27.0244908	total: 1m 41s	remaining: 2m 52s
371:	learn: 27.0196780	total: 1m 42s	remaining: 2m 52s
372:	learn: 27.0132398	total: 1m 42s	remaining: 2m 52s
373:	learn: 27.0029387	total: 1m 42s	remaining: 2m 51s
374:	learn: 26.9985033	total: 1m 42s	remaining: 2m 51s
375:	learn: 26.9936483	total: 1m 43s	remaining: 2m 51s
376:	learn: 26.9874667	total: 1m 43s	remaining: 2m 50s
377:	learn: 26.9804105	total: 1m 43s	remaining: 2m 50s
378:	learn: 26.9743551	total: 1m 44s	remaining: 2m 50s
379:	learn: 26.9674062	total: 1m 44s	remaining: 2m 50s
380:	learn: 26.9633452	total: 1m 44s	remaining: 2m 49s
381:	learn: 26.9570250	total: 1m 44s	remaining: 2m 49s
382:	learn: 26.9517319	total: 1m 45s	remaining: 2m 49s
383:	learn: 26.9420908	total: 1m 45s	remaining: 2m 49s
384:	learn: 26.9375444	total: 1m 45s	remaining: 2m 48s
385:	learn: 26.9325270	total: 1m 45s	remaining: 2m 48s
386:	learn: 26.9287662	total: 1m 46s	remaining: 2m 48s
387:	learn: 26.9238408	total: 1m 46s	remaining: 2m 47s
388:	learn: 26.9186031	total: 1m 46s	remaining: 2m 47s
389:	learn: 26.9148184	total: 1m 46s	remaining: 2m 47s
390:	learn: 26.9099868	total: 1m 47s	remaining: 2m 46s
391:	learn: 26.9045649	total: 1m 47s	remaining: 2m 46s
392:	learn: 26.9005574	total: 1m 47s	remaining: 2m 46s
393:	learn: 26.8969328	total: 1m 47s	remaining: 2m 45s
394:	learn: 26.8913465	total: 1m 48s	remaining: 2m 45s
395:	learn: 26.8848037	total: 1m 48s	remaining: 2m 45s
396:	learn: 26.8787506	total: 1m 48s	remaining: 2m 44s
397:	learn: 26.8709011	total: 1m 48s	remaining: 2m 44s
398:	learn: 26.8667399	total: 1m 49s	remaining: 2m 44s
399:	learn: 26.8621220	total: 1m 49s	remaining: 2m 44s
400:	learn: 26.8583174	total: 1m 49s	remaining: 2m 43s
401:	learn: 26.8534115	total: 1m 49s	remaining: 2m 43s
402:	learn: 26.8486002	total: 1m 50s	remaining: 2m 43s
403:	learn: 26.8427487	total: 1m 50s	remaining: 2m 42s
404:	learn: 26.8374232	total: 1m 50s	remaining: 2m 42s
405:	learn: 26.8328162	total: 1m 50s	remaining: 2m 42s
406:	learn: 26.8253443	total: 1m 51s	remaining: 2m 41s
407:	learn: 26.8209368	total: 1m 51s	remaining: 2m 41s
408:	learn: 26.8163674	total: 1m 51s	remaining: 2m 41s
409:	learn: 26.8109134	total: 1m 51s	remaining: 2m 40s
410:	learn: 26.8054184	total: 1m 52s	remaining: 2m 40s
411:	learn: 26.8005558	total: 1m 52s	remaining: 2m 40s
412:	learn: 26.7955172	total: 1m 52s	remaining: 2m 40s
413:	learn: 26.7909236	total: 1m 52s	remaining: 2m 39s
414:	learn: 26.7857958	total: 1m 53s	remaining: 2m 39s
415:	learn: 26.7795873	total: 1m 53s	remaining: 2m 39s
416:	learn: 26.7734622	total: 1m 53s	remaining: 2m 39s
417:	learn: 26.7685578	total: 1m 54s	remaining: 2m 38s
418:	learn: 26.7627867	total: 1m 54s	remaining: 2m 38s
419:	learn: 26.7567770	total: 1m 54s	remaining: 2m 38s
420:	learn: 26.7483796	total: 1m 54s	remaining: 2m 37s
421:	learn: 26.7439448	total: 1m 55s	remaining: 2m 37s
422:	learn: 26.7392883	total: 1m 55s	remaining: 2m 37s
423:	learn: 26.7338205	total: 1m 55s	remaining: 2m 37s
424:	learn: 26.7302062	total: 1m 55s	remaining: 2m 36s
425:	learn: 26.7251753	total: 1m 56s	remaining: 2m 36s
426:	learn: 26.7210901	total: 1m 56s	remaining: 2m 36s
427:	learn: 26.7170398	total: 1m 56s	remaining: 2m 35s
428:	learn: 26.7121764	total: 1m 56s	remaining: 2m 35s
429:	learn: 26.7059040	total: 1m 57s	remaining: 2m 35s
430:	learn: 26.7002274	total: 1m 57s	remaining: 2m 35s
431:	learn: 26.6959908	total: 1m 57s	remaining: 2m 34s
432:	learn: 26.6926519	total: 1m 57s	remaining: 2m 34s
433:	learn: 26.6891519	total: 1m 58s	remaining: 2m 34s
434:	learn: 26.6841210	total: 1m 58s	remaining: 2m 33s
435:	learn: 26.6807849	total: 1m 58s	remaining: 2m 33s
436:	learn: 26.6767893	total: 1m 58s	remaining: 2m 33s
437:	learn: 26.6715734	total: 1m 59s	remaining: 2m 32s
438:	learn: 26.6662049	total: 1m 59s	remaining: 2m 32s
439:	learn: 26.6617155	total: 1m 59s	remaining: 2m 32s
440:	learn: 26.6574268	total: 1m 59s	remaining: 2m 32s
441:	learn: 26.6522731	total: 2m	remaining: 2m 31s
442:	learn: 26.6481888	total: 2m	remaining: 2m 31s
443:	learn: 26.6437150	total: 2m	remaining: 2m 31s
444:	learn: 26.6392503	total: 2m	remaining: 2m 30s
445:	learn: 26.6343020	total: 2m 1s	remaining: 2m 30s
446:	learn: 26.6275200	total: 2m 1s	remaining: 2m 30s
447:	learn: 26.6215889	total: 2m 1s	remaining: 2m 30s
448:	learn: 26.6159932	total: 2m 2s	remaining: 2m 29s
449:	learn: 26.6108182	total: 2m 2s	remaining: 2m 29s
450:	learn: 26.6058156	total: 2m 2s	remaining: 2m 29s
451:	learn: 26.6002895	total: 2m 2s	remaining: 2m 28s
452:	learn: 26.5955626	total: 2m 3s	remaining: 2m 28s
453:	learn: 26.5910640	total: 2m 3s	remaining: 2m 28s
454:	learn: 26.5846272	total: 2m 3s	remaining: 2m 28s
455:	learn: 26.5802281	total: 2m 3s	remaining: 2m 27s
456:	learn: 26.5740643	total: 2m 4s	remaining: 2m 27s
457:	learn: 26.5704950	total: 2m 4s	remaining: 2m 27s

458:	learn: 26.5666652	total: 2m 4s	remaining: 2m 26s
459:	learn: 26.5590295	total: 2m 4s	remaining: 2m 26s
460:	learn: 26.5531843	total: 2m 5s	remaining: 2m 26s
461:	learn: 26.5468556	total: 2m 5s	remaining: 2m 26s
462:	learn: 26.5403104	total: 2m 5s	remaining: 2m 25s
463:	learn: 26.5353765	total: 2m 6s	remaining: 2m 25s
464:	learn: 26.5308581	total: 2m 6s	remaining: 2m 25s
465:	learn: 26.5257643	total: 2m 6s	remaining: 2m 24s
466:	learn: 26.5204138	total: 2m 6s	remaining: 2m 24s
467:	learn: 26.5161411	total: 2m 7s	remaining: 2m 24s
468:	learn: 26.5101275	total: 2m 7s	remaining: 2m 24s
469:	learn: 26.5038269	total: 2m 7s	remaining: 2m 23s
470:	learn: 26.4989704	total: 2m 7s	remaining: 2m 23s
471:	learn: 26.4926857	total: 2m 8s	remaining: 2m 23s
472:	learn: 26.4879088	total: 2m 8s	remaining: 2m 23s
473:	learn: 26.4849966	total: 2m 8s	remaining: 2m 22s
474:	learn: 26.4806746	total: 2m 8s	remaining: 2m 22s
475:	learn: 26.4738708	total: 2m 9s	remaining: 2m 22s
476:	learn: 26.4690172	total: 2m 9s	remaining: 2m 21s
477:	learn: 26.4643348	total: 2m 9s	remaining: 2m 21s
478:	learn: 26.4597372	total: 2m 9s	remaining: 2m 21s
479:	learn: 26.4479459	total: 2m 10s	remaining: 2m 21s
480:	learn: 26.4429588	total: 2m 10s	remaining: 2m 20s
481:	learn: 26.4392584	total: 2m 10s	remaining: 2m 20s
482:	learn: 26.4347911	total: 2m 10s	remaining: 2m 20s
483:	learn: 26.4306484	total: 2m 11s	remaining: 2m 19s
484:	learn: 26.4266993	total: 2m 11s	remaining: 2m 19s
485:	learn: 26.4207365	total: 2m 11s	remaining: 2m 19s
486:	learn: 26.4166245	total: 2m 11s	remaining: 2m 18s
487:	learn: 26.4119823	total: 2m 12s	remaining: 2m 18s
488:	learn: 26.4071549	total: 2m 12s	remaining: 2m 18s
489:	learn: 26.4002013	total: 2m 12s	remaining: 2m 18s
490:	learn: 26.3946998	total: 2m 12s	remaining: 2m 17s
491:	learn: 26.3874660	total: 2m 13s	remaining: 2m 17s
492:	learn: 26.3817460	total: 2m 13s	remaining: 2m 17s
493:	learn: 26.3781083	total: 2m 13s	remaining: 2m 16s
494:	learn: 26.3726289	total: 2m 13s	remaining: 2m 16s
495:	learn: 26.3661898	total: 2m 14s	remaining: 2m 16s
496:	learn: 26.3593051	total: 2m 14s	remaining: 2m 16s
497:	learn: 26.3535632	total: 2m 14s	remaining: 2m 15s
498:	learn: 26.3488395	total: 2m 15s	remaining: 2m 15s
499:	learn: 26.3436447	total: 2m 15s	remaining: 2m 15s
500:	learn: 26.3383586	total: 2m 15s	remaining: 2m 14s
501:	learn: 26.3346061	total: 2m 15s	remaining: 2m 14s
502:	learn: 26.3302780	total: 2m 16s	remaining: 2m 14s
503:	learn: 26.3261056	total: 2m 16s	remaining: 2m 14s
504:	learn: 26.3230768	total: 2m 16s	remaining: 2m 13s
505:	learn: 26.3161614	total: 2m 16s	remaining: 2m 13s
506:	learn: 26.3115028	total: 2m 17s	remaining: 2m 13s
507:	learn: 26.3082578	total: 2m 17s	remaining: 2m 12s
508:	learn: 26.3040299	total: 2m 17s	remaining: 2m 12s
509:	learn: 26.3003260	total: 2m 17s	remaining: 2m 12s
510:	learn: 26.2957807	total: 2m 18s	remaining: 2m 12s
511:	learn: 26.2935044	total: 2m 18s	remaining: 2m 11s
512:	learn: 26.2905731	total: 2m 18s	remaining: 2m 11s
513:	learn: 26.2870511	total: 2m 18s	remaining: 2m 11s
514:	learn: 26.2827957	total: 2m 19s	remaining: 2m 11s
515:	learn: 26.2786052	total: 2m 19s	remaining: 2m 10s
516:	learn: 26.2751196	total: 2m 19s	remaining: 2m 10s
517:	learn: 26.2707285	total: 2m 19s	remaining: 2m 10s
518:	learn: 26.2663146	total: 2m 20s	remaining: 2m 9s
519:	learn: 26.2613905	total: 2m 20s	remaining: 2m 9s
520:	learn: 26.2572176	total: 2m 20s	remaining: 2m 9s
521:	learn: 26.2527984	total: 2m 20s	remaining: 2m 9s
522:	learn: 26.2483480	total: 2m 21s	remaining: 2m 8s
523:	learn: 26.2414130	total: 2m 21s	remaining: 2m 8s
524:	learn: 26.2366763	total: 2m 21s	remaining: 2m 8s
525:	learn: 26.2321224	total: 2m 21s	remaining: 2m 7s
526:	learn: 26.2274647	total: 2m 22s	remaining: 2m 7s
527:	learn: 26.2202360	total: 2m 22s	remaining: 2m 7s
528:	learn: 26.2156954	total: 2m 22s	remaining: 2m 6s
529:	learn: 26.2119018	total: 2m 22s	remaining: 2m 6s
530:	learn: 26.2070652	total: 2m 23s	remaining: 2m 6s
531:	learn: 26.2005355	total: 2m 23s	remaining: 2m 6s
532:	learn: 26.1932963	total: 2m 23s	remaining: 2m 5s
533:	learn: 26.1836283	total: 2m 24s	remaining: 2m 5s
534:	learn: 26.1799632	total: 2m 24s	remaining: 2m 5s
535:	learn: 26.1757745	total: 2m 24s	remaining: 2m 5s
536:	learn: 26.1706418	total: 2m 24s	remaining: 2m 4s
537:	learn: 26.1665774	total: 2m 25s	remaining: 2m 4s
538:	learn: 26.1621347	total: 2m 25s	remaining: 2m 4s
539:	learn: 26.1566318	total: 2m 25s	remaining: 2m 3s
540:	learn: 26.1519175	total: 2m 25s	remaining: 2m 3s
541:	learn: 26.1476559	total: 2m 26s	remaining: 2m 3s
542:	learn: 26.1437738	total: 2m 26s	remaining: 2m 3s
543:	learn: 26.1384303	total: 2m 26s	remaining: 2m 2s
544:	learn: 26.1343617	total: 2m 26s	remaining: 2m 2s
545:	learn: 26.1288979	total: 2m 27s	remaining: 2m 2s
546:	learn: 26.1244198	total: 2m 27s	remaining: 2m 2s
547:	learn: 26.1220092	total: 2m 27s	remaining: 2m 1s
548:	learn: 26.1189639	total: 2m 27s	remaining: 2m 1s
549:	learn: 26.1147594	total: 2m 28s	remaining: 2m 1s
550:	learn: 26.1113511	total: 2m 28s	remaining: 2m 1s
551:	learn: 26.1048381	total: 2m 28s	remaining: 2m
552:	learn: 26.1014977	total: 2m 28s	remaining: 2m
553:	learn: 26.0957164	total: 2m 29s	remaining: 2m
554:	learn: 26.0915340	total: 2m 29s	remaining: 1m 59s
555:	learn: 26.0885153	total: 2m 29s	remaining: 1m 59s
556:	learn: 26.0848064	total: 2m 29s	remaining: 1m 59s
557:	learn: 26.0813662	total: 2m 30s	remaining: 1m 58s
558:	learn: 26.0773041	total: 2m 30s	remaining: 1m 58s
559:	learn: 26.0707971	total: 2m 30s	remaining: 1m 58s
560:	learn: 26.0664964	total: 2m 31s	remaining: 1m 58s
561:	learn: 26.0618683	total: 2m 31s	remaining: 1m 57s
562:	learn: 26.0579868	total: 2m 31s	remaining: 1m 57s
563:	learn: 26.0540319	total: 2m 31s	remaining: 1m 57s
564:	learn: 26.0518011	total: 2m 32s	remaining: 1m 57s
565:	learn: 26.0481048	total: 2m 32s	remaining: 1m 56s
566:	learn: 26.0437751	total: 2m 32s	remaining: 1m 56s
567:	learn: 26.0385807	total: 2m 32s	remaining: 1m 56s
568:	learn: 26.0345782	total: 2m 33s	remaining: 1m 55s
569:	learn: 26.0304423	total: 2m 33s	remaining: 1m 55s
570:	learn: 26.0270251	total: 2m 33s	remaining: 1m 55s
571:	learn: 26.0227694	total: 2m 33s	remaining: 1m 55s
572:	learn: 26.0191406	total: 2m 34s	remaining: 1m 54s
573:	learn: 26.0139105	total: 2m 34s	remaining: 1m 54s
574:	learn: 26.0097918	total: 2m 34s	remaining: 1m 54s
575:	learn: 26.0061727	total: 2m 34s	remaining: 1m 54s
576:	learn: 26.0027451	total: 2m 35s	remaining: 1m 53s
577:	learn: 25.9991682	total: 2m 35s	remaining: 1m 53s
578:	learn: 25.9939846	total: 2m 35s	remaining: 1m 53s
579:	learn: 25.9895476	total: 2m 35s	remaining: 1m 52s
580:	learn: 25.9848239	total: 2m 36s	remaining: 1m 52s
581:	learn: 25.9813535	total: 2m 36s	remaining: 1m 52s
582:	learn: 25.9756617	total: 2m 36s	remaining: 1m 52s
583:	learn: 25.9702086	total: 2m 36s	remaining: 1m 51s
584:	learn: 25.9665021	total: 2m 37s	remaining: 1m 51s
585:	learn: 25.9634104	total: 2m 37s	remaining: 1m 51s
586:	learn: 25.9601275	total: 2m 37s	remaining: 1m 50s
587:	learn: 25.9538939	total: 2m 37s	remaining: 1m 50s
588:	learn: 25.9479796	total: 2m 38s	remaining: 1m 50s
589:	learn: 25.9438356	total: 2m 38s	remaining: 1m 50s
590:	learn: 25.9385722	total: 2m 38s	remaining: 1m 49s
591:	learn: 25.9338169	total: 2m 39s	remaining: 1m 49s
592:	learn: 25.9281755	total: 2m 39s	remaining: 1m 49s
593:	learn: 25.9226059	total: 2m 39s	remaining: 1m 49s
594:	learn: 25.9177870	total: 2m 39s	remaining: 1m 48s
595:	learn: 25.9134789	total: 2m 40s	remaining: 1m 48s
596:	learn: 25.9096311	total: 2m 40s	remaining: 1m 48s
597:	learn: 25.9010270	total: 2m 40s	remaining: 1m 48s
598:	learn: 25.8955711	total: 2m 40s	remaining: 1m 47s
599:	learn: 25.8919383	total: 2m 41s	remaining: 1m 47s
600:	learn: 25.8878435	total: 2m 41s	remaining: 1m 47s
601:	learn: 25.8843630	total: 2m 41s	remaining: 1m 46s
602:	learn: 25.8800314	total: 2m 42s	remaining: 1m 46s
603:	learn: 25.8758859	total: 2m 42s	remaining: 1m 46s
604:	learn: 25.8714326	total: 2m 42s	remaining: 1m 46s
605:	learn: 25.8678624	total: 2m 42s	remaining: 1m 45s
606:	learn: 25.8647785	total: 2m 43s	remaining: 1m 45s
607:	learn: 25.8593574	total: 2m 43s	remaining: 1m 45s
608:	learn: 25.8550658	total: 2m 43s	remaining: 1m 45s

609:	learn: 25.8512586	total: 2m 43s	remaining: 1m 44s
610:	learn: 25.8478308	total: 2m 44s	remaining: 1m 44s
611:	learn: 25.8439592	total: 2m 44s	remaining: 1m 44s
612:	learn: 25.8391093	total: 2m 44s	remaining: 1m 43s
613:	learn: 25.8355799	total: 2m 44s	remaining: 1m 43s
614:	learn: 25.8290068	total: 2m 45s	remaining: 1m 43s
615:	learn: 25.8238277	total: 2m 45s	remaining: 1m 43s
616:	learn: 25.8212702	total: 2m 45s	remaining: 1m 42s
617:	learn: 25.8168361	total: 2m 45s	remaining: 1m 42s
618:	learn: 25.8117160	total: 2m 46s	remaining: 1m 42s
619:	learn: 25.8081325	total: 2m 46s	remaining: 1m 41s
620:	learn: 25.8045045	total: 2m 46s	remaining: 1m 41s
621:	learn: 25.7975089	total: 2m 46s	remaining: 1m 41s
622:	learn: 25.7937496	total: 2m 47s	remaining: 1m 41s
623:	learn: 25.7894573	total: 2m 47s	remaining: 1m 40s
624:	learn: 25.7865072	total: 2m 47s	remaining: 1m 40s
625:	learn: 25.7832759	total: 2m 47s	remaining: 1m 40s
626:	learn: 25.7774577	total: 2m 48s	remaining: 1m 40s
627:	learn: 25.7726786	total: 2m 48s	remaining: 1m 39s
628:	learn: 25.7691786	total: 2m 48s	remaining: 1m 39s
629:	learn: 25.7658957	total: 2m 48s	remaining: 1m 39s
630:	learn: 25.7627523	total: 2m 49s	remaining: 1m 38s
631:	learn: 25.7579217	total: 2m 49s	remaining: 1m 38s
632:	learn: 25.7525920	total: 2m 49s	remaining: 1m 38s
633:	learn: 25.7489953	total: 2m 49s	remaining: 1m 38s
634:	learn: 25.7437258	total: 2m 50s	remaining: 1m 37s
635:	learn: 25.7396177	total: 2m 50s	remaining: 1m 37s
636:	learn: 25.7350631	total: 2m 50s	remaining: 1m 37s
637:	learn: 25.7312027	total: 2m 51s	remaining: 1m 37s
638:	learn: 25.7251412	total: 2m 51s	remaining: 1m 36s
639:	learn: 25.7200693	total: 2m 51s	remaining: 1m 36s
640:	learn: 25.7165927	total: 2m 51s	remaining: 1m 36s
641:	learn: 25.7128576	total: 2m 52s	remaining: 1m 35s
642:	learn: 25.7083798	total: 2m 52s	remaining: 1m 35s
643:	learn: 25.7046353	total: 2m 52s	remaining: 1m 35s
644:	learn: 25.7012257	total: 2m 52s	remaining: 1m 35s
645:	learn: 25.6978075	total: 2m 53s	remaining: 1m 34s
646:	learn: 25.6937932	total: 2m 53s	remaining: 1m 34s
647:	learn: 25.6899607	total: 2m 53s	remaining: 1m 34s
648:	learn: 25.6867427	total: 2m 53s	remaining: 1m 34s
649:	learn: 25.6826936	total: 2m 54s	remaining: 1m 33s
650:	learn: 25.6788299	total: 2m 54s	remaining: 1m 33s
651:	learn: 25.6723397	total: 2m 54s	remaining: 1m 33s
652:	learn: 25.6688893	total: 2m 54s	remaining: 1m 32s
653:	learn: 25.6651543	total: 2m 55s	remaining: 1m 32s
654:	learn: 25.6611933	total: 2m 55s	remaining: 1m 32s
655:	learn: 25.6568404	total: 2m 55s	remaining: 1m 32s
656:	learn: 25.6530723	total: 2m 55s	remaining: 1m 31s
657:	learn: 25.6498048	total: 2m 56s	remaining: 1m 31s
658:	learn: 25.6431839	total: 2m 56s	remaining: 1m 31s
659:	learn: 25.6392295	total: 2m 56s	remaining: 1m 31s
660:	learn: 25.6350189	total: 2m 57s	remaining: 1m 30s
661:	learn: 25.6308007	total: 2m 57s	remaining: 1m 30s
662:	learn: 25.6268161	total: 2m 57s	remaining: 1m 30s
663:	learn: 25.6222201	total: 2m 57s	remaining: 1m 29s
664:	learn: 25.6184405	total: 2m 58s	remaining: 1m 29s
665:	learn: 25.6145978	total: 2m 58s	remaining: 1m 29s
666:	learn: 25.6116641	total: 2m 58s	remaining: 1m 29s
667:	learn: 25.6087839	total: 2m 58s	remaining: 1m 28s
668:	learn: 25.6043253	total: 2m 59s	remaining: 1m 28s
669:	learn: 25.6016824	total: 2m 59s	remaining: 1m 28s
670:	learn: 25.5973782	total: 2m 59s	remaining: 1m 28s
671:	learn: 25.5915403	total: 2m 59s	remaining: 1m 27s
672:	learn: 25.5884840	total: 2m 59s	remaining: 1m 27s
673:	learn: 25.5843253	total: 3m	remaining: 1m 27s
674:	learn: 25.5812184	total: 3m	remaining: 1m 26s
675:	learn: 25.5753478	total: 3m	remaining: 1m 26s
676:	learn: 25.5705384	total: 3m 1s	remaining: 1m 26s
677:	learn: 25.5673357	total: 3m 1s	remaining: 1m 26s
678:	learn: 25.5642895	total: 3m 1s	remaining: 1m 25s
679:	learn: 25.5588392	total: 3m 1s	remaining: 1m 25s
680:	learn: 25.5556848	total: 3m 1s	remaining: 1m 25s
681:	learn: 25.5516069	total: 3m 2s	remaining: 1m 24s
682:	learn: 25.5473859	total: 3m 2s	remaining: 1m 24s
683:	learn: 25.5436180	total: 3m 2s	remaining: 1m 24s
684:	learn: 25.5394244	total: 3m 3s	remaining: 1m 24s
685:	learn: 25.5344647	total: 3m 3s	remaining: 1m 23s
686:	learn: 25.5317831	total: 3m 3s	remaining: 1m 23s
687:	learn: 25.5281292	total: 3m 3s	remaining: 1m 23s
688:	learn: 25.5243006	total: 3m 4s	remaining: 1m 23s
689:	learn: 25.5176647	total: 3m 4s	remaining: 1m 22s
690:	learn: 25.5140874	total: 3m 4s	remaining: 1m 22s
691:	learn: 25.5101855	total: 3m 4s	remaining: 1m 22s
692:	learn: 25.5073380	total: 3m 5s	remaining: 1m 21s
693:	learn: 25.5032505	total: 3m 5s	remaining: 1m 21s
694:	learn: 25.4979532	total: 3m 5s	remaining: 1m 21s
695:	learn: 25.4953940	total: 3m 5s	remaining: 1m 21s
696:	learn: 25.4924031	total: 3m 6s	remaining: 1m 20s
697:	learn: 25.4865608	total: 3m 6s	remaining: 1m 20s
698:	learn: 25.4817286	total: 3m 6s	remaining: 1m 20s
699:	learn: 25.4790055	total: 3m 6s	remaining: 1m 20s
700:	learn: 25.4754454	total: 3m 7s	remaining: 1m 19s
701:	learn: 25.4717797	total: 3m 7s	remaining: 1m 19s
702:	learn: 25.4688371	total: 3m 7s	remaining: 1m 19s
703:	learn: 25.4656478	total: 3m 7s	remaining: 1m 18s
704:	learn: 25.4625774	total: 3m 8s	remaining: 1m 18s
705:	learn: 25.4590020	total: 3m 8s	remaining: 1m 18s
706:	learn: 25.4554092	total: 3m 8s	remaining: 1m 18s
707:	learn: 25.4515838	total: 3m 8s	remaining: 1m 17s
708:	learn: 25.4484333	total: 3m 9s	remaining: 1m 17s
709:	learn: 25.4451599	total: 3m 9s	remaining: 1m 17s
710:	learn: 25.4411906	total: 3m 9s	remaining: 1m 17s
711:	learn: 25.4376202	total: 3m 9s	remaining: 1m 16s
712:	learn: 25.4335592	total: 3m 10s	remaining: 1m 16s
713:	learn: 25.4295251	total: 3m 10s	remaining: 1m 16s
714:	learn: 25.4261882	total: 3m 10s	remaining: 1m 16s
715:	learn: 25.4223480	total: 3m 10s	remaining: 1m 15s
716:	learn: 25.4199536	total: 3m 11s	remaining: 1m 15s
717:	learn: 25.4176194	total: 3m 11s	remaining: 1m 15s
718:	learn: 25.4139100	total: 3m 11s	remaining: 1m 14s
719:	learn: 25.4087172	total: 3m 11s	remaining: 1m 14s
720:	learn: 25.4046393	total: 3m 12s	remaining: 1m 14s
721:	learn: 25.4005992	total: 3m 12s	remaining: 1m 14s
722:	learn: 25.3970400	total: 3m 12s	remaining: 1m 13s
723:	learn: 25.3937623	total: 3m 12s	remaining: 1m 13s
724:	learn: 25.3885543	total: 3m 13s	remaining: 1m 13s
725:	learn: 25.3849104	total: 3m 13s	remaining: 1m 13s
726:	learn: 25.3808722	total: 3m 13s	remaining: 1m 12s
727:	learn: 25.3776600	total: 3m 13s	remaining: 1m 12s
728:	learn: 25.3727547	total: 3m 14s	remaining: 1m 12s
729:	learn: 25.3695403	total: 3m 14s	remaining: 1m 11s
730:	learn: 25.3659997	total: 3m 14s	remaining: 1m 11s
731:	learn: 25.3624211	total: 3m 14s	remaining: 1m 11s
732:	learn: 25.3576859	total: 3m 15s	remaining: 1m 11s
733:	learn: 25.3537129	total: 3m 15s	remaining: 1m 10s
734:	learn: 25.3487983	total: 3m 15s	remaining: 1m 10s
735:	learn: 25.3452574	total: 3m 16s	remaining: 1m 10s
736:	learn: 25.3405738	total: 3m 16s	remaining: 1m 10s
737:	learn: 25.3383217	total: 3m 16s	remaining: 1m 9s
738:	learn: 25.3349315	total: 3m 16s	remaining: 1m 9s
739:	learn: 25.3324530	total: 3m 17s	remaining: 1m 9s
740:	learn: 25.3286767	total: 3m 17s	remaining: 1m 8s
741:	learn: 25.3225170	total: 3m 17s	remaining: 1m 8s
742:	learn: 25.3187139	total: 3m 17s	remaining: 1m 8s
743:	learn: 25.3132156	total: 3m 18s	remaining: 1m 8s
744:	learn: 25.3089872	total: 3m 18s	remaining: 1m 7s
745:	learn: 25.3047291	total: 3m 18s	remaining: 1m 7s
746:	learn: 25.3021174	total: 3m 18s	remaining: 1m 7s
747:	learn: 25.2987080	total: 3m 19s	remaining: 1m 7s
748:	learn: 25.2950180	total: 3m 19s	remaining: 1m 6s
749:	learn: 25.2919678	total: 3m 19s	remaining: 1m 6s
750:	learn: 25.2868824	total: 3m 19s	remaining: 1m 6s
751:	learn: 25.2842408	total: 3m 19s	remaining: 1m 5s
752:	learn: 25.2800189	total: 3m 20s	remaining: 1m 5s
753:	learn: 25.2769888	total: 3m 20s	remaining: 1m 5s
754:	learn: 25.2727930	total: 3m 20s	remaining: 1m 5s
755:	learn: 25.2697247	total: 3m 21s	remaining: 1m 4s
756:	learn: 25.2649479	total: 3m 21s	remaining: 1m 4s
757:	learn: 25.2617330	total: 3m 21s	remaining: 1m 4s
758:	learn: 25.2573335	total: 3m 21s	remaining: 1m 4s
759:	learn: 25.2535517	total: 3m 22s	remaining: 1m 3s

760:	learn: 25.2491459	total: 3m 22s	remaining: 1m 3s
761:	learn: 25.2447874	total: 3m 22s	remaining: 1m 3s
762:	learn: 25.2412576	total: 3m 22s	remaining: 1m 3s
763:	learn: 25.2376743	total: 3m 23s	remaining: 1m 2s
764:	learn: 25.2351323	total: 3m 23s	remaining: 1m 2s
765:	learn: 25.2319512	total: 3m 23s	remaining: 1m 2s
766:	learn: 25.2273097	total: 3m 23s	remaining: 1m 1s
767:	learn: 25.2231289	total: 3m 24s	remaining: 1m 1s
768:	learn: 25.2189838	total: 3m 24s	remaining: 1m 1s
769:	learn: 25.2143238	total: 3m 24s	remaining: 1m 1s
770:	learn: 25.2103910	total: 3m 24s	remaining: 1m
771:	learn: 25.2078978	total: 3m 25s	remaining: 1m
772:	learn: 25.2035597	total: 3m 25s	remaining: 1m
773:	learn: 25.1995308	total: 3m 25s	remaining: 1m
774:	learn: 25.1932646	total: 3m 26s	remaining: 59.8s
775:	learn: 25.1881042	total: 3m 26s	remaining: 59.5s
776:	learn: 25.1845538	total: 3m 26s	remaining: 59.3s
777:	learn: 25.1807604	total: 3m 26s	remaining: 59s
778:	learn: 25.1765796	total: 3m 27s	remaining: 58.7s
779:	learn: 25.1716877	total: 3m 27s	remaining: 58.5s
780:	learn: 25.1681743	total: 3m 27s	remaining: 58.2s
781:	learn: 25.1641124	total: 3m 27s	remaining: 58s
782:	learn: 25.1597819	total: 3m 28s	remaining: 57.7s
783:	learn: 25.1547761	total: 3m 28s	remaining: 57.5s
784:	learn: 25.1495914	total: 3m 28s	remaining: 57.2s
785:	learn: 25.1468413	total: 3m 29s	remaining: 56.9s
786:	learn: 25.1433065	total: 3m 29s	remaining: 56.7s
787:	learn: 25.1384042	total: 3m 29s	remaining: 56.4s
788:	learn: 25.1343727	total: 3m 29s	remaining: 56.1s
789:	learn: 25.1308173	total: 3m 30s	remaining: 55.9s
790:	learn: 25.1255282	total: 3m 30s	remaining: 55.6s
791:	learn: 25.1228109	total: 3m 30s	remaining: 55.3s
792:	learn: 25.1203682	total: 3m 30s	remaining: 55s
793:	learn: 25.1135906	total: 3m 31s	remaining: 54.8s
794:	learn: 25.1084837	total: 3m 31s	remaining: 54.5s
795:	learn: 25.1045286	total: 3m 31s	remaining: 54.2s
796:	learn: 25.1009411	total: 3m 31s	remaining: 54s
797:	learn: 25.0963277	total: 3m 32s	remaining: 53.7s
798:	learn: 25.0926710	total: 3m 32s	remaining: 53.4s
799:	learn: 25.0888275	total: 3m 32s	remaining: 53.2s
800:	learn: 25.0858465	total: 3m 32s	remaining: 52.9s
801:	learn: 25.0824266	total: 3m 33s	remaining: 52.6s
802:	learn: 25.0793972	total: 3m 33s	remaining: 52.4s
803:	learn: 25.0767287	total: 3m 33s	remaining: 52.1s
804:	learn: 25.0737496	total: 3m 33s	remaining: 51.8s
805:	learn: 25.0696128	total: 3m 34s	remaining: 51.5s
806:	learn: 25.0657809	total: 3m 34s	remaining: 51.3s
807:	learn: 25.0621753	total: 3m 34s	remaining: 51s
808:	learn: 25.0597106	total: 3m 34s	remaining: 50.7s
809:	learn: 25.0549090	total: 3m 35s	remaining: 50.5s
810:	learn: 25.0504262	total: 3m 35s	remaining: 50.2s
811:	learn: 25.0472362	total: 3m 35s	remaining: 49.9s
812:	learn: 25.0445627	total: 3m 35s	remaining: 49.7s
813:	learn: 25.0409955	total: 3m 36s	remaining: 49.4s
814:	learn: 25.0379132	total: 3m 36s	remaining: 49.1s
815:	learn: 25.0347681	total: 3m 36s	remaining: 48.9s
816:	learn: 25.0305644	total: 3m 37s	remaining: 48.6s
817:	learn: 25.0270871	total: 3m 37s	remaining: 48.3s
818:	learn: 25.0241849	total: 3m 37s	remaining: 48.1s
819:	learn: 25.0201793	total: 3m 37s	remaining: 47.8s
820:	learn: 25.0131980	total: 3m 38s	remaining: 47.5s
821:	learn: 25.0103010	total: 3m 38s	remaining: 47.3s
822:	learn: 25.0075664	total: 3m 38s	remaining: 47s
823:	learn: 25.0035699	total: 3m 38s	remaining: 46.7s
824:	learn: 24.9996160	total: 3m 39s	remaining: 46.5s
825:	learn: 24.9956220	total: 3m 39s	remaining: 46.2s
826:	learn: 24.9915083	total: 3m 39s	remaining: 45.9s
827:	learn: 24.9876915	total: 3m 39s	remaining: 45.7s
828:	learn: 24.9844547	total: 3m 40s	remaining: 45.4s
829:	learn: 24.9807884	total: 3m 40s	remaining: 45.1s
830:	learn: 24.9759578	total: 3m 40s	remaining: 44.9s
831:	learn: 24.9716119	total: 3m 40s	remaining: 44.6s
832:	learn: 24.9677574	total: 3m 41s	remaining: 44.3s
833:	learn: 24.9632169	total: 3m 41s	remaining: 44.1s
834:	learn: 24.9602659	total: 3m 41s	remaining: 43.8s
835:	learn: 24.9569400	total: 3m 41s	remaining: 43.5s
836:	learn: 24.9540124	total: 3m 42s	remaining: 43.3s
837:	learn: 24.9519973	total: 3m 42s	remaining: 43s
838:	learn: 24.9488182	total: 3m 42s	remaining: 42.7s
839:	learn: 24.9456402	total: 3m 42s	remaining: 42.4s
840:	learn: 24.9405005	total: 3m 43s	remaining: 42.2s
841:	learn: 24.9371911	total: 3m 43s	remaining: 41.9s
842:	learn: 24.9338837	total: 3m 43s	remaining: 41.6s
843:	learn: 24.9308218	total: 3m 43s	remaining: 41.4s
844:	learn: 24.9283160	total: 3m 44s	remaining: 41.1s
845:	learn: 24.9246208	total: 3m 44s	remaining: 40.8s
846:	learn: 24.9210455	total: 3m 44s	remaining: 40.6s
847:	learn: 24.9182199	total: 3m 44s	remaining: 40.3s
848:	learn: 24.9144069	total: 3m 45s	remaining: 40s
849:	learn: 24.9125555	total: 3m 45s	remaining: 39.8s
850:	learn: 24.9081110	total: 3m 45s	remaining: 39.5s
851:	learn: 24.9046763	total: 3m 45s	remaining: 39.2s
852:	learn: 24.9008251	total: 3m 46s	remaining: 39s
853:	learn: 24.8986961	total: 3m 46s	remaining: 38.7s
854:	learn: 24.8957741	total: 3m 46s	remaining: 38.4s
855:	learn: 24.8924325	total: 3m 46s	remaining: 38.2s
856:	learn: 24.8891680	total: 3m 47s	remaining: 37.9s
857:	learn: 24.8858456	total: 3m 47s	remaining: 37.6s
858:	learn: 24.8818827	total: 3m 47s	remaining: 37.4s
859:	learn: 24.8787907	total: 3m 47s	remaining: 37.1s
860:	learn: 24.8747078	total: 3m 48s	remaining: 36.8s
861:	learn: 24.8703204	total: 3m 48s	remaining: 36.6s
862:	learn: 24.8663566	total: 3m 48s	remaining: 36.3s
863:	learn: 24.8641546	total: 3m 48s	remaining: 36s
864:	learn: 24.8606104	total: 3m 49s	remaining: 35.8s
865:	learn: 24.8570381	total: 3m 49s	remaining: 35.5s
866:	learn: 24.8538394	total: 3m 49s	remaining: 35.2s
867:	learn: 24.8514776	total: 3m 49s	remaining: 35s
868:	learn: 24.8487902	total: 3m 50s	remaining: 34.7s
869:	learn: 24.8458394	total: 3m 50s	remaining: 34.4s
870:	learn: 24.8425475	total: 3m 50s	remaining: 34.1s
871:	learn: 24.8378135	total: 3m 50s	remaining: 33.9s
872:	learn: 24.8338484	total: 3m 51s	remaining: 33.6s
873:	learn: 24.8309611	total: 3m 51s	remaining: 33.4s
874:	learn: 24.8258339	total: 3m 51s	remaining: 33.1s
875:	learn: 24.8233432	total: 3m 51s	remaining: 32.8s
876:	learn: 24.8200717	total: 3m 52s	remaining: 32.6s
877:	learn: 24.8168115	total: 3m 52s	remaining: 32.3s
878:	learn: 24.8125701	total: 3m 52s	remaining: 32s
879:	learn: 24.8098800	total: 3m 52s	remaining: 31.8s
880:	learn: 24.8046833	total: 3m 53s	remaining: 31.5s
881:	learn: 24.8021596	total: 3m 53s	remaining: 31.2s
882:	learn: 24.7988360	total: 3m 53s	remaining: 31s
883:	learn: 24.7954456	total: 3m 53s	remaining: 30.7s
884:	learn: 24.7918143	total: 3m 54s	remaining: 30.4s
885:	learn: 24.7882112	total: 3m 54s	remaining: 30.2s
886:	learn: 24.7849347	total: 3m 54s	remaining: 29.9s
887:	learn: 24.7825003	total: 3m 54s	remaining: 29.6s
888:	learn: 24.7800285	total: 3m 55s	remaining: 29.4s
889:	learn: 24.7766988	total: 3m 55s	remaining: 29.1s
890:	learn: 24.7735045	total: 3m 55s	remaining: 28.8s
891:	learn: 24.7693530	total: 3m 55s	remaining: 28.6s
892:	learn: 24.7659852	total: 3m 56s	remaining: 28.3s
893:	learn: 24.7631319	total: 3m 56s	remaining: 28s
894:	learn: 24.7604701	total: 3m 56s	remaining: 27.8s
895:	learn: 24.7578018	total: 3m 56s	remaining: 27.5s
896:	learn: 24.7546815	total: 3m 57s	remaining: 27.2s
897:	learn: 24.7511667	total: 3m 57s	remaining: 27s
898:	learn: 24.7479736	total: 3m 57s	remaining: 26.7s
899:	learn: 24.7446635	total: 3m 57s	remaining: 26.4s
900:	learn: 24.7429494	total: 3m 58s	remaining: 26.2s
901:	learn: 24.7392249	total: 3m 58s	remaining: 25.9s
902:	learn: 24.7357593	total: 3m 58s	remaining: 25.6s
903:	learn: 24.7319532	total: 3m 58s	remaining: 25.4s
904:	learn: 24.7292629	total: 3m 59s	remaining: 25.1s
905:	learn: 24.7267171	total: 3m 59s	remaining: 24.8s
906:	learn: 24.7217865	total: 3m 59s	remaining: 24.6s
907:	learn: 24.7168737	total: 4m	remaining: 24.3s
908:	learn: 24.7135690	total: 4m	remaining: 24s
909:	learn: 24.7091822	total: 4m	remaining: 23.8s
910:	learn: 24.7060210	total: 4m	remaining: 23.5s
911:	learn: 24.7026074	total: 4m	remaining: 23.3s
912:	learn: 24.6992094	total: 4m 1s	remaining: 23s

913:	learn: 24.6950172	total: 4m 1s	remaining: 22.7s
914:	learn: 24.6923687	total: 4m 1s	remaining: 22.5s
915:	learn: 24.6896539	total: 4m 2s	remaining: 22.2s
916:	learn: 24.6861009	total: 4m 2s	remaining: 21.9s
917:	learn: 24.6830322	total: 4m 2s	remaining: 21.7s
918:	learn: 24.6801329	total: 4m 2s	remaining: 21.4s
919:	learn: 24.6774057	total: 4m 3s	remaining: 21.1s
920:	learn: 24.6749858	total: 4m 3s	remaining: 20.9s
921:	learn: 24.6728378	total: 4m 3s	remaining: 20.6s
922:	learn: 24.6689094	total: 4m 3s	remaining: 20.4s
923:	learn: 24.6662837	total: 4m 4s	remaining: 20.1s
924:	learn: 24.6608547	total: 4m 4s	remaining: 19.8s
925:	learn: 24.6566507	total: 4m 4s	remaining: 19.6s
926:	learn: 24.6533424	total: 4m 5s	remaining: 19.3s
927:	learn: 24.6502775	total: 4m 5s	remaining: 19s
928:	learn: 24.6462802	total: 4m 5s	remaining: 18.8s
929:	learn: 24.6434063	total: 4m 5s	remaining: 18.5s
930:	learn: 24.6395670	total: 4m 6s	remaining: 18.2s
931:	learn: 24.6360728	total: 4m 6s	remaining: 18s
932:	learn: 24.6335508	total: 4m 6s	remaining: 17.7s
933:	learn: 24.6302473	total: 4m 6s	remaining: 17.4s
934:	learn: 24.6274361	total: 4m 7s	remaining: 17.2s
935:	learn: 24.6250946	total: 4m 7s	remaining: 16.9s
936:	learn: 24.6209113	total: 4m 7s	remaining: 16.6s
937:	learn: 24.6178472	total: 4m 7s	remaining: 16.4s
938:	learn: 24.6149765	total: 4m 8s	remaining: 16.1s
939:	learn: 24.6108451	total: 4m 8s	remaining: 15.9s
940:	learn: 24.6068663	total: 4m 8s	remaining: 15.6s
941:	learn: 24.6037201	total: 4m 8s	remaining: 15.3s
942:	learn: 24.6005408	total: 4m 9s	remaining: 15.1s
943:	learn: 24.5981945	total: 4m 9s	remaining: 14.8s
944:	learn: 24.5939922	total: 4m 9s	remaining: 14.5s
945:	learn: 24.5910891	total: 4m 9s	remaining: 14.3s
946:	learn: 24.5872456	total: 4m 10s	remaining: 14s
947:	learn: 24.5835178	total: 4m 10s	remaining: 13.7s
948:	learn: 24.5814172	total: 4m 10s	remaining: 13.5s
949:	learn: 24.5783203	total: 4m 10s	remaining: 13.2s
950:	learn: 24.5729529	total: 4m 11s	remaining: 12.9s
951:	learn: 24.5698959	total: 4m 11s	remaining: 12.7s
952:	learn: 24.5660203	total: 4m 11s	remaining: 12.4s
953:	learn: 24.5626648	total: 4m 11s	remaining: 12.1s
954:	learn: 24.5592178	total: 4m 12s	remaining: 11.9s
955:	learn: 24.5565403	total: 4m 12s	remaining: 11.6s
956:	learn: 24.5535001	total: 4m 12s	remaining: 11.4s
957:	learn: 24.5488667	total: 4m 12s	remaining: 11.1s
958:	learn: 24.5462974	total: 4m 13s	remaining: 10.8s
959:	learn: 24.5421495	total: 4m 13s	remaining: 10.6s
960:	learn: 24.5385942	total: 4m 13s	remaining: 10.3s
961:	learn: 24.5364216	total: 4m 13s	remaining: 10s
962:	learn: 24.5330181	total: 4m 14s	remaining: 9.77s
963:	learn: 24.5292418	total: 4m 14s	remaining: 9.5s
964:	learn: 24.5258768	total: 4m 14s	remaining: 9.24s
965:	learn: 24.5224696	total: 4m 14s	remaining: 8.97s
966:	learn: 24.5207734	total: 4m 15s	remaining: 8.71s
967:	learn: 24.5172917	total: 4m 15s	remaining: 8.44s
968:	learn: 24.5131470	total: 4m 15s	remaining: 8.18s
969:	learn: 24.5096350	total: 4m 15s	remaining: 7.92s
970:	learn: 24.5058660	total: 4m 16s	remaining: 7.65s
971:	learn: 24.5030826	total: 4m 16s	remaining: 7.39s
972:	learn: 24.5000289	total: 4m 16s	remaining: 7.12s
973:	learn: 24.4973991	total: 4m 16s	remaining: 6.86s
974:	learn: 24.4951323	total: 4m 17s	remaining: 6.59s
975:	learn: 24.4927970	total: 4m 17s	remaining: 6.33s
976:	learn: 24.4867212	total: 4m 17s	remaining: 6.07s
977:	learn: 24.4838908	total: 4m 18s	remaining: 5.8s
978:	learn: 24.4815917	total: 4m 18s	remaining: 5.54s
979:	learn: 24.4781471	total: 4m 18s	remaining: 5.28s
980:	learn: 24.4753363	total: 4m 18s	remaining: 5.01s
981:	learn: 24.4724997	total: 4m 18s	remaining: 4.75s
982:	learn: 24.4699736	total: 4m 19s	remaining: 4.48s
983:	learn: 24.4657988	total: 4m 19s	remaining: 4.22s
984:	learn: 24.4628313	total: 4m 19s	remaining: 3.96s
985:	learn: 24.4598027	total: 4m 20s	remaining: 3.69s
986:	learn: 24.4567560	total: 4m 20s	remaining: 3.43s
987:	learn: 24.4543813	total: 4m 20s	remaining: 3.16s
988:	learn: 24.4511078	total: 4m 20s	remaining: 2.9s
989:	learn: 24.4479654	total: 4m 21s	remaining: 2.64s
990:	learn: 24.4437616	total: 4m 21s	remaining: 2.37s
991:	learn: 24.4404513	total: 4m 21s	remaining: 2.11s
992:	learn: 24.4364447	total: 4m 21s	remaining: 1.84s
993:	learn: 24.4333821	total: 4m 22s	remaining: 1.58s
994:	learn: 24.4304646	total: 4m 22s	remaining: 1.32s
995:	learn: 24.4256337	total: 4m 22s	remaining: 1.05s
996:	learn: 24.4203894	total: 4m 22s	remaining: 791ms
997:	learn: 24.4182541	total: 4m 23s	remaining: 527ms
998:	learn: 24.4153344	total: 4m 23s	remaining: 264ms
999:	learn: 24.4122623	total: 4m 23s	remaining: 0us
CPU times: user 17min 5s, sys: 33.8 s, total: 17min 39s
Wall time: 4min 33s

CatBoostRegressor(loss_function='RMSE')

In [102]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [103]:
y_pred = model.predict(test_pool)
print(r2_score(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))

0.5302906112959198
676.7751911342218

In [104]:
model.plot_tree(
    tree_idx=0,
    pool=train_pool
)

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

Попробуем теперь тоже самое, но для классификации

In [105]:
df['usefulCount'].median()

16.0

In [106]:
X = df[['drugName', 'condition', 'review', 'rating']]
Y = df['usefulCount'].apply(lambda x: 1 if x > 16.0 else 0)

In [107]:
Y

0         1
1         1
2         1
3         0
4         1
         ..
161292    1
161293    1
161294    1
161295    1
161296    1
Name: usefulCount, Length: 320796, dtype: int64

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=420)

In [109]:
train_pool = Pool(
    X_train, 
    y_train, 
    cat_features=[0, 1], 
    text_features=[2], 
    feature_names=list(X_train.columns)
)
test_pool = Pool(
    X_test, 
    cat_features=[0, 1], 
    text_features=[2], 
    feature_names=list(X_test.columns)
)

In [110]:
model = CatBoostClassifier()

In [111]:
%%time

model.fit(train_pool, verbose=True, plot=False)

Learning rate set to 0.110081
0:	learn: 0.6547231	total: 468ms	remaining: 7m 47s
1:	learn: 0.6254482	total: 940ms	remaining: 7m 49s
2:	learn: 0.6027517	total: 1.4s	remaining: 7m 44s
3:	learn: 0.5868032	total: 1.84s	remaining: 7m 39s
4:	learn: 0.5727374	total: 2.27s	remaining: 7m 32s
5:	learn: 0.5616695	total: 2.71s	remaining: 7m 29s
6:	learn: 0.5475251	total: 3.21s	remaining: 7m 34s
7:	learn: 0.5361624	total: 3.67s	remaining: 7m 35s
8:	learn: 0.5278337	total: 4.13s	remaining: 7m 34s
9:	learn: 0.5233409	total: 4.5s	remaining: 7m 25s
10:	learn: 0.5171006	total: 4.98s	remaining: 7m 27s
11:	learn: 0.5117420	total: 5.43s	remaining: 7m 26s
12:	learn: 0.5083562	total: 5.81s	remaining: 7m 21s
13:	learn: 0.5049678	total: 6.31s	remaining: 7m 24s
14:	learn: 0.5027707	total: 6.7s	remaining: 7m 20s
15:	learn: 0.5002646	total: 7.15s	remaining: 7m 19s
16:	learn: 0.4985155	total: 7.53s	remaining: 7m 15s
17:	learn: 0.4967042	total: 7.92s	remaining: 7m 12s
18:	learn: 0.4952188	total: 8.34s	remaining: 7m 10s
19:	learn: 0.4927089	total: 8.81s	remaining: 7m 11s
20:	learn: 0.4906727	total: 9.28s	remaining: 7m 12s
21:	learn: 0.4892062	total: 9.72s	remaining: 7m 12s
22:	learn: 0.4877631	total: 10.2s	remaining: 7m 12s
23:	learn: 0.4865782	total: 10.6s	remaining: 7m 12s
24:	learn: 0.4856755	total: 11.1s	remaining: 7m 12s
25:	learn: 0.4849211	total: 11.5s	remaining: 7m 10s
26:	learn: 0.4840608	total: 11.9s	remaining: 7m 9s
27:	learn: 0.4832258	total: 12.3s	remaining: 7m 7s
28:	learn: 0.4828448	total: 12.8s	remaining: 7m 8s
29:	learn: 0.4823505	total: 13.2s	remaining: 7m 6s
30:	learn: 0.4820389	total: 13.7s	remaining: 7m 7s
31:	learn: 0.4816102	total: 14.1s	remaining: 7m 5s
32:	learn: 0.4813660	total: 14.5s	remaining: 7m 5s
33:	learn: 0.4812024	total: 14.8s	remaining: 7m 1s
34:	learn: 0.4808833	total: 15.3s	remaining: 7m
35:	learn: 0.4805220	total: 15.6s	remaining: 6m 58s
36:	learn: 0.4801354	total: 16s	remaining: 6m 57s
37:	learn: 0.4798733	total: 16.4s	remaining: 6m 55s
38:	learn: 0.4796142	total: 16.7s	remaining: 6m 51s
39:	learn: 0.4792029	total: 17.1s	remaining: 6m 50s
40:	learn: 0.4790024	total: 17.6s	remaining: 6m 50s
41:	learn: 0.4787701	total: 17.9s	remaining: 6m 47s
42:	learn: 0.4785111	total: 18.2s	remaining: 6m 46s
43:	learn: 0.4783126	total: 18.5s	remaining: 6m 42s
44:	learn: 0.4781173	total: 18.9s	remaining: 6m 40s
45:	learn: 0.4777701	total: 19.4s	remaining: 6m 41s
46:	learn: 0.4773358	total: 19.8s	remaining: 6m 41s
47:	learn: 0.4772186	total: 20.2s	remaining: 6m 40s
48:	learn: 0.4769482	total: 20.6s	remaining: 6m 39s
49:	learn: 0.4766056	total: 21s	remaining: 6m 39s
50:	learn: 0.4765218	total: 21.4s	remaining: 6m 38s
51:	learn: 0.4761806	total: 21.8s	remaining: 6m 37s
52:	learn: 0.4760343	total: 22.1s	remaining: 6m 34s
53:	learn: 0.4758350	total: 22.4s	remaining: 6m 32s
54:	learn: 0.4756164	total: 22.8s	remaining: 6m 30s
55:	learn: 0.4752858	total: 23.2s	remaining: 6m 31s
56:	learn: 0.4751043	total: 23.6s	remaining: 6m 31s
57:	learn: 0.4749257	total: 24s	remaining: 6m 29s
58:	learn: 0.4748528	total: 24.3s	remaining: 6m 27s
59:	learn: 0.4747358	total: 24.6s	remaining: 6m 25s
60:	learn: 0.4746155	total: 25s	remaining: 6m 25s
61:	learn: 0.4744285	total: 25.4s	remaining: 6m 24s
62:	learn: 0.4743623	total: 25.7s	remaining: 6m 22s
63:	learn: 0.4742366	total: 26.1s	remaining: 6m 21s
64:	learn: 0.4740850	total: 26.4s	remaining: 6m 19s
65:	learn: 0.4739629	total: 26.7s	remaining: 6m 18s
66:	learn: 0.4739391	total: 27.1s	remaining: 6m 17s
67:	learn: 0.4737803	total: 27.4s	remaining: 6m 15s
68:	learn: 0.4736862	total: 27.7s	remaining: 6m 14s
69:	learn: 0.4735116	total: 28s	remaining: 6m 12s
70:	learn: 0.4733224	total: 28.3s	remaining: 6m 10s
71:	learn: 0.4731779	total: 28.6s	remaining: 6m 9s
72:	learn: 0.4729687	total: 28.9s	remaining: 6m 7s
73:	learn: 0.4727941	total: 29.3s	remaining: 6m 6s
74:	learn: 0.4726176	total: 29.6s	remaining: 6m 5s
75:	learn: 0.4725219	total: 30s	remaining: 6m 4s
76:	learn: 0.4723626	total: 30.3s	remaining: 6m 3s
77:	learn: 0.4722748	total: 30.7s	remaining: 6m 2s
78:	learn: 0.4720947	total: 31s	remaining: 6m 1s
79:	learn: 0.4719201	total: 31.3s	remaining: 6m
80:	learn: 0.4717387	total: 31.7s	remaining: 5m 59s
81:	learn: 0.4716893	total: 32s	remaining: 5m 57s
82:	learn: 0.4713945	total: 32.3s	remaining: 5m 57s
83:	learn: 0.4712198	total: 32.6s	remaining: 5m 56s
84:	learn: 0.4710616	total: 33s	remaining: 5m 54s
85:	learn: 0.4709521	total: 33.2s	remaining: 5m 53s
86:	learn: 0.4708189	total: 33.6s	remaining: 5m 52s
87:	learn: 0.4706815	total: 33.9s	remaining: 5m 50s
88:	learn: 0.4705594	total: 34.2s	remaining: 5m 50s
89:	learn: 0.4704394	total: 34.5s	remaining: 5m 48s
90:	learn: 0.4703160	total: 34.8s	remaining: 5m 47s
91:	learn: 0.4701553	total: 35.1s	remaining: 5m 46s
92:	learn: 0.4700358	total: 35.4s	remaining: 5m 45s
93:	learn: 0.4698295	total: 35.9s	remaining: 5m 46s
94:	learn: 0.4697210	total: 36.2s	remaining: 5m 44s
95:	learn: 0.4696226	total: 36.5s	remaining: 5m 43s
96:	learn: 0.4695094	total: 36.8s	remaining: 5m 42s
97:	learn: 0.4693357	total: 37.2s	remaining: 5m 42s
98:	learn: 0.4692221	total: 37.6s	remaining: 5m 42s
99:	learn: 0.4690927	total: 37.9s	remaining: 5m 41s
100:	learn: 0.4690184	total: 38.3s	remaining: 5m 40s
101:	learn: 0.4688599	total: 38.6s	remaining: 5m 39s
102:	learn: 0.4687154	total: 38.9s	remaining: 5m 38s
103:	learn: 0.4685618	total: 39.3s	remaining: 5m 38s
104:	learn: 0.4684253	total: 39.6s	remaining: 5m 37s
105:	learn: 0.4682903	total: 39.9s	remaining: 5m 36s
106:	learn: 0.4681993	total: 40.2s	remaining: 5m 35s
107:	learn: 0.4680926	total: 40.5s	remaining: 5m 34s
108:	learn: 0.4679953	total: 40.9s	remaining: 5m 33s
109:	learn: 0.4678820	total: 41.1s	remaining: 5m 32s
110:	learn: 0.4677458	total: 41.5s	remaining: 5m 32s
111:	learn: 0.4676102	total: 41.8s	remaining: 5m 31s
112:	learn: 0.4674114	total: 42.2s	remaining: 5m 31s
113:	learn: 0.4673679	total: 42.5s	remaining: 5m 30s
114:	learn: 0.4672376	total: 42.9s	remaining: 5m 30s
115:	learn: 0.4671783	total: 43.2s	remaining: 5m 29s
116:	learn: 0.4670309	total: 43.5s	remaining: 5m 28s
117:	learn: 0.4669042	total: 43.8s	remaining: 5m 27s
118:	learn: 0.4667441	total: 44.2s	remaining: 5m 26s
119:	learn: 0.4666178	total: 44.5s	remaining: 5m 25s
120:	learn: 0.4664836	total: 44.8s	remaining: 5m 25s
121:	learn: 0.4662141	total: 45.1s	remaining: 5m 24s
122:	learn: 0.4660471	total: 45.5s	remaining: 5m 24s
123:	learn: 0.4659006	total: 45.8s	remaining: 5m 23s
124:	learn: 0.4658334	total: 46.1s	remaining: 5m 22s
125:	learn: 0.4656804	total: 46.4s	remaining: 5m 21s
126:	learn: 0.4655063	total: 46.7s	remaining: 5m 21s
127:	learn: 0.4654151	total: 47.1s	remaining: 5m 20s
128:	learn: 0.4652963	total: 47.4s	remaining: 5m 19s
129:	learn: 0.4651460	total: 47.7s	remaining: 5m 19s
130:	learn: 0.4651111	total: 48s	remaining: 5m 18s
131:	learn: 0.4650072	total: 48.4s	remaining: 5m 18s
132:	learn: 0.4648850	total: 48.7s	remaining: 5m 17s
133:	learn: 0.4648477	total: 49s	remaining: 5m 16s
134:	learn: 0.4646927	total: 49.3s	remaining: 5m 15s
135:	learn: 0.4645113	total: 49.6s	remaining: 5m 15s
136:	learn: 0.4643494	total: 49.9s	remaining: 5m 14s
137:	learn: 0.4641861	total: 50.3s	remaining: 5m 14s
138:	learn: 0.4640480	total: 50.6s	remaining: 5m 13s
139:	learn: 0.4639875	total: 50.9s	remaining: 5m 12s
140:	learn: 0.4638529	total: 51.2s	remaining: 5m 11s
141:	learn: 0.4637747	total: 51.5s	remaining: 5m 11s
142:	learn: 0.4636438	total: 51.8s	remaining: 5m 10s
143:	learn: 0.4634363	total: 52.2s	remaining: 5m 10s
144:	learn: 0.4633166	total: 52.5s	remaining: 5m 9s
145:	learn: 0.4632251	total: 52.8s	remaining: 5m 9s
146:	learn: 0.4631263	total: 53.1s	remaining: 5m 8s
147:	learn: 0.4629942	total: 53.4s	remaining: 5m 7s
148:	learn: 0.4628536	total: 53.7s	remaining: 5m 6s
149:	learn: 0.4626985	total: 54s	remaining: 5m 6s
150:	learn: 0.4626106	total: 54.3s	remaining: 5m 5s
151:	learn: 0.4624212	total: 54.6s	remaining: 5m 4s
152:	learn: 0.4622620	total: 55s	remaining: 5m 4s
153:	learn: 0.4621864	total: 55.3s	remaining: 5m 3s
154:	learn: 0.4620325	total: 55.6s	remaining: 5m 3s
155:	learn: 0.4619169	total: 55.9s	remaining: 5m 2s
156:	learn: 0.4617724	total: 56.2s	remaining: 5m 1s
157:	learn: 0.4616848	total: 56.5s	remaining: 5m 1s

158:	learn: 0.4615675	total: 56.8s	remaining: 5m
159:	learn: 0.4613856	total: 57.3s	remaining: 5m
160:	learn: 0.4612566	total: 57.6s	remaining: 5m
161:	learn: 0.4611128	total: 57.9s	remaining: 4m 59s
162:	learn: 0.4610096	total: 58.2s	remaining: 4m 58s
163:	learn: 0.4608994	total: 58.5s	remaining: 4m 58s
164:	learn: 0.4607604	total: 58.8s	remaining: 4m 57s
165:	learn: 0.4606428	total: 59.1s	remaining: 4m 57s
166:	learn: 0.4605811	total: 59.5s	remaining: 4m 56s
167:	learn: 0.4604403	total: 59.8s	remaining: 4m 56s
168:	learn: 0.4603740	total: 1m	remaining: 4m 55s
169:	learn: 0.4602557	total: 1m	remaining: 4m 55s
170:	learn: 0.4601148	total: 1m	remaining: 4m 54s
171:	learn: 0.4599619	total: 1m 1s	remaining: 4m 53s
172:	learn: 0.4598885	total: 1m 1s	remaining: 4m 53s
173:	learn: 0.4597589	total: 1m 1s	remaining: 4m 52s
174:	learn: 0.4596285	total: 1m 1s	remaining: 4m 52s
175:	learn: 0.4595037	total: 1m 2s	remaining: 4m 51s
176:	learn: 0.4593644	total: 1m 2s	remaining: 4m 51s
177:	learn: 0.4592491	total: 1m 2s	remaining: 4m 50s
178:	learn: 0.4591185	total: 1m 3s	remaining: 4m 50s
179:	learn: 0.4589881	total: 1m 3s	remaining: 4m 49s
180:	learn: 0.4588540	total: 1m 3s	remaining: 4m 48s
181:	learn: 0.4587417	total: 1m 4s	remaining: 4m 48s
182:	learn: 0.4586812	total: 1m 4s	remaining: 4m 48s
183:	learn: 0.4585597	total: 1m 4s	remaining: 4m 47s
184:	learn: 0.4584371	total: 1m 5s	remaining: 4m 46s
185:	learn: 0.4583121	total: 1m 5s	remaining: 4m 46s
186:	learn: 0.4581839	total: 1m 5s	remaining: 4m 45s
187:	learn: 0.4580320	total: 1m 6s	remaining: 4m 45s
188:	learn: 0.4579120	total: 1m 6s	remaining: 4m 44s
189:	learn: 0.4577965	total: 1m 6s	remaining: 4m 44s
190:	learn: 0.4576953	total: 1m 6s	remaining: 4m 43s
191:	learn: 0.4575331	total: 1m 7s	remaining: 4m 43s
192:	learn: 0.4574279	total: 1m 7s	remaining: 4m 42s
193:	learn: 0.4573173	total: 1m 7s	remaining: 4m 42s
194:	learn: 0.4572045	total: 1m 8s	remaining: 4m 41s
195:	learn: 0.4570407	total: 1m 8s	remaining: 4m 41s
196:	learn: 0.4568835	total: 1m 8s	remaining: 4m 40s
197:	learn: 0.4567339	total: 1m 9s	remaining: 4m 40s
198:	learn: 0.4566554	total: 1m 9s	remaining: 4m 40s
199:	learn: 0.4565190	total: 1m 9s	remaining: 4m 39s
200:	learn: 0.4564579	total: 1m 10s	remaining: 4m 39s
201:	learn: 0.4563260	total: 1m 10s	remaining: 4m 39s
202:	learn: 0.4561895	total: 1m 11s	remaining: 4m 39s
203:	learn: 0.4561090	total: 1m 11s	remaining: 4m 38s
204:	learn: 0.4560141	total: 1m 11s	remaining: 4m 38s
205:	learn: 0.4558926	total: 1m 12s	remaining: 4m 37s
206:	learn: 0.4557882	total: 1m 12s	remaining: 4m 37s
207:	learn: 0.4556617	total: 1m 12s	remaining: 4m 36s
208:	learn: 0.4555242	total: 1m 12s	remaining: 4m 36s
209:	learn: 0.4554045	total: 1m 13s	remaining: 4m 35s
210:	learn: 0.4552630	total: 1m 13s	remaining: 4m 34s
211:	learn: 0.4551218	total: 1m 13s	remaining: 4m 34s
212:	learn: 0.4549766	total: 1m 14s	remaining: 4m 34s
213:	learn: 0.4548538	total: 1m 14s	remaining: 4m 34s
214:	learn: 0.4547480	total: 1m 14s	remaining: 4m 33s
215:	learn: 0.4546190	total: 1m 15s	remaining: 4m 33s
216:	learn: 0.4544969	total: 1m 15s	remaining: 4m 32s
217:	learn: 0.4544131	total: 1m 15s	remaining: 4m 31s
218:	learn: 0.4543066	total: 1m 16s	remaining: 4m 31s
219:	learn: 0.4541841	total: 1m 16s	remaining: 4m 31s
220:	learn: 0.4541194	total: 1m 16s	remaining: 4m 30s
221:	learn: 0.4539835	total: 1m 17s	remaining: 4m 30s
222:	learn: 0.4538560	total: 1m 17s	remaining: 4m 29s
223:	learn: 0.4537442	total: 1m 17s	remaining: 4m 29s
224:	learn: 0.4536208	total: 1m 18s	remaining: 4m 28s
225:	learn: 0.4535115	total: 1m 18s	remaining: 4m 28s
226:	learn: 0.4533886	total: 1m 18s	remaining: 4m 27s
227:	learn: 0.4532868	total: 1m 18s	remaining: 4m 27s
228:	learn: 0.4531748	total: 1m 19s	remaining: 4m 26s
229:	learn: 0.4530271	total: 1m 19s	remaining: 4m 26s
230:	learn: 0.4529199	total: 1m 19s	remaining: 4m 25s
231:	learn: 0.4528218	total: 1m 20s	remaining: 4m 25s
232:	learn: 0.4526949	total: 1m 20s	remaining: 4m 24s
233:	learn: 0.4526326	total: 1m 20s	remaining: 4m 24s
234:	learn: 0.4525089	total: 1m 21s	remaining: 4m 23s
235:	learn: 0.4524164	total: 1m 21s	remaining: 4m 23s
236:	learn: 0.4523559	total: 1m 21s	remaining: 4m 22s
237:	learn: 0.4522347	total: 1m 22s	remaining: 4m 22s
238:	learn: 0.4520615	total: 1m 22s	remaining: 4m 22s
239:	learn: 0.4519694	total: 1m 22s	remaining: 4m 22s
240:	learn: 0.4518210	total: 1m 23s	remaining: 4m 21s
241:	learn: 0.4517113	total: 1m 23s	remaining: 4m 21s
242:	learn: 0.4515718	total: 1m 23s	remaining: 4m 20s
243:	learn: 0.4514817	total: 1m 24s	remaining: 4m 20s
244:	learn: 0.4513468	total: 1m 24s	remaining: 4m 20s
245:	learn: 0.4512372	total: 1m 24s	remaining: 4m 20s
246:	learn: 0.4511091	total: 1m 25s	remaining: 4m 20s
247:	learn: 0.4510465	total: 1m 25s	remaining: 4m 20s
248:	learn: 0.4509305	total: 1m 26s	remaining: 4m 19s
249:	learn: 0.4508014	total: 1m 26s	remaining: 4m 19s
250:	learn: 0.4506938	total: 1m 26s	remaining: 4m 18s
251:	learn: 0.4505546	total: 1m 27s	remaining: 4m 18s
252:	learn: 0.4504498	total: 1m 27s	remaining: 4m 17s
253:	learn: 0.4503306	total: 1m 27s	remaining: 4m 17s
254:	learn: 0.4502032	total: 1m 27s	remaining: 4m 16s
255:	learn: 0.4500836	total: 1m 28s	remaining: 4m 16s
256:	learn: 0.4500093	total: 1m 28s	remaining: 4m 16s
257:	learn: 0.4498697	total: 1m 28s	remaining: 4m 15s
258:	learn: 0.4497661	total: 1m 29s	remaining: 4m 15s
259:	learn: 0.4496496	total: 1m 29s	remaining: 4m 14s
260:	learn: 0.4495457	total: 1m 29s	remaining: 4m 14s
261:	learn: 0.4494484	total: 1m 30s	remaining: 4m 13s
262:	learn: 0.4493249	total: 1m 30s	remaining: 4m 13s
263:	learn: 0.4492762	total: 1m 30s	remaining: 4m 12s
264:	learn: 0.4491569	total: 1m 30s	remaining: 4m 12s
265:	learn: 0.4490470	total: 1m 31s	remaining: 4m 11s
266:	learn: 0.4489792	total: 1m 31s	remaining: 4m 11s
267:	learn: 0.4488689	total: 1m 31s	remaining: 4m 11s
268:	learn: 0.4487540	total: 1m 32s	remaining: 4m 10s
269:	learn: 0.4486440	total: 1m 32s	remaining: 4m 10s
270:	learn: 0.4485395	total: 1m 32s	remaining: 4m 9s
271:	learn: 0.4484114	total: 1m 33s	remaining: 4m 9s
272:	learn: 0.4482782	total: 1m 33s	remaining: 4m 8s
273:	learn: 0.4481640	total: 1m 33s	remaining: 4m 8s
274:	learn: 0.4480516	total: 1m 34s	remaining: 4m 7s
275:	learn: 0.4479490	total: 1m 34s	remaining: 4m 7s
276:	learn: 0.4478249	total: 1m 34s	remaining: 4m 7s
277:	learn: 0.4477230	total: 1m 35s	remaining: 4m 6s
278:	learn: 0.4476356	total: 1m 35s	remaining: 4m 6s
279:	learn: 0.4475076	total: 1m 35s	remaining: 4m 6s
280:	learn: 0.4474162	total: 1m 36s	remaining: 4m 5s
281:	learn: 0.4473166	total: 1m 36s	remaining: 4m 5s
282:	learn: 0.4471932	total: 1m 36s	remaining: 4m 5s
283:	learn: 0.4470587	total: 1m 37s	remaining: 4m 4s
284:	learn: 0.4469589	total: 1m 37s	remaining: 4m 4s
285:	learn: 0.4468498	total: 1m 37s	remaining: 4m 3s
286:	learn: 0.4467168	total: 1m 37s	remaining: 4m 3s
287:	learn: 0.4465948	total: 1m 38s	remaining: 4m 2s
288:	learn: 0.4464924	total: 1m 38s	remaining: 4m 2s
289:	learn: 0.4463947	total: 1m 38s	remaining: 4m 1s
290:	learn: 0.4462764	total: 1m 39s	remaining: 4m 1s
291:	learn: 0.4461872	total: 1m 39s	remaining: 4m 1s
292:	learn: 0.4460963	total: 1m 39s	remaining: 4m
293:	learn: 0.4459937	total: 1m 40s	remaining: 4m
294:	learn: 0.4458846	total: 1m 40s	remaining: 3m 59s
295:	learn: 0.4457984	total: 1m 40s	remaining: 3m 59s
296:	learn: 0.4456620	total: 1m 40s	remaining: 3m 58s
297:	learn: 0.4455556	total: 1m 41s	remaining: 3m 58s
298:	learn: 0.4454350	total: 1m 41s	remaining: 3m 58s
299:	learn: 0.4453111	total: 1m 41s	remaining: 3m 57s
300:	learn: 0.4452068	total: 1m 42s	remaining: 3m 57s
301:	learn: 0.4450960	total: 1m 42s	remaining: 3m 56s
302:	learn: 0.4450339	total: 1m 42s	remaining: 3m 56s
303:	learn: 0.4449811	total: 1m 43s	remaining: 3m 56s
304:	learn: 0.4448695	total: 1m 43s	remaining: 3m 55s
305:	learn: 0.4447709	total: 1m 43s	remaining: 3m 55s
306:	learn: 0.4446687	total: 1m 44s	remaining: 3m 54s
307:	learn: 0.4445411	total: 1m 44s	remaining: 3m 54s
308:	learn: 0.4444274	total: 1m 44s	remaining: 3m 53s
309:	learn: 0.4443034	total: 1m 44s	remaining: 3m 53s
310:	learn: 0.4442187	total: 1m 45s	remaining: 3m 53s
311:	learn: 0.4441155	total: 1m 45s	remaining: 3m 52s

312:	learn: 0.4440674	total: 1m 45s	remaining: 3m 52s
313:	learn: 0.4439545	total: 1m 46s	remaining: 3m 52s
314:	learn: 0.4438948	total: 1m 46s	remaining: 3m 51s
315:	learn: 0.4437617	total: 1m 46s	remaining: 3m 51s
316:	learn: 0.4436395	total: 1m 47s	remaining: 3m 51s
317:	learn: 0.4435601	total: 1m 47s	remaining: 3m 50s
318:	learn: 0.4434516	total: 1m 47s	remaining: 3m 50s
319:	learn: 0.4433612	total: 1m 48s	remaining: 3m 49s
320:	learn: 0.4432586	total: 1m 48s	remaining: 3m 49s
321:	learn: 0.4431399	total: 1m 48s	remaining: 3m 48s
322:	learn: 0.4430087	total: 1m 49s	remaining: 3m 48s
323:	learn: 0.4428939	total: 1m 49s	remaining: 3m 48s
324:	learn: 0.4428049	total: 1m 49s	remaining: 3m 47s
325:	learn: 0.4427138	total: 1m 50s	remaining: 3m 47s
326:	learn: 0.4425883	total: 1m 50s	remaining: 3m 47s
327:	learn: 0.4424702	total: 1m 50s	remaining: 3m 46s
328:	learn: 0.4423729	total: 1m 51s	remaining: 3m 46s
329:	learn: 0.4422588	total: 1m 51s	remaining: 3m 46s
330:	learn: 0.4421503	total: 1m 51s	remaining: 3m 45s
331:	learn: 0.4420226	total: 1m 51s	remaining: 3m 45s
332:	learn: 0.4419031	total: 1m 52s	remaining: 3m 44s
333:	learn: 0.4417938	total: 1m 52s	remaining: 3m 44s
334:	learn: 0.4416821	total: 1m 52s	remaining: 3m 44s
335:	learn: 0.4415744	total: 1m 53s	remaining: 3m 43s
336:	learn: 0.4414886	total: 1m 53s	remaining: 3m 43s
337:	learn: 0.4413699	total: 1m 53s	remaining: 3m 42s
338:	learn: 0.4412805	total: 1m 54s	remaining: 3m 42s
339:	learn: 0.4411953	total: 1m 54s	remaining: 3m 42s
340:	learn: 0.4410901	total: 1m 54s	remaining: 3m 41s
341:	learn: 0.4410231	total: 1m 55s	remaining: 3m 41s
342:	learn: 0.4409282	total: 1m 55s	remaining: 3m 40s
343:	learn: 0.4408292	total: 1m 55s	remaining: 3m 40s
344:	learn: 0.4407038	total: 1m 55s	remaining: 3m 40s
345:	learn: 0.4405712	total: 1m 56s	remaining: 3m 39s
346:	learn: 0.4405043	total: 1m 56s	remaining: 3m 39s
347:	learn: 0.4404178	total: 1m 56s	remaining: 3m 39s
348:	learn: 0.4403009	total: 1m 57s	remaining: 3m 38s
349:	learn: 0.4402058	total: 1m 57s	remaining: 3m 38s
350:	learn: 0.4400968	total: 1m 57s	remaining: 3m 37s
351:	learn: 0.4399624	total: 1m 58s	remaining: 3m 37s
352:	learn: 0.4398744	total: 1m 58s	remaining: 3m 37s
353:	learn: 0.4397815	total: 1m 58s	remaining: 3m 36s
354:	learn: 0.4396672	total: 1m 59s	remaining: 3m 36s
355:	learn: 0.4396064	total: 1m 59s	remaining: 3m 36s
356:	learn: 0.4394980	total: 1m 59s	remaining: 3m 35s
357:	learn: 0.4393986	total: 2m	remaining: 3m 35s
358:	learn: 0.4393234	total: 2m	remaining: 3m 34s
359:	learn: 0.4392088	total: 2m	remaining: 3m 34s
360:	learn: 0.4391197	total: 2m 1s	remaining: 3m 34s
361:	learn: 0.4390463	total: 2m 1s	remaining: 3m 33s
362:	learn: 0.4389470	total: 2m 1s	remaining: 3m 33s
363:	learn: 0.4388853	total: 2m 1s	remaining: 3m 32s
364:	learn: 0.4388012	total: 2m 2s	remaining: 3m 32s
365:	learn: 0.4386664	total: 2m 2s	remaining: 3m 32s
366:	learn: 0.4385710	total: 2m 2s	remaining: 3m 31s
367:	learn: 0.4384489	total: 2m 3s	remaining: 3m 31s
368:	learn: 0.4383926	total: 2m 3s	remaining: 3m 31s
369:	learn: 0.4383092	total: 2m 3s	remaining: 3m 30s
370:	learn: 0.4382035	total: 2m 4s	remaining: 3m 30s
371:	learn: 0.4381114	total: 2m 4s	remaining: 3m 30s
372:	learn: 0.4379820	total: 2m 4s	remaining: 3m 29s
373:	learn: 0.4378510	total: 2m 5s	remaining: 3m 29s
374:	learn: 0.4377344	total: 2m 5s	remaining: 3m 28s
375:	learn: 0.4376096	total: 2m 5s	remaining: 3m 28s
376:	learn: 0.4374997	total: 2m 5s	remaining: 3m 28s
377:	learn: 0.4374074	total: 2m 6s	remaining: 3m 27s
378:	learn: 0.4372993	total: 2m 6s	remaining: 3m 27s
379:	learn: 0.4371971	total: 2m 6s	remaining: 3m 27s
380:	learn: 0.4371153	total: 2m 7s	remaining: 3m 26s
381:	learn: 0.4370053	total: 2m 7s	remaining: 3m 26s
382:	learn: 0.4369074	total: 2m 7s	remaining: 3m 25s
383:	learn: 0.4368092	total: 2m 8s	remaining: 3m 25s
384:	learn: 0.4366948	total: 2m 8s	remaining: 3m 25s
385:	learn: 0.4365918	total: 2m 8s	remaining: 3m 24s
386:	learn: 0.4364736	total: 2m 9s	remaining: 3m 24s
387:	learn: 0.4363662	total: 2m 9s	remaining: 3m 24s
388:	learn: 0.4362664	total: 2m 9s	remaining: 3m 23s
389:	learn: 0.4361743	total: 2m 9s	remaining: 3m 23s
390:	learn: 0.4360527	total: 2m 10s	remaining: 3m 22s
391:	learn: 0.4359457	total: 2m 10s	remaining: 3m 22s
392:	learn: 0.4358407	total: 2m 10s	remaining: 3m 22s
393:	learn: 0.4357418	total: 2m 11s	remaining: 3m 21s
394:	learn: 0.4356413	total: 2m 11s	remaining: 3m 21s
395:	learn: 0.4355790	total: 2m 11s	remaining: 3m 21s
396:	learn: 0.4354532	total: 2m 12s	remaining: 3m 20s
397:	learn: 0.4353511	total: 2m 12s	remaining: 3m 20s
398:	learn: 0.4352123	total: 2m 12s	remaining: 3m 20s
399:	learn: 0.4351299	total: 2m 13s	remaining: 3m 19s
400:	learn: 0.4350479	total: 2m 13s	remaining: 3m 19s
401:	learn: 0.4349622	total: 2m 13s	remaining: 3m 18s
402:	learn: 0.4348704	total: 2m 14s	remaining: 3m 18s
403:	learn: 0.4347523	total: 2m 14s	remaining: 3m 18s
404:	learn: 0.4346335	total: 2m 14s	remaining: 3m 17s
405:	learn: 0.4345406	total: 2m 15s	remaining: 3m 17s
406:	learn: 0.4344450	total: 2m 15s	remaining: 3m 17s
407:	learn: 0.4343582	total: 2m 15s	remaining: 3m 16s
408:	learn: 0.4342925	total: 2m 16s	remaining: 3m 16s
409:	learn: 0.4342341	total: 2m 16s	remaining: 3m 16s
410:	learn: 0.4341764	total: 2m 16s	remaining: 3m 15s
411:	learn: 0.4340910	total: 2m 16s	remaining: 3m 15s
412:	learn: 0.4339748	total: 2m 17s	remaining: 3m 14s
413:	learn: 0.4338907	total: 2m 17s	remaining: 3m 14s
414:	learn: 0.4337972	total: 2m 17s	remaining: 3m 14s
415:	learn: 0.4337035	total: 2m 18s	remaining: 3m 13s
416:	learn: 0.4336340	total: 2m 18s	remaining: 3m 13s
417:	learn: 0.4335309	total: 2m 18s	remaining: 3m 13s
418:	learn: 0.4334294	total: 2m 18s	remaining: 3m 12s
419:	learn: 0.4333545	total: 2m 19s	remaining: 3m 12s
420:	learn: 0.4332460	total: 2m 19s	remaining: 3m 11s
421:	learn: 0.4331555	total: 2m 19s	remaining: 3m 11s
422:	learn: 0.4330424	total: 2m 20s	remaining: 3m 11s
423:	learn: 0.4329650	total: 2m 20s	remaining: 3m 10s
424:	learn: 0.4328788	total: 2m 20s	remaining: 3m 10s
425:	learn: 0.4327921	total: 2m 21s	remaining: 3m 10s
426:	learn: 0.4327150	total: 2m 21s	remaining: 3m 9s
427:	learn: 0.4326061	total: 2m 21s	remaining: 3m 9s
428:	learn: 0.4325003	total: 2m 21s	remaining: 3m 8s
429:	learn: 0.4324233	total: 2m 22s	remaining: 3m 8s
430:	learn: 0.4322930	total: 2m 22s	remaining: 3m 8s
431:	learn: 0.4321811	total: 2m 22s	remaining: 3m 7s
432:	learn: 0.4320773	total: 2m 23s	remaining: 3m 7s
433:	learn: 0.4319885	total: 2m 23s	remaining: 3m 7s
434:	learn: 0.4318806	total: 2m 23s	remaining: 3m 6s
435:	learn: 0.4317838	total: 2m 24s	remaining: 3m 6s
436:	learn: 0.4316981	total: 2m 24s	remaining: 3m 6s
437:	learn: 0.4316066	total: 2m 24s	remaining: 3m 5s
438:	learn: 0.4315452	total: 2m 25s	remaining: 3m 5s
439:	learn: 0.4314520	total: 2m 25s	remaining: 3m 4s
440:	learn: 0.4313438	total: 2m 25s	remaining: 3m 4s
441:	learn: 0.4312660	total: 2m 25s	remaining: 3m 4s
442:	learn: 0.4311717	total: 2m 26s	remaining: 3m 3s
443:	learn: 0.4311015	total: 2m 26s	remaining: 3m 3s
444:	learn: 0.4310195	total: 2m 26s	remaining: 3m 3s
445:	learn: 0.4309727	total: 2m 27s	remaining: 3m 2s
446:	learn: 0.4308876	total: 2m 27s	remaining: 3m 2s
447:	learn: 0.4308078	total: 2m 27s	remaining: 3m 2s
448:	learn: 0.4307115	total: 2m 28s	remaining: 3m 1s
449:	learn: 0.4306079	total: 2m 28s	remaining: 3m 1s
450:	learn: 0.4305169	total: 2m 28s	remaining: 3m 1s
451:	learn: 0.4304244	total: 2m 29s	remaining: 3m
452:	learn: 0.4303152	total: 2m 29s	remaining: 3m
453:	learn: 0.4302176	total: 2m 29s	remaining: 3m
454:	learn: 0.4301242	total: 2m 30s	remaining: 2m 59s
455:	learn: 0.4300445	total: 2m 30s	remaining: 2m 59s
456:	learn: 0.4299721	total: 2m 30s	remaining: 2m 58s
457:	learn: 0.4298746	total: 2m 30s	remaining: 2m 58s
458:	learn: 0.4298127	total: 2m 31s	remaining: 2m 58s
459:	learn: 0.4297110	total: 2m 31s	remaining: 2m 57s
460:	learn: 0.4296421	total: 2m 31s	remaining: 2m 57s
461:	learn: 0.4295603	total: 2m 32s	remaining: 2m 57s
462:	learn: 0.4294468	total: 2m 32s	remaining: 2m 56s
463:	learn: 0.4293539	total: 2m 32s	remaining: 2m 56s
464:	learn: 0.4292479	total: 2m 33s	remaining: 2m 56s
465:	learn: 0.4291414	total: 2m 33s	remaining: 2m 55s

466:	learn: 0.4290491	total: 2m 33s	remaining: 2m 55s
467:	learn: 0.4289873	total: 2m 34s	remaining: 2m 55s
468:	learn: 0.4288860	total: 2m 34s	remaining: 2m 54s
469:	learn: 0.4288076	total: 2m 34s	remaining: 2m 54s
470:	learn: 0.4286969	total: 2m 34s	remaining: 2m 54s
471:	learn: 0.4285994	total: 2m 35s	remaining: 2m 53s
472:	learn: 0.4285100	total: 2m 35s	remaining: 2m 53s
473:	learn: 0.4284409	total: 2m 35s	remaining: 2m 52s
474:	learn: 0.4283483	total: 2m 36s	remaining: 2m 52s
475:	learn: 0.4282510	total: 2m 36s	remaining: 2m 52s
476:	learn: 0.4281711	total: 2m 36s	remaining: 2m 51s
477:	learn: 0.4280916	total: 2m 37s	remaining: 2m 51s
478:	learn: 0.4279997	total: 2m 37s	remaining: 2m 51s
479:	learn: 0.4279288	total: 2m 37s	remaining: 2m 50s
480:	learn: 0.4278324	total: 2m 37s	remaining: 2m 50s
481:	learn: 0.4277458	total: 2m 38s	remaining: 2m 50s
482:	learn: 0.4276508	total: 2m 38s	remaining: 2m 49s
483:	learn: 0.4275858	total: 2m 38s	remaining: 2m 49s
484:	learn: 0.4274901	total: 2m 39s	remaining: 2m 48s
485:	learn: 0.4273720	total: 2m 39s	remaining: 2m 48s
486:	learn: 0.4272894	total: 2m 39s	remaining: 2m 48s
487:	learn: 0.4272183	total: 2m 40s	remaining: 2m 47s
488:	learn: 0.4271183	total: 2m 40s	remaining: 2m 47s
489:	learn: 0.4270324	total: 2m 40s	remaining: 2m 47s
490:	learn: 0.4269352	total: 2m 41s	remaining: 2m 46s
491:	learn: 0.4268579	total: 2m 41s	remaining: 2m 46s
492:	learn: 0.4267675	total: 2m 41s	remaining: 2m 46s
493:	learn: 0.4266593	total: 2m 42s	remaining: 2m 45s
494:	learn: 0.4265509	total: 2m 42s	remaining: 2m 45s
495:	learn: 0.4264650	total: 2m 42s	remaining: 2m 45s
496:	learn: 0.4263970	total: 2m 42s	remaining: 2m 44s
497:	learn: 0.4263150	total: 2m 43s	remaining: 2m 44s
498:	learn: 0.4262348	total: 2m 43s	remaining: 2m 44s
499:	learn: 0.4261381	total: 2m 43s	remaining: 2m 43s
500:	learn: 0.4260392	total: 2m 44s	remaining: 2m 43s
501:	learn: 0.4259622	total: 2m 44s	remaining: 2m 43s
502:	learn: 0.4258712	total: 2m 44s	remaining: 2m 42s
503:	learn: 0.4257437	total: 2m 45s	remaining: 2m 42s
504:	learn: 0.4256576	total: 2m 45s	remaining: 2m 42s
505:	learn: 0.4255811	total: 2m 45s	remaining: 2m 41s
506:	learn: 0.4254874	total: 2m 46s	remaining: 2m 41s
507:	learn: 0.4253933	total: 2m 46s	remaining: 2m 41s
508:	learn: 0.4253107	total: 2m 46s	remaining: 2m 40s
509:	learn: 0.4252389	total: 2m 46s	remaining: 2m 40s
510:	learn: 0.4251820	total: 2m 47s	remaining: 2m 40s
511:	learn: 0.4250801	total: 2m 47s	remaining: 2m 39s
512:	learn: 0.4250258	total: 2m 47s	remaining: 2m 39s
513:	learn: 0.4249439	total: 2m 48s	remaining: 2m 39s
514:	learn: 0.4248774	total: 2m 48s	remaining: 2m 38s
515:	learn: 0.4247661	total: 2m 48s	remaining: 2m 38s
516:	learn: 0.4246610	total: 2m 49s	remaining: 2m 38s
517:	learn: 0.4245576	total: 2m 49s	remaining: 2m 37s
518:	learn: 0.4244749	total: 2m 49s	remaining: 2m 37s
519:	learn: 0.4244023	total: 2m 50s	remaining: 2m 36s
520:	learn: 0.4243256	total: 2m 50s	remaining: 2m 36s
521:	learn: 0.4242375	total: 2m 50s	remaining: 2m 36s
522:	learn: 0.4241505	total: 2m 50s	remaining: 2m 35s
523:	learn: 0.4240645	total: 2m 51s	remaining: 2m 35s
524:	learn: 0.4239703	total: 2m 51s	remaining: 2m 35s
525:	learn: 0.4239352	total: 2m 51s	remaining: 2m 34s
526:	learn: 0.4238399	total: 2m 52s	remaining: 2m 34s
527:	learn: 0.4237642	total: 2m 52s	remaining: 2m 34s
528:	learn: 0.4236591	total: 2m 52s	remaining: 2m 33s
529:	learn: 0.4235584	total: 2m 53s	remaining: 2m 33s
530:	learn: 0.4234627	total: 2m 53s	remaining: 2m 33s
531:	learn: 0.4233883	total: 2m 53s	remaining: 2m 32s
532:	learn: 0.4232888	total: 2m 54s	remaining: 2m 32s
533:	learn: 0.4231813	total: 2m 54s	remaining: 2m 32s
534:	learn: 0.4231018	total: 2m 54s	remaining: 2m 31s
535:	learn: 0.4230046	total: 2m 54s	remaining: 2m 31s
536:	learn: 0.4229146	total: 2m 55s	remaining: 2m 31s
537:	learn: 0.4228344	total: 2m 55s	remaining: 2m 30s
538:	learn: 0.4227398	total: 2m 55s	remaining: 2m 30s
539:	learn: 0.4226766	total: 2m 56s	remaining: 2m 30s
540:	learn: 0.4225845	total: 2m 56s	remaining: 2m 29s
541:	learn: 0.4224903	total: 2m 56s	remaining: 2m 29s
542:	learn: 0.4224131	total: 2m 57s	remaining: 2m 29s
543:	learn: 0.4223190	total: 2m 57s	remaining: 2m 28s
544:	learn: 0.4222269	total: 2m 57s	remaining: 2m 28s
545:	learn: 0.4221353	total: 2m 57s	remaining: 2m 27s
546:	learn: 0.4220795	total: 2m 58s	remaining: 2m 27s
547:	learn: 0.4219685	total: 2m 58s	remaining: 2m 27s
548:	learn: 0.4219083	total: 2m 58s	remaining: 2m 26s
549:	learn: 0.4218317	total: 2m 59s	remaining: 2m 26s
550:	learn: 0.4217624	total: 2m 59s	remaining: 2m 26s
551:	learn: 0.4217160	total: 2m 59s	remaining: 2m 25s
552:	learn: 0.4216326	total: 3m	remaining: 2m 25s
553:	learn: 0.4215383	total: 3m	remaining: 2m 25s
554:	learn: 0.4214532	total: 3m	remaining: 2m 24s
555:	learn: 0.4213688	total: 3m 1s	remaining: 2m 24s
556:	learn: 0.4212606	total: 3m 1s	remaining: 2m 24s
557:	learn: 0.4211864	total: 3m 1s	remaining: 2m 23s
558:	learn: 0.4210884	total: 3m 1s	remaining: 2m 23s
559:	learn: 0.4209714	total: 3m 2s	remaining: 2m 23s
560:	learn: 0.4208821	total: 3m 2s	remaining: 2m 22s
561:	learn: 0.4207890	total: 3m 2s	remaining: 2m 22s
562:	learn: 0.4207151	total: 3m 3s	remaining: 2m 22s
563:	learn: 0.4206297	total: 3m 3s	remaining: 2m 21s
564:	learn: 0.4205584	total: 3m 3s	remaining: 2m 21s
565:	learn: 0.4204680	total: 3m 4s	remaining: 2m 21s
566:	learn: 0.4203686	total: 3m 4s	remaining: 2m 20s
567:	learn: 0.4203112	total: 3m 4s	remaining: 2m 20s
568:	learn: 0.4202307	total: 3m 5s	remaining: 2m 20s
569:	learn: 0.4201599	total: 3m 5s	remaining: 2m 19s
570:	learn: 0.4200802	total: 3m 5s	remaining: 2m 19s
571:	learn: 0.4199775	total: 3m 6s	remaining: 2m 19s
572:	learn: 0.4199189	total: 3m 6s	remaining: 2m 18s
573:	learn: 0.4198374	total: 3m 6s	remaining: 2m 18s
574:	learn: 0.4197563	total: 3m 7s	remaining: 2m 18s
575:	learn: 0.4196772	total: 3m 7s	remaining: 2m 17s
576:	learn: 0.4195959	total: 3m 7s	remaining: 2m 17s
577:	learn: 0.4195064	total: 3m 7s	remaining: 2m 17s
578:	learn: 0.4193843	total: 3m 8s	remaining: 2m 16s
579:	learn: 0.4192907	total: 3m 8s	remaining: 2m 16s
580:	learn: 0.4192359	total: 3m 8s	remaining: 2m 16s
581:	learn: 0.4191243	total: 3m 9s	remaining: 2m 15s
582:	learn: 0.4190320	total: 3m 9s	remaining: 2m 15s
583:	learn: 0.4189424	total: 3m 9s	remaining: 2m 15s
584:	learn: 0.4188636	total: 3m 10s	remaining: 2m 14s
585:	learn: 0.4187900	total: 3m 10s	remaining: 2m 14s
586:	learn: 0.4186978	total: 3m 10s	remaining: 2m 14s
587:	learn: 0.4186097	total: 3m 11s	remaining: 2m 13s
588:	learn: 0.4185201	total: 3m 11s	remaining: 2m 13s
589:	learn: 0.4184330	total: 3m 11s	remaining: 2m 13s
590:	learn: 0.4183571	total: 3m 11s	remaining: 2m 12s
591:	learn: 0.4182768	total: 3m 12s	remaining: 2m 12s
592:	learn: 0.4181818	total: 3m 12s	remaining: 2m 12s
593:	learn: 0.4181115	total: 3m 12s	remaining: 2m 11s
594:	learn: 0.4180214	total: 3m 13s	remaining: 2m 11s
595:	learn: 0.4179263	total: 3m 13s	remaining: 2m 11s
596:	learn: 0.4178542	total: 3m 13s	remaining: 2m 10s
597:	learn: 0.4177762	total: 3m 14s	remaining: 2m 10s
598:	learn: 0.4177025	total: 3m 14s	remaining: 2m 10s
599:	learn: 0.4176213	total: 3m 14s	remaining: 2m 9s
600:	learn: 0.4175323	total: 3m 15s	remaining: 2m 9s
601:	learn: 0.4174239	total: 3m 15s	remaining: 2m 9s
602:	learn: 0.4173396	total: 3m 15s	remaining: 2m 8s
603:	learn: 0.4172745	total: 3m 16s	remaining: 2m 8s
604:	learn: 0.4171700	total: 3m 16s	remaining: 2m 8s
605:	learn: 0.4170874	total: 3m 16s	remaining: 2m 7s
606:	learn: 0.4170017	total: 3m 17s	remaining: 2m 7s
607:	learn: 0.4169215	total: 3m 17s	remaining: 2m 7s
608:	learn: 0.4168542	total: 3m 17s	remaining: 2m 6s
609:	learn: 0.4167811	total: 3m 18s	remaining: 2m 6s
610:	learn: 0.4167134	total: 3m 18s	remaining: 2m 6s
611:	learn: 0.4166290	total: 3m 18s	remaining: 2m 5s
612:	learn: 0.4165431	total: 3m 18s	remaining: 2m 5s
613:	learn: 0.4164647	total: 3m 19s	remaining: 2m 5s
614:	learn: 0.4164271	total: 3m 19s	remaining: 2m 4s
615:	learn: 0.4163434	total: 3m 19s	remaining: 2m 4s
616:	learn: 0.4162459	total: 3m 20s	remaining: 2m 4s
617:	learn: 0.4161412	total: 3m 20s	remaining: 2m 3s
618:	learn: 0.4160515	total: 3m 20s	remaining: 2m 3s

619:	learn: 0.4159509	total: 3m 21s	remaining: 2m 3s
620:	learn: 0.4158698	total: 3m 21s	remaining: 2m 2s
621:	learn: 0.4157549	total: 3m 21s	remaining: 2m 2s
622:	learn: 0.4156821	total: 3m 22s	remaining: 2m 2s
623:	learn: 0.4155989	total: 3m 22s	remaining: 2m 1s
624:	learn: 0.4155250	total: 3m 22s	remaining: 2m 1s
625:	learn: 0.4154782	total: 3m 22s	remaining: 2m 1s
626:	learn: 0.4153948	total: 3m 23s	remaining: 2m
627:	learn: 0.4153069	total: 3m 23s	remaining: 2m
628:	learn: 0.4152554	total: 3m 23s	remaining: 2m
629:	learn: 0.4151750	total: 3m 24s	remaining: 1m 59s
630:	learn: 0.4151076	total: 3m 24s	remaining: 1m 59s
631:	learn: 0.4150325	total: 3m 24s	remaining: 1m 59s
632:	learn: 0.4149552	total: 3m 25s	remaining: 1m 58s
633:	learn: 0.4148180	total: 3m 25s	remaining: 1m 58s
634:	learn: 0.4147389	total: 3m 25s	remaining: 1m 58s
635:	learn: 0.4146510	total: 3m 26s	remaining: 1m 57s
636:	learn: 0.4145725	total: 3m 26s	remaining: 1m 57s
637:	learn: 0.4144824	total: 3m 26s	remaining: 1m 57s
638:	learn: 0.4143833	total: 3m 26s	remaining: 1m 56s
639:	learn: 0.4143030	total: 3m 27s	remaining: 1m 56s
640:	learn: 0.4142052	total: 3m 27s	remaining: 1m 56s
641:	learn: 0.4141171	total: 3m 27s	remaining: 1m 55s
642:	learn: 0.4140286	total: 3m 28s	remaining: 1m 55s
643:	learn: 0.4139524	total: 3m 28s	remaining: 1m 55s
644:	learn: 0.4138534	total: 3m 28s	remaining: 1m 54s
645:	learn: 0.4137512	total: 3m 29s	remaining: 1m 54s
646:	learn: 0.4136569	total: 3m 29s	remaining: 1m 54s
647:	learn: 0.4135771	total: 3m 29s	remaining: 1m 53s
648:	learn: 0.4134998	total: 3m 30s	remaining: 1m 53s
649:	learn: 0.4134129	total: 3m 30s	remaining: 1m 53s
650:	learn: 0.4133411	total: 3m 30s	remaining: 1m 52s
651:	learn: 0.4132493	total: 3m 31s	remaining: 1m 52s
652:	learn: 0.4131416	total: 3m 31s	remaining: 1m 52s
653:	learn: 0.4130608	total: 3m 31s	remaining: 1m 51s
654:	learn: 0.4129852	total: 3m 31s	remaining: 1m 51s
655:	learn: 0.4129244	total: 3m 32s	remaining: 1m 51s
656:	learn: 0.4128371	total: 3m 32s	remaining: 1m 51s
657:	learn: 0.4127401	total: 3m 32s	remaining: 1m 50s
658:	learn: 0.4126601	total: 3m 33s	remaining: 1m 50s
659:	learn: 0.4125841	total: 3m 33s	remaining: 1m 49s
660:	learn: 0.4125101	total: 3m 33s	remaining: 1m 49s
661:	learn: 0.4124258	total: 3m 34s	remaining: 1m 49s
662:	learn: 0.4123521	total: 3m 34s	remaining: 1m 48s
663:	learn: 0.4122602	total: 3m 34s	remaining: 1m 48s
664:	learn: 0.4121717	total: 3m 35s	remaining: 1m 48s
665:	learn: 0.4120367	total: 3m 35s	remaining: 1m 48s
666:	learn: 0.4119558	total: 3m 35s	remaining: 1m 47s
667:	learn: 0.4118824	total: 3m 36s	remaining: 1m 47s
668:	learn: 0.4117977	total: 3m 36s	remaining: 1m 47s
669:	learn: 0.4117082	total: 3m 36s	remaining: 1m 46s
670:	learn: 0.4116066	total: 3m 36s	remaining: 1m 46s
671:	learn: 0.4115359	total: 3m 37s	remaining: 1m 46s
672:	learn: 0.4114693	total: 3m 37s	remaining: 1m 45s
673:	learn: 0.4113778	total: 3m 37s	remaining: 1m 45s
674:	learn: 0.4113277	total: 3m 38s	remaining: 1m 45s
675:	learn: 0.4112484	total: 3m 38s	remaining: 1m 44s
676:	learn: 0.4111673	total: 3m 38s	remaining: 1m 44s
677:	learn: 0.4110795	total: 3m 39s	remaining: 1m 44s
678:	learn: 0.4110098	total: 3m 39s	remaining: 1m 43s
679:	learn: 0.4109105	total: 3m 39s	remaining: 1m 43s
680:	learn: 0.4108352	total: 3m 40s	remaining: 1m 43s
681:	learn: 0.4107673	total: 3m 40s	remaining: 1m 42s
682:	learn: 0.4106819	total: 3m 40s	remaining: 1m 42s
683:	learn: 0.4106243	total: 3m 40s	remaining: 1m 42s
684:	learn: 0.4105583	total: 3m 41s	remaining: 1m 41s
685:	learn: 0.4104705	total: 3m 41s	remaining: 1m 41s
686:	learn: 0.4103660	total: 3m 41s	remaining: 1m 41s
687:	learn: 0.4103088	total: 3m 42s	remaining: 1m 40s
688:	learn: 0.4102540	total: 3m 42s	remaining: 1m 40s
689:	learn: 0.4101735	total: 3m 42s	remaining: 1m 40s
690:	learn: 0.4100907	total: 3m 43s	remaining: 1m 39s
691:	learn: 0.4100078	total: 3m 43s	remaining: 1m 39s
692:	learn: 0.4099239	total: 3m 43s	remaining: 1m 39s
693:	learn: 0.4098477	total: 3m 43s	remaining: 1m 38s
694:	learn: 0.4097953	total: 3m 44s	remaining: 1m 38s
695:	learn: 0.4096964	total: 3m 44s	remaining: 1m 38s
696:	learn: 0.4096140	total: 3m 44s	remaining: 1m 37s
697:	learn: 0.4095141	total: 3m 45s	remaining: 1m 37s
698:	learn: 0.4094368	total: 3m 45s	remaining: 1m 37s
699:	learn: 0.4093498	total: 3m 45s	remaining: 1m 36s
700:	learn: 0.4092667	total: 3m 46s	remaining: 1m 36s
701:	learn: 0.4091839	total: 3m 46s	remaining: 1m 36s
702:	learn: 0.4091091	total: 3m 46s	remaining: 1m 35s
703:	learn: 0.4090513	total: 3m 47s	remaining: 1m 35s
704:	learn: 0.4089432	total: 3m 47s	remaining: 1m 35s
705:	learn: 0.4088449	total: 3m 47s	remaining: 1m 34s
706:	learn: 0.4087557	total: 3m 48s	remaining: 1m 34s
707:	learn: 0.4086662	total: 3m 48s	remaining: 1m 34s
708:	learn: 0.4085946	total: 3m 48s	remaining: 1m 33s
709:	learn: 0.4085072	total: 3m 48s	remaining: 1m 33s
710:	learn: 0.4084111	total: 3m 49s	remaining: 1m 33s
711:	learn: 0.4083497	total: 3m 49s	remaining: 1m 32s
712:	learn: 0.4082851	total: 3m 49s	remaining: 1m 32s
713:	learn: 0.4081878	total: 3m 50s	remaining: 1m 32s
714:	learn: 0.4081142	total: 3m 50s	remaining: 1m 31s
715:	learn: 0.4080486	total: 3m 50s	remaining: 1m 31s
716:	learn: 0.4080145	total: 3m 51s	remaining: 1m 31s
717:	learn: 0.4079191	total: 3m 51s	remaining: 1m 30s
718:	learn: 0.4078569	total: 3m 51s	remaining: 1m 30s
719:	learn: 0.4077728	total: 3m 52s	remaining: 1m 30s
720:	learn: 0.4076845	total: 3m 52s	remaining: 1m 29s
721:	learn: 0.4076105	total: 3m 52s	remaining: 1m 29s
722:	learn: 0.4075204	total: 3m 52s	remaining: 1m 29s
723:	learn: 0.4074391	total: 3m 53s	remaining: 1m 28s
724:	learn: 0.4073535	total: 3m 53s	remaining: 1m 28s
725:	learn: 0.4072704	total: 3m 53s	remaining: 1m 28s
726:	learn: 0.4071822	total: 3m 54s	remaining: 1m 27s
727:	learn: 0.4071118	total: 3m 54s	remaining: 1m 27s
728:	learn: 0.4070330	total: 3m 54s	remaining: 1m 27s
729:	learn: 0.4069502	total: 3m 55s	remaining: 1m 26s
730:	learn: 0.4068703	total: 3m 55s	remaining: 1m 26s
731:	learn: 0.4067809	total: 3m 55s	remaining: 1m 26s
732:	learn: 0.4067012	total: 3m 56s	remaining: 1m 25s
733:	learn: 0.4066319	total: 3m 56s	remaining: 1m 25s
734:	learn: 0.4065608	total: 3m 56s	remaining: 1m 25s
735:	learn: 0.4064670	total: 3m 56s	remaining: 1m 24s
736:	learn: 0.4064125	total: 3m 57s	remaining: 1m 24s
737:	learn: 0.4063431	total: 3m 57s	remaining: 1m 24s
738:	learn: 0.4062778	total: 3m 57s	remaining: 1m 23s
739:	learn: 0.4061830	total: 3m 58s	remaining: 1m 23s
740:	learn: 0.4060884	total: 3m 58s	remaining: 1m 23s
741:	learn: 0.4059859	total: 3m 58s	remaining: 1m 23s
742:	learn: 0.4059007	total: 3m 59s	remaining: 1m 22s
743:	learn: 0.4058259	total: 3m 59s	remaining: 1m 22s
744:	learn: 0.4057631	total: 3m 59s	remaining: 1m 22s
745:	learn: 0.4056538	total: 4m	remaining: 1m 21s
746:	learn: 0.4055642	total: 4m	remaining: 1m 21s
747:	learn: 0.4055091	total: 4m	remaining: 1m 21s
748:	learn: 0.4054615	total: 4m 1s	remaining: 1m 20s
749:	learn: 0.4053838	total: 4m 1s	remaining: 1m 20s
750:	learn: 0.4053175	total: 4m 1s	remaining: 1m 20s
751:	learn: 0.4052603	total: 4m 2s	remaining: 1m 19s
752:	learn: 0.4051728	total: 4m 2s	remaining: 1m 19s
753:	learn: 0.4051038	total: 4m 2s	remaining: 1m 19s
754:	learn: 0.4050001	total: 4m 2s	remaining: 1m 18s
755:	learn: 0.4048971	total: 4m 3s	remaining: 1m 18s
756:	learn: 0.4048528	total: 4m 3s	remaining: 1m 18s
757:	learn: 0.4048050	total: 4m 3s	remaining: 1m 17s
758:	learn: 0.4047312	total: 4m 4s	remaining: 1m 17s
759:	learn: 0.4046615	total: 4m 4s	remaining: 1m 17s
760:	learn: 0.4045814	total: 4m 4s	remaining: 1m 16s
761:	learn: 0.4044986	total: 4m 5s	remaining: 1m 16s
762:	learn: 0.4044403	total: 4m 5s	remaining: 1m 16s
763:	learn: 0.4043615	total: 4m 5s	remaining: 1m 15s
764:	learn: 0.4042892	total: 4m 6s	remaining: 1m 15s
765:	learn: 0.4042023	total: 4m 6s	remaining: 1m 15s
766:	learn: 0.4041159	total: 4m 6s	remaining: 1m 14s
767:	learn: 0.4040236	total: 4m 7s	remaining: 1m 14s
768:	learn: 0.4039349	total: 4m 7s	remaining: 1m 14s
769:	learn: 0.4038492	total: 4m 7s	remaining: 1m 13s
770:	learn: 0.4037705	total: 4m 7s	remaining: 1m 13s
771:	learn: 0.4036887	total: 4m 8s	remaining: 1m 13s

772:	learn: 0.4036083	total: 4m 8s	remaining: 1m 13s
773:	learn: 0.4035112	total: 4m 8s	remaining: 1m 12s
774:	learn: 0.4034165	total: 4m 9s	remaining: 1m 12s
775:	learn: 0.4033320	total: 4m 9s	remaining: 1m 12s
776:	learn: 0.4032697	total: 4m 9s	remaining: 1m 11s
777:	learn: 0.4032019	total: 4m 10s	remaining: 1m 11s
778:	learn: 0.4031279	total: 4m 10s	remaining: 1m 11s
779:	learn: 0.4030489	total: 4m 10s	remaining: 1m 10s
780:	learn: 0.4029773	total: 4m 11s	remaining: 1m 10s
781:	learn: 0.4028790	total: 4m 11s	remaining: 1m 10s
782:	learn: 0.4028207	total: 4m 11s	remaining: 1m 9s
783:	learn: 0.4027535	total: 4m 11s	remaining: 1m 9s
784:	learn: 0.4027004	total: 4m 12s	remaining: 1m 9s
785:	learn: 0.4026080	total: 4m 12s	remaining: 1m 8s
786:	learn: 0.4025004	total: 4m 12s	remaining: 1m 8s
787:	learn: 0.4024422	total: 4m 13s	remaining: 1m 8s
788:	learn: 0.4023594	total: 4m 13s	remaining: 1m 7s
789:	learn: 0.4022897	total: 4m 13s	remaining: 1m 7s
790:	learn: 0.4021987	total: 4m 14s	remaining: 1m 7s
791:	learn: 0.4021464	total: 4m 14s	remaining: 1m 6s
792:	learn: 0.4020631	total: 4m 14s	remaining: 1m 6s
793:	learn: 0.4019778	total: 4m 14s	remaining: 1m 6s
794:	learn: 0.4019008	total: 4m 15s	remaining: 1m 5s
795:	learn: 0.4018143	total: 4m 15s	remaining: 1m 5s
796:	learn: 0.4017386	total: 4m 15s	remaining: 1m 5s
797:	learn: 0.4016581	total: 4m 16s	remaining: 1m 4s
798:	learn: 0.4015801	total: 4m 16s	remaining: 1m 4s
799:	learn: 0.4015046	total: 4m 16s	remaining: 1m 4s
800:	learn: 0.4014271	total: 4m 17s	remaining: 1m 3s
801:	learn: 0.4013780	total: 4m 17s	remaining: 1m 3s
802:	learn: 0.4013216	total: 4m 17s	remaining: 1m 3s
803:	learn: 0.4012186	total: 4m 18s	remaining: 1m 2s
804:	learn: 0.4011391	total: 4m 18s	remaining: 1m 2s
805:	learn: 0.4010553	total: 4m 18s	remaining: 1m 2s
806:	learn: 0.4009818	total: 4m 18s	remaining: 1m 1s
807:	learn: 0.4009034	total: 4m 19s	remaining: 1m 1s
808:	learn: 0.4008304	total: 4m 19s	remaining: 1m 1s
809:	learn: 0.4007616	total: 4m 19s	remaining: 1m
810:	learn: 0.4007156	total: 4m 20s	remaining: 1m
811:	learn: 0.4006224	total: 4m 20s	remaining: 1m
812:	learn: 0.4005502	total: 4m 20s	remaining: 60s
813:	learn: 0.4004547	total: 4m 21s	remaining: 59.7s
814:	learn: 0.4003726	total: 4m 21s	remaining: 59.3s
815:	learn: 0.4002747	total: 4m 21s	remaining: 59s
816:	learn: 0.4002122	total: 4m 22s	remaining: 58.7s
817:	learn: 0.4001476	total: 4m 22s	remaining: 58.4s
818:	learn: 0.4000597	total: 4m 22s	remaining: 58s
819:	learn: 0.3999998	total: 4m 22s	remaining: 57.7s
820:	learn: 0.3999126	total: 4m 23s	remaining: 57.4s
821:	learn: 0.3998315	total: 4m 23s	remaining: 57.1s
822:	learn: 0.3997307	total: 4m 23s	remaining: 56.7s
823:	learn: 0.3996473	total: 4m 24s	remaining: 56.4s
824:	learn: 0.3995701	total: 4m 24s	remaining: 56.1s
825:	learn: 0.3995117	total: 4m 24s	remaining: 55.8s
826:	learn: 0.3994260	total: 4m 25s	remaining: 55.4s
827:	learn: 0.3993599	total: 4m 25s	remaining: 55.1s
828:	learn: 0.3992842	total: 4m 25s	remaining: 54.8s
829:	learn: 0.3992222	total: 4m 25s	remaining: 54.5s
830:	learn: 0.3991730	total: 4m 26s	remaining: 54.2s
831:	learn: 0.3990966	total: 4m 26s	remaining: 53.8s
832:	learn: 0.3990123	total: 4m 26s	remaining: 53.5s
833:	learn: 0.3989334	total: 4m 27s	remaining: 53.2s
834:	learn: 0.3988485	total: 4m 27s	remaining: 52.9s
835:	learn: 0.3987445	total: 4m 28s	remaining: 52.6s
836:	learn: 0.3986786	total: 4m 28s	remaining: 52.2s
837:	learn: 0.3986073	total: 4m 28s	remaining: 51.9s
838:	learn: 0.3985345	total: 4m 28s	remaining: 51.6s
839:	learn: 0.3984804	total: 4m 29s	remaining: 51.3s
840:	learn: 0.3983923	total: 4m 29s	remaining: 51s
841:	learn: 0.3983142	total: 4m 29s	remaining: 50.6s
842:	learn: 0.3982404	total: 4m 30s	remaining: 50.3s
843:	learn: 0.3981415	total: 4m 30s	remaining: 50s
844:	learn: 0.3980728	total: 4m 30s	remaining: 49.7s
845:	learn: 0.3980056	total: 4m 30s	remaining: 49.3s
846:	learn: 0.3979225	total: 4m 31s	remaining: 49s
847:	learn: 0.3978520	total: 4m 31s	remaining: 48.7s
848:	learn: 0.3977657	total: 4m 31s	remaining: 48.4s
849:	learn: 0.3976960	total: 4m 32s	remaining: 48s
850:	learn: 0.3976215	total: 4m 32s	remaining: 47.7s
851:	learn: 0.3975442	total: 4m 32s	remaining: 47.4s
852:	learn: 0.3974838	total: 4m 33s	remaining: 47.1s
853:	learn: 0.3974172	total: 4m 33s	remaining: 46.7s
854:	learn: 0.3973572	total: 4m 33s	remaining: 46.4s
855:	learn: 0.3972915	total: 4m 33s	remaining: 46.1s
856:	learn: 0.3972487	total: 4m 34s	remaining: 45.8s
857:	learn: 0.3971814	total: 4m 34s	remaining: 45.4s
858:	learn: 0.3971030	total: 4m 34s	remaining: 45.1s
859:	learn: 0.3970353	total: 4m 35s	remaining: 44.8s
860:	learn: 0.3969691	total: 4m 35s	remaining: 44.5s
861:	learn: 0.3968982	total: 4m 35s	remaining: 44.1s
862:	learn: 0.3968022	total: 4m 36s	remaining: 43.8s
863:	learn: 0.3967414	total: 4m 36s	remaining: 43.5s
864:	learn: 0.3966781	total: 4m 36s	remaining: 43.2s
865:	learn: 0.3966273	total: 4m 36s	remaining: 42.8s
866:	learn: 0.3965503	total: 4m 37s	remaining: 42.5s
867:	learn: 0.3964794	total: 4m 37s	remaining: 42.2s
868:	learn: 0.3964209	total: 4m 37s	remaining: 41.9s
869:	learn: 0.3963574	total: 4m 38s	remaining: 41.6s
870:	learn: 0.3962577	total: 4m 38s	remaining: 41.3s
871:	learn: 0.3961669	total: 4m 38s	remaining: 40.9s
872:	learn: 0.3960734	total: 4m 39s	remaining: 40.6s
873:	learn: 0.3960094	total: 4m 39s	remaining: 40.3s
874:	learn: 0.3959428	total: 4m 39s	remaining: 40s
875:	learn: 0.3958690	total: 4m 40s	remaining: 39.6s
876:	learn: 0.3957991	total: 4m 40s	remaining: 39.3s
877:	learn: 0.3957386	total: 4m 40s	remaining: 39s
878:	learn: 0.3956699	total: 4m 40s	remaining: 38.7s
879:	learn: 0.3955754	total: 4m 41s	remaining: 38.4s
880:	learn: 0.3955278	total: 4m 41s	remaining: 38s
881:	learn: 0.3954632	total: 4m 41s	remaining: 37.7s
882:	learn: 0.3953901	total: 4m 42s	remaining: 37.4s
883:	learn: 0.3953143	total: 4m 42s	remaining: 37.1s
884:	learn: 0.3952345	total: 4m 42s	remaining: 36.7s
885:	learn: 0.3951690	total: 4m 43s	remaining: 36.4s
886:	learn: 0.3950790	total: 4m 43s	remaining: 36.1s
887:	learn: 0.3950076	total: 4m 43s	remaining: 35.8s
888:	learn: 0.3949347	total: 4m 43s	remaining: 35.5s
889:	learn: 0.3948529	total: 4m 44s	remaining: 35.1s
890:	learn: 0.3947790	total: 4m 44s	remaining: 34.8s
891:	learn: 0.3946760	total: 4m 44s	remaining: 34.5s
892:	learn: 0.3946071	total: 4m 45s	remaining: 34.2s
893:	learn: 0.3945517	total: 4m 45s	remaining: 33.9s
894:	learn: 0.3944829	total: 4m 45s	remaining: 33.5s
895:	learn: 0.3944272	total: 4m 46s	remaining: 33.2s
896:	learn: 0.3943551	total: 4m 46s	remaining: 32.9s
897:	learn: 0.3943276	total: 4m 46s	remaining: 32.6s
898:	learn: 0.3942626	total: 4m 47s	remaining: 32.2s
899:	learn: 0.3941899	total: 4m 47s	remaining: 31.9s
900:	learn: 0.3941370	total: 4m 47s	remaining: 31.6s
901:	learn: 0.3940534	total: 4m 47s	remaining: 31.3s
902:	learn: 0.3939737	total: 4m 48s	remaining: 31s
903:	learn: 0.3938933	total: 4m 48s	remaining: 30.6s
904:	learn: 0.3938231	total: 4m 48s	remaining: 30.3s
905:	learn: 0.3937553	total: 4m 49s	remaining: 30s
906:	learn: 0.3936859	total: 4m 49s	remaining: 29.7s
907:	learn: 0.3936052	total: 4m 49s	remaining: 29.4s
908:	learn: 0.3935348	total: 4m 50s	remaining: 29s
909:	learn: 0.3934395	total: 4m 50s	remaining: 28.7s
910:	learn: 0.3933621	total: 4m 50s	remaining: 28.4s
911:	learn: 0.3932851	total: 4m 50s	remaining: 28.1s
912:	learn: 0.3932150	total: 4m 51s	remaining: 27.7s
913:	learn: 0.3931594	total: 4m 51s	remaining: 27.4s
914:	learn: 0.3930867	total: 4m 51s	remaining: 27.1s
915:	learn: 0.3929895	total: 4m 52s	remaining: 26.8s
916:	learn: 0.3929306	total: 4m 52s	remaining: 26.5s
917:	learn: 0.3928628	total: 4m 52s	remaining: 26.1s
918:	learn: 0.3927944	total: 4m 53s	remaining: 25.8s
919:	learn: 0.3927174	total: 4m 53s	remaining: 25.5s
920:	learn: 0.3926366	total: 4m 53s	remaining: 25.2s
921:	learn: 0.3925633	total: 4m 53s	remaining: 24.9s
922:	learn: 0.3924968	total: 4m 54s	remaining: 24.5s
923:	learn: 0.3924251	total: 4m 54s	remaining: 24.2s
924:	learn: 0.3923635	total: 4m 54s	remaining: 23.9s
925:	learn: 0.3923052	total: 4m 55s	remaining: 23.6s
926:	learn: 0.3922153	total: 4m 55s	remaining: 23.3s
927:	learn: 0.3921505	total: 4m 55s	remaining: 22.9s

928:	learn: 0.3920390	total: 4m 56s	remaining: 22.6s
929:	learn: 0.3919582	total: 4m 56s	remaining: 22.3s
930:	learn: 0.3918962	total: 4m 56s	remaining: 22s
931:	learn: 0.3918235	total: 4m 57s	remaining: 21.7s
932:	learn: 0.3917480	total: 4m 57s	remaining: 21.3s
933:	learn: 0.3916649	total: 4m 57s	remaining: 21s
934:	learn: 0.3915789	total: 4m 57s	remaining: 20.7s
935:	learn: 0.3915132	total: 4m 58s	remaining: 20.4s
936:	learn: 0.3914698	total: 4m 58s	remaining: 20.1s
937:	learn: 0.3914031	total: 4m 58s	remaining: 19.7s
938:	learn: 0.3912966	total: 4m 59s	remaining: 19.4s
939:	learn: 0.3912327	total: 4m 59s	remaining: 19.1s
940:	learn: 0.3911800	total: 4m 59s	remaining: 18.8s
941:	learn: 0.3911405	total: 5m	remaining: 18.5s
942:	learn: 0.3910655	total: 5m	remaining: 18.2s
943:	learn: 0.3910011	total: 5m	remaining: 17.8s
944:	learn: 0.3909289	total: 5m 1s	remaining: 17.5s
945:	learn: 0.3908439	total: 5m 1s	remaining: 17.2s
946:	learn: 0.3907894	total: 5m 1s	remaining: 16.9s
947:	learn: 0.3907106	total: 5m 1s	remaining: 16.6s
948:	learn: 0.3906337	total: 5m 2s	remaining: 16.2s
949:	learn: 0.3905474	total: 5m 2s	remaining: 15.9s
950:	learn: 0.3904724	total: 5m 2s	remaining: 15.6s
951:	learn: 0.3903859	total: 5m 3s	remaining: 15.3s
952:	learn: 0.3903097	total: 5m 3s	remaining: 15s
953:	learn: 0.3902207	total: 5m 3s	remaining: 14.7s
954:	learn: 0.3901485	total: 5m 4s	remaining: 14.3s
955:	learn: 0.3900730	total: 5m 4s	remaining: 14s
956:	learn: 0.3900014	total: 5m 4s	remaining: 13.7s
957:	learn: 0.3899594	total: 5m 5s	remaining: 13.4s
958:	learn: 0.3898892	total: 5m 5s	remaining: 13.1s
959:	learn: 0.3898216	total: 5m 5s	remaining: 12.7s
960:	learn: 0.3897476	total: 5m 6s	remaining: 12.4s
961:	learn: 0.3896581	total: 5m 6s	remaining: 12.1s
962:	learn: 0.3895756	total: 5m 6s	remaining: 11.8s
963:	learn: 0.3895208	total: 5m 6s	remaining: 11.5s
964:	learn: 0.3894378	total: 5m 7s	remaining: 11.1s
965:	learn: 0.3893654	total: 5m 7s	remaining: 10.8s
966:	learn: 0.3892841	total: 5m 7s	remaining: 10.5s
967:	learn: 0.3892159	total: 5m 8s	remaining: 10.2s
968:	learn: 0.3891464	total: 5m 8s	remaining: 9.87s
969:	learn: 0.3890809	total: 5m 8s	remaining: 9.55s
970:	learn: 0.3890108	total: 5m 9s	remaining: 9.23s
971:	learn: 0.3889486	total: 5m 9s	remaining: 8.91s
972:	learn: 0.3888828	total: 5m 9s	remaining: 8.59s
973:	learn: 0.3888417	total: 5m 9s	remaining: 8.27s
974:	learn: 0.3887369	total: 5m 10s	remaining: 7.95s
975:	learn: 0.3886679	total: 5m 10s	remaining: 7.64s
976:	learn: 0.3886035	total: 5m 10s	remaining: 7.32s
977:	learn: 0.3885314	total: 5m 11s	remaining: 7s
978:	learn: 0.3884582	total: 5m 11s	remaining: 6.68s
979:	learn: 0.3883702	total: 5m 11s	remaining: 6.36s
980:	learn: 0.3882915	total: 5m 12s	remaining: 6.04s
981:	learn: 0.3882091	total: 5m 12s	remaining: 5.73s
982:	learn: 0.3881368	total: 5m 12s	remaining: 5.41s
983:	learn: 0.3880758	total: 5m 13s	remaining: 5.09s
984:	learn: 0.3880092	total: 5m 13s	remaining: 4.77s
985:	learn: 0.3879355	total: 5m 13s	remaining: 4.45s
986:	learn: 0.3878585	total: 5m 13s	remaining: 4.13s
987:	learn: 0.3877722	total: 5m 14s	remaining: 3.82s
988:	learn: 0.3876708	total: 5m 14s	remaining: 3.5s
989:	learn: 0.3875158	total: 5m 14s	remaining: 3.18s
990:	learn: 0.3874356	total: 5m 15s	remaining: 2.86s
991:	learn: 0.3873565	total: 5m 15s	remaining: 2.54s
992:	learn: 0.3872846	total: 5m 15s	remaining: 2.23s
993:	learn: 0.3872367	total: 5m 16s	remaining: 1.91s
994:	learn: 0.3871783	total: 5m 16s	remaining: 1.59s
995:	learn: 0.3871413	total: 5m 16s	remaining: 1.27s
996:	learn: 0.3870761	total: 5m 17s	remaining: 954ms
997:	learn: 0.3869899	total: 5m 17s	remaining: 636ms
998:	learn: 0.3869095	total: 5m 17s	remaining: 318ms
999:	learn: 0.3868474	total: 5m 18s	remaining: 0us
CPU times: user 20min 28s, sys: 43.1 s, total: 21min 11s
Wall time: 5min 29s

CatBoostClassifier()

In [112]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [113]:
y_pred = model.predict(test_pool)
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred))
print(recall_score(y_test, y_pred))

0.8188279301745636
0.7983641536273115
0.8482367758186398

In [114]:
model.plot_tree(
    tree_idx=0,
    pool=train_pool
)

ExecutableNotFound: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH

Этот результат хорош сразу по многим параметрам

* Само значение качества достаточно высокое с первого запуска.
* Мы вообще практически ничего не делали с данными. Только дату немного отформатировали и сразу кинули в модель.
* Мы ничего не делали с моделью. Никаких дополнительных параметров настраивать не пришлось.
* Количество признаков у модели - всего 5! Нам не пришлось делать лишние признаки чтобы подать их в обучение.

<img src="https://raw.githubusercontent.com/ADKosm/lsml-2021-public/main/imgs/vince_mcmahon_6.png" width="300">